#!/usr/bin/env bash
# Puts one kp-themes theme on this Linux desktop: Garuda or Arch, KDE Plasma 6,
# or the shell alone inside WSL.
#
# Hand-written; the files it copies are generated by gates/generate-desktop.mjs:
# this platform's in themes/<theme>/ beside this script, the ones Windows shares
# (FireDragon, Starship, fish, wallpapers) in ../shared/<theme>/.
#
# Steps (a step whose program is not there skips itself, so WSL gets the shell only):
#   shell       ~/.config/starship.toml and ~/.config/fish/conf.d/kp-colors.fish
#   konsole     the colour scheme, set on the KP profile (install.sh makes it the default)
#   plasma      the Plasma colour scheme and the accent colour
#   wallpaper   the desktop picture on every screen
#   lockscreen  the lock screen picture
#   firedragon  userChrome.css, userContent.css and the kp block in user.js, every profile
#
# Every file it replaces that kp-themes did not write is kept once as
# <file>.kp-backup-<timestamp>.
#
# Usage:
#   apply.sh                   pick from the list
#   apply.sh lapis             the whole desktop in KP Lapis
#   apply.sh lapis --only shell,konsole
#   apply.sh lapis --skip wallpaper --dry-run
#   apply.sh --list
set -euo pipefail

HERE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
SHARED="$(dirname "$HERE")/shared"
STATE="${XDG_CONFIG_HOME:-$HOME/.config}/kp-themes"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
STAMP="$(date +%Y%m%d-%H%M%S)"
STEPS="shell konsole plasma wallpaper lockscreen firedragon"

say() { printf '  \033[35m%-11s\033[0m %s\n' "$1" "$2"; }
skip() { printf '  \033[35m%-11s\033[0m \033[90m%s\033[0m\n' "$1" "$2"; }
die() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }
has() { command -v "$1" >/dev/null 2>&1; }

list() {
    local i=0 name label kind
    printf '\n  \033[36mkp-themes\033[0m\n'
    while IFS=$'\t' read -r name label kind; do
        i=$((i + 1))
        printf '  %2d. %-14s %-5s  %s\n' "$i" "$name" "$kind" "$label"
    done <"$SHARED/themes.tsv"
    printf '\n'
}

THEME="" ONLY="" SKIP="" DRY=0
while [ $# -gt 0 ]; do
    case "$1" in
        --list) list; exit 0 ;;
        --only) ONLY="${2//,/ }"; shift ;;
        --skip) SKIP="${2//,/ }"; shift ;;
        --dry-run) DRY=1 ;;
        -h | --help) sed -n '2,/^set -euo/p' "$0" | sed '$d; s/^# \{0,1\}//'; exit 0 ;;
        -*) die "unknown option $1 (see --help)" ;;
        *) THEME="$1" ;;
    esac
    shift
done
for s in $ONLY $SKIP; do
    case " $STEPS " in *" $s "*) ;; *) die "unknown step '$s'; steps: $STEPS" ;; esac
done

if [ -z "$THEME" ]; then
    list
    read -r -p '  Theme (number or name): ' answer
    if [[ "$answer" =~ ^[0-9]+$ ]]; then
        THEME="$(sed -n "${answer}p" "$SHARED/themes.tsv" | cut -f1)"
    else
        THEME="$answer"
    fi
fi
LINE="$(awk -F'\t' -v t="$THEME" '$1 == t' "$SHARED/themes.tsv")"
[ -n "$LINE" ] || die "unknown theme '$THEME'; known: $(cut -f1 "$SHARED/themes.tsv" | tr '\n' ' ')"
LABEL="$(printf '%s' "$LINE" | cut -f2)"
THEME_DIR="$HERE/themes/$THEME"
SHARED_DIR="$SHARED/$THEME"
# KDE names a colour scheme after its file; the generator writes the same name.
SCHEME="KP$(printf '%s' "$LABEL" | tr -cd 'A-Za-z0-9')"

step() {
    if [ -n "$ONLY" ]; then case " $ONLY " in *" $1 "*) return 0 ;; *) return 1 ;; esac; fi
    case " $SKIP " in *" $1 "*) return 1 ;; esac
    return 0
}

# Keep a file kp-themes did not write, once; a previous theme's copy can be made again.
backup() {
    [ -f "$1" ] || return 0
    head -n 3 "$1" | grep -q 'GENERATED by kp-themes' && return 0
    [ "$DRY" = 1 ] || cp -p "$1" "$1.kp-backup-$STAMP"
}

# Copy src to dest, making the folder and keeping what was there.
put() {
    [ "$DRY" = 1 ] && return 0
    mkdir -p "$(dirname "$2")"
    backup "$2"
    cp "$1" "$2"
}

kwrite() {
    if has kwriteconfig6; then kwriteconfig6 "$@"; elif has kwriteconfig5; then kwriteconfig5 "$@"; else return 1; fi
}

plasma_session() {
    case "${XDG_CURRENT_DESKTOP:-}" in *KDE*) return 0 ;; esac
    [ -n "${KDE_FULL_SESSION:-}" ]
}

# The picture to show: the rendered PNG, or the SVG, which Plasma also reads.
picture() {
    if [ -f "$SHARED_DIR/$1.png" ]; then printf '%s' "$SHARED_DIR/$1.png"; else printf '%s' "$SHARED_DIR/$1.svg"; fi
}

printf '\n  \033[36mkp-themes -> Linux: KP %s (%s)\033[0m\n' "$LABEL" "$THEME"
[ "$DRY" = 1 ] && printf '  \033[33mdry run: nothing is written\033[0m\n'
printf '\n'

# --- The shell: Starship and fish ---------------------------------------------
if step shell; then
    put "$SHARED_DIR/starship.toml" "$HOME/.config/starship.toml"
    put "$SHARED_DIR/kp-colors.fish" "$HOME/.config/fish/conf.d/kp-colors.fish"
    say shell 'starship.toml and fish colours written; a new shell shows them'
fi

# --- Konsole ----------------------------------------------------------------------
if step konsole; then
    if has konsole; then
        put "$THEME_DIR/konsole.colorscheme" "$DATA/konsole/kp-$THEME.colorscheme"
        profile="$DATA/konsole/KP.profile"
        if [ "$DRY" = 0 ]; then
            if [ ! -f "$profile" ]; then
                printf '[General]\nName=KP\nParent=FALLBACK/\n\n[Appearance]\nColorScheme=kp-%s\n' "$THEME" >"$profile"
            elif ! kwrite --file "$profile" --group Appearance --key ColorScheme "kp-$THEME"; then
                sed -i "s/^ColorScheme=.*/ColorScheme=kp-$THEME/" "$profile"
            fi
        fi
        say konsole "KP profile set to kp-$THEME; new Konsole windows show it"
    else
        skip konsole 'Konsole not installed, skipped'
    fi
fi

# --- Plasma: colour scheme and accent ---------------------------------------------
if step plasma; then
    if has plasma-apply-colorscheme && plasma_session; then
        put "$THEME_DIR/kde.colors" "$DATA/color-schemes/$SCHEME.colors"
        if [ "$DRY" = 0 ]; then
            # The accent is the theme's signal colour, the selection colour of the scheme.
            accent="$(awk -F= '/^\[Colors:Selection\]/{s=1;next} /^\[/{s=0} s&&$1=="BackgroundNormal"{print $2; exit}' "$THEME_DIR/kde.colors")"
            kwrite --file kdeglobals --group General --key accentColorFromWallpaper false || true
            kwrite --file kdeglobals --group General --key AccentColor "$accent" || true
            # It refuses to apply the scheme that is already active; that is fine.
            plasma-apply-colorscheme "$SCHEME" >/dev/null 2>&1 || true
        fi
        say plasma "colour scheme $SCHEME and accent applied"
    else
        skip plasma 'no Plasma session, skipped'
    fi
fi

# --- Wallpaper --------------------------------------------------------------------
if step wallpaper; then
    if has plasma-apply-wallpaperimage && plasma_session; then
        src="$(picture wallpaper)"
        dest="$DATA/wallpapers/kp-themes/$THEME.${src##*.}"
        put "$src" "$dest"
        [ "$DRY" = 1 ] || plasma-apply-wallpaperimage "$dest" >/dev/null
        say wallpaper "$(basename "$dest") on every screen"
    else
        skip wallpaper 'no Plasma session, skipped'
    fi
fi

# --- Lock screen ------------------------------------------------------------------
# The login screen (SDDM) belongs to root and is left alone.
if step lockscreen; then
    if plasma_session && (has kwriteconfig6 || has kwriteconfig5); then
        src="$(picture wallpaper-lock)"
        dest="$DATA/wallpapers/kp-themes/$THEME-lock.${src##*.}"
        put "$src" "$dest"
        if [ "$DRY" = 0 ]; then
            kwrite --file kscreenlockerrc --group Greeter --key WallpaperPlugin org.kde.image
            kwrite --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image "file://$dest"
            kwrite --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key PreviewImage "file://$dest"
        fi
        say lockscreen "$(basename "$dest") on the lock screen"
    else
        skip lockscreen 'no Plasma session, skipped'
    fi
fi

# --- FireDragon -------------------------------------------------------------------
if step firedragon; then
    profiles=()
    for base in "$HOME/.firedragon" "$HOME/.config/firedragon" "$HOME/.var/app/org.garudalinux.firedragon/.firedragon"; do
        [ -d "$base" ] || continue
        while IFS= read -r prefs; do profiles+=("$(dirname "$prefs")"); done < <(find "$base" -maxdepth 3 -name prefs.js -not -path '*BackgroundTask*' 2>/dev/null)
    done
    if [ ${#profiles[@]} -eq 0 ]; then
        skip firedragon 'no FireDragon profile found (start it once first), skipped'
    else
        for p in "${profiles[@]}"; do
            put "$SHARED_DIR/firedragon/userChrome.css" "$p/chrome/userChrome.css"
            put "$SHARED_DIR/firedragon/userContent.css" "$p/chrome/userContent.css"
            if [ "$DRY" = 0 ]; then
                # The kp block is replaced on every run, so a changed firedragon-user.js arrives too.
                userjs="$p/user.js"
                if [ -f "$userjs" ] && ! grep -q 'kp-themes: begin' "$userjs"; then cp -p "$userjs" "$userjs.kp-backup-$STAMP"; fi
                rest=""
                [ -f "$userjs" ] && rest="$(sed '/\/\/ kp-themes: begin/,/\/\/ kp-themes: end/d' "$userjs")"
                { [ -n "$rest" ] && printf '%s\n\n' "$rest"; cat "$SHARED/firedragon-user.js"; } >"$userjs.kp-new"
                mv "$userjs.kp-new" "$userjs"
            fi
            say firedragon "$(basename "$p"): chrome/ written"
        done
        if pgrep -x firedragon >/dev/null 2>&1; then
            say firedragon 'FireDragon is running: close it and start it again to see the theme'
        fi
    fi
fi

if [ "$DRY" = 0 ]; then
    mkdir -p "$STATE"
    printf '%s\n' "$THEME" >"$STATE/current"
fi
printf '\n  \033[36mDone: KP %s.\033[0m\n\n' "$LABEL"
