# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Shade (light). Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 4F6369
set -g fish_color_command 25938A
set -g fish_color_keyword 1D6CA5
set -g fish_color_quote FCF6E3
set -g fish_color_redirection 248A81
set -g fish_color_end 248A81
set -g fish_color_error B7221F
set -g fish_color_param 4F6369
set -g fish_color_option 566B71
set -g fish_color_comment 566B71
set -g fish_color_operator 1D6CA5
set -g fish_color_escape 25938A
set -g fish_color_autosuggestion 566B71
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=D9D3BF
set -g fish_color_search_match --background=D9D3BF
set -g fish_pager_color_prefix 1D6CA5 --bold
set -g fish_pager_color_completion 4F6369
set -g fish_pager_color_description 566B71
set -g fish_pager_color_progress 25938A
