<#
.SYNOPSIS
    Puts one kp-themes theme on this Windows desktop.

.DESCRIPTION
    Hand-written; the files it copies are generated by gates/generate-windows.mjs.
    Every file it changes is copied to <file>.kp-backup-<timestamp> first.
    Current user only: no step needs administrator rights.

    Steps (each can be skipped):
      yasb        ~/.config/yasb/styles.css
      mica        Mica For Everyone's settings.json
      terminal    Windows Terminal: scheme, window theme, font, acrylic; Arch as default profile if installed
      firedragon  userChrome.css, userContent.css and user.js in every FireDragon profile
      vscode      all 22 VS Code themes as a local extension (pick one with Ctrl+K Ctrl+T)
      accent      accent colour, dark/light mode, transparency (accent.reg)
      wallpaper   wallpaper.png, if rendered (npm run render:wallpapers)
      wsl         starship.toml and fish colours inside the Arch WSL distro, if installed

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\windows\apply.ps1 -Theme synthwave
.EXAMPLE
    .\windows\apply.ps1 -Theme cyberpunk -Skip wallpaper,accent -DryRun
#>
[CmdletBinding()]
param(
    [string]$Theme = 'synthwave',
    [ValidateSet('yasb', 'mica', 'terminal', 'firedragon', 'vscode', 'accent', 'wallpaper', 'wsl')]
    [string[]]$Skip = @(),
    [string]$WslDistro = 'archlinux',
    [string]$TerminalFont = '',
    [switch]$RestartExplorer,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2

$Root = $PSScriptRoot
$ThemeDir = Join-Path $Root $Theme
$RepoRoot = Split-Path $Root -Parent
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

if (-not (Test-Path (Join-Path $ThemeDir 'terminal.json'))) {
    $known = (Get-Content (Join-Path $Root 'themes.json') -Raw | ConvertFrom-Json) | ForEach-Object { $_.name }
    throw "Unknown theme '$Theme'. Known: $($known -join ', '). Run 'npm run generate:windows' if the folder is missing."
}
$Meta = (Get-Content (Join-Path $Root 'themes.json') -Raw | ConvertFrom-Json) | Where-Object { $_.name -eq $Theme }

function Say([string]$step, [string]$text, [string]$colour = 'Gray') {
    Write-Host ('  {0,-11}' -f $step) -ForegroundColor Magenta -NoNewline
    Write-Host $text -ForegroundColor $colour
}

function Backup([string]$path) {
    if (Test-Path $path) {
        $target = "$path.kp-backup-$Stamp"
        if (-not $DryRun) { Copy-Item $path $target -Force }
        return $target
    }
    return $null
}

function Write-Text([string]$path, [string]$text) {
    if ($DryRun) { return }
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllText($path, $text, $Utf8NoBom)
}

function Copy-Themed([string]$source, [string]$dest) {
    Backup $dest | Out-Null
    if (-not $DryRun) {
        $dir = Split-Path $dest -Parent
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Copy-Item $source $dest -Force
    }
}

# Strict mode refuses .PSObject.Properties.Name on an object with no properties.
function Has($object, [string]$name) { return ($null -ne $object) -and ($null -ne $object.PSObject.Properties[$name]) }

function Set-Prop($object, [string]$name, $value) {
    if (Has $object $name) { $object.$name = $value }
    else { $object | Add-Member -NotePropertyName $name -NotePropertyValue $value }
}

# Windows Terminal writes JSON with comments and trailing commas; PowerShell 5 reads neither.
function Read-Jsonc([string]$path) {
    $text = Get-Content $path -Raw -Encoding UTF8
    $text = [regex]::Replace($text, '(?m)^\s*//.*$', '')
    $text = [regex]::Replace($text, ',(\s*[}\]])', '$1')
    return $text | ConvertFrom-Json
}

function Test-Font([string]$face) {
    foreach ($hive in 'HKLM:', 'HKCU:') {
        $key = "$hive\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"
        if (Test-Path $key) {
            $names = (Get-Item $key).GetValueNames()
            if ($names | Where-Object { $_ -like "$face*" }) { return $true }
        }
    }
    return $false
}

Write-Host ''
Write-Host "  kp-themes -> Windows: KP $($Meta.label) ($Theme)" -ForegroundColor Cyan
if ($DryRun) { Write-Host '  dry run: nothing is written' -ForegroundColor Yellow }
Write-Host ''

# --- YASB -------------------------------------------------------------------
if ($Skip -notcontains 'yasb') {
    $yasbHome = if ($env:YASB_CONFIG_HOME) { $env:YASB_CONFIG_HOME } else { Join-Path $HOME '.config\yasb' }
    if (Test-Path $yasbHome) {
        Copy-Themed (Join-Path $ThemeDir 'yasb-styles.css') (Join-Path $yasbHome 'styles.css')
        Say 'yasb' 'styles.css replaced; YASB reloads it by itself (watch_stylesheet).'
    } else { Say 'yasb' "no YASB config at $yasbHome, skipped" 'DarkGray' }
}

# --- Mica For Everyone --------------------------------------------------------
if ($Skip -notcontains 'mica') {
    $pkg = Get-ChildItem (Join-Path $env:LOCALAPPDATA 'Packages') -Directory -Filter 'MicaForEveryone*' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($pkg) {
        Copy-Themed (Join-Path $ThemeDir 'mica-settings.json') (Join-Path $pkg.FullName 'LocalState\settings.json')
        Say 'mica' 'settings.json replaced; restart Mica For Everyone to pick it up.'
    } else { Say 'mica' 'Mica For Everyone not found, skipped' 'DarkGray' }
}

# --- Windows Terminal ---------------------------------------------------------
if ($Skip -notcontains 'terminal') {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'),
        (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json'),
        (Join-Path $env:LOCALAPPDATA 'Microsoft\Windows Terminal\settings.json')
    ) | Where-Object { Test-Path $_ }

    $generated = Get-Content (Join-Path $ThemeDir 'terminal.json') -Raw | ConvertFrom-Json
    $face = $TerminalFont
    if (-not $face) {
        # The registry lists a font by its file name ("JetBrainsMono NFM Regular"), but
        # Windows Terminal looks it up by its family name ("JetBrainsMono Nerd Font Mono").
        # Each pair is: what to look for in the registry, what to write in settings.json.
        $fonts = @(
            @('JetBrainsMono Nerd Font Mono', 'JetBrainsMono Nerd Font Mono'),
            @('JetBrainsMono NFM', 'JetBrainsMono Nerd Font Mono'),
            @('JetBrainsMono Nerd Font', 'JetBrainsMono Nerd Font'),
            @('JetBrainsMono NF', 'JetBrainsMono Nerd Font'),
            @('JetBrains Mono', 'JetBrains Mono'),
            @('CaskaydiaCove', 'CaskaydiaCove Nerd Font Mono'),
            @('Cascadia Code', 'Cascadia Code')
        )
        foreach ($f in $fonts) {
            if (Test-Font $f[0]) { $face = $f[1]; break }
        }
    }

    if (-not $candidates) { Say 'terminal' 'Windows Terminal settings.json not found (open Terminal once first), skipped' 'DarkGray' }
    foreach ($path in $candidates) {
        $s = Read-Jsonc $path
        $name = $generated.scheme.name

        $schemes = @()
        if (Has $s 'schemes') { $schemes = @($s.schemes | Where-Object { $_.name -ne $name }) }
        Set-Prop $s 'schemes' (@($schemes) + $generated.scheme)

        $themes = @()
        if (Has $s 'themes') { $themes = @($s.themes | Where-Object { $_.name -ne $name }) }
        Set-Prop $s 'themes' (@($themes) + $generated.theme)
        Set-Prop $s 'theme' $name

        if (-not (Has $s 'profiles')) { Set-Prop $s 'profiles' ([pscustomobject]@{ defaults = [pscustomobject]@{}; list = @() }) }
        if ($s.profiles -is [array]) { Set-Prop $s 'profiles' ([pscustomobject]@{ defaults = [pscustomobject]@{}; list = $s.profiles }) }
        if (-not (Has $s.profiles 'defaults') -or $null -eq $s.profiles.defaults) { Set-Prop $s.profiles 'defaults' ([pscustomobject]@{}) }
        $d = $s.profiles.defaults
        Set-Prop $d 'colorScheme' $name
        Set-Prop $d 'opacity' 88
        Set-Prop $d 'useAcrylic' $true
        Set-Prop $d 'padding' '10, 8'
        Set-Prop $d 'cursorShape' 'bar'
        if ($face) { Set-Prop $d 'font' ([pscustomobject]@{ face = $face; size = 11 }) }

        # Arch in WSL as the default tab, starting in the Linux home.
        $arch = @($s.profiles.list) | Where-Object {
            (Has $_ 'source') -and ($_.source -like '*Wsl*') -and ($_.name -match $WslDistro)
        } | Select-Object -First 1
        if ($arch) {
            Set-Prop $s 'defaultProfile' $arch.guid
            Set-Prop $arch 'startingDirectory' '~'
            Set-Prop $arch 'hidden' $false
        }

        Backup $path | Out-Null
        Write-Text $path (($s | ConvertTo-Json -Depth 64) + "`n")
        $note = if ($face) { "font $face" } else { 'no Nerd Font found: winget install DEVCOM.JetBrainsMonoNerdFont' }
        $archNote = if ($arch) { "; default profile: $($arch.name)" } else { '' }
        Say 'terminal' "scheme and window theme '$name', $note$archNote"
    }
}

# --- FireDragon -----------------------------------------------------------------
if ($Skip -notcontains 'firedragon') {
    $bases = @((Join-Path $env:APPDATA 'FireDragon'), (Join-Path $env:APPDATA 'firedragon'), (Join-Path $env:APPDATA 'garuda\firedragon')) |
        Where-Object { Test-Path $_ } | Select-Object -Unique
    $profiles = @()
    foreach ($base in $bases) {
        $profiles += Get-ChildItem $base -Recurse -Depth 3 -Filter 'prefs.js' -ErrorAction SilentlyContinue | ForEach-Object { $_.Directory.FullName }
    }
    $profiles = $profiles | Select-Object -Unique
    if (-not $profiles) { Say 'firedragon' 'no FireDragon profile found (start it once first), skipped' 'DarkGray' }
    $userJs = Get-Content (Join-Path $Root 'firedragon-user.js') -Raw
    foreach ($p in $profiles) {
        Copy-Themed (Join-Path $ThemeDir 'firedragon\userChrome.css') (Join-Path $p 'chrome\userChrome.css')
        Copy-Themed (Join-Path $ThemeDir 'firedragon\userContent.css') (Join-Path $p 'chrome\userContent.css')
        $dest = Join-Path $p 'user.js'
        [string]$existing = if (Test-Path $dest) { Get-Content $dest -Raw } else { '' }
        if ($existing -notmatch 'kp-themes: begin') {
            Backup $dest | Out-Null
            Write-Text $dest ($existing.TrimEnd() + "`n`n" + $userJs)
        }
        Say 'firedragon' "$(Split-Path $p -Leaf): chrome/ written; restart FireDragon"
    }
    if (Get-Process -Name 'firedragon' -ErrorAction SilentlyContinue) { Say 'firedragon' 'FireDragon is running: the new look appears after a restart' 'Yellow' }
}

# --- VS Code ----------------------------------------------------------------------
if ($Skip -notcontains 'vscode') {
    $vsHome = Join-Path $HOME '.vscode\extensions'
    $vsSource = Join-Path $RepoRoot 'vscode'
    if ((Test-Path $vsHome) -and (Test-Path $vsSource)) {
        $ext = Join-Path $vsHome 'kp-soft.kp-themes-local-0.0.0'
        $contributes = @()
        foreach ($file in Get-ChildItem $vsSource -Filter 'kp-*-color-theme.json') {
            $json = Get-Content $file.FullName -Raw | ConvertFrom-Json
            $contributes += [pscustomobject]@{
                label   = $json.name
                uiTheme = $(if ($json.type -eq 'light') { 'vs' } else { 'vs-dark' })
                path    = "./themes/$($file.Name)"
            }
            if (-not $DryRun) {
                New-Item -ItemType Directory -Path (Join-Path $ext 'themes') -Force | Out-Null
                Copy-Item $file.FullName (Join-Path $ext "themes\$($file.Name)") -Force
            }
        }
        $manifest = [pscustomobject]@{
            name        = 'kp-themes-local'
            displayName = 'KP Themes (local)'
            publisher   = 'kp-soft'
            version     = '0.0.0'
            engines     = [pscustomobject]@{ vscode = '^1.70.0' }
            categories  = @('Themes')
            contributes = [pscustomobject]@{ themes = $contributes }
        }
        Write-Text (Join-Path $ext 'package.json') ($manifest | ConvertTo-Json -Depth 8)
        Say 'vscode' "$($contributes.Count) themes installed; pick 'KP $($Meta.label)' with Ctrl+K Ctrl+T"
    } else { Say 'vscode' 'VS Code not found, skipped' 'DarkGray' }
}

# --- Accent colour and dark mode ----------------------------------------------
if ($Skip -notcontains 'accent') {
    if (-not $DryRun) { & reg.exe import (Join-Path $ThemeDir 'accent.reg') 2>&1 | Out-Null }
    $restart = if ($RestartExplorer) { 'restarting Explorer' } else { 'sign out, or run with -RestartExplorer, to see it everywhere' }
    Say 'accent' "accent colour and $(if ($Meta.dark) { 'dark' } else { 'light' }) mode set; $restart"
    if ($RestartExplorer -and -not $DryRun) { Stop-Process -Name explorer -Force }
}

# --- Wallpaper ----------------------------------------------------------------------
if ($Skip -notcontains 'wallpaper') {
    $png = Join-Path $ThemeDir 'wallpaper.png'
    if (Test-Path $png) {
        $keep = Join-Path ([Environment]::GetFolderPath('MyPictures')) "kp-themes\$Theme.png"
        if (-not $DryRun) {
            New-Item -ItemType Directory -Path (Split-Path $keep -Parent) -Force | Out-Null
            Copy-Item $png $keep -Force
            Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;
public static class KpWallpaper {
    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    public static extern bool SystemParametersInfo(int action, int param, string value, int flags);
}
'@ -ErrorAction SilentlyContinue
            # SPI_SETDESKWALLPAPER, SPIF_UPDATEINIFILE | SPIF_SENDCHANGE
            [KpWallpaper]::SystemParametersInfo(20, 0, $keep, 3) | Out-Null
        }
        Say 'wallpaper' "set from $keep"
    } else { Say 'wallpaper' 'no wallpaper.png (run: npm run render:wallpapers), skipped' 'DarkGray' }
}

# --- The shell inside WSL -------------------------------------------------------------
if ($Skip -notcontains 'wsl') {
    $distros = @()
    if (Get-Command wsl.exe -ErrorAction SilentlyContinue) {
        # wsl.exe prints UTF-16; PowerShell reads it with a NUL after every letter.
        $distros = @(& wsl.exe --list --quiet 2>$null | ForEach-Object { ($_ -replace "`0", '').Trim() } | Where-Object { $_ })
    }
    if ($distros -contains $WslDistro) {
        $star = (Join-Path $ThemeDir 'starship.toml') -replace '\\', '/'
        $fish = (Join-Path $ThemeDir 'kp-colors.fish') -replace '\\', '/'
        # PowerShell 5 mangles quotes in native arguments, so the script travels as base64.
        $sh = "set -e`nmkdir -p ~/.config/fish/conf.d`ncp `"`$(wslpath -u '$star')`" ~/.config/starship.toml`ncp `"`$(wslpath -u '$fish')`" ~/.config/fish/conf.d/kp-colors.fish`n"
        $b64 = [Convert]::ToBase64String($Utf8NoBom.GetBytes($sh))
        if (-not $DryRun) { & wsl.exe -d $WslDistro -e sh -c "echo $b64 | base64 -d | sh" }
        Say 'wsl' "starship.toml and fish colours copied into $WslDistro"
    } else { Say 'wsl' "no WSL distro '$WslDistro' (see windows/wsl/README.md), skipped" 'DarkGray' }
}

Write-Host ''
Write-Host "  Done. Backups end in .kp-backup-$Stamp" -ForegroundColor Cyan
Write-Host ''
