<#
.SYNOPSIS
    Puts one kp-themes theme on this Windows desktop.

.DESCRIPTION
    Hand-written; the files it copies are generated by gates/generate-windows.mjs.
    Every file it changes is copied to <file>.kp-backup-<timestamp> first.
    Current user only: no step needs administrator rights.

    Steps (each can be skipped):
      yasb        ~/.config/yasb/styles.css
      mica        Mica For Everyone's settings.json
      terminal    Windows Terminal: scheme, window theme, font, acrylic; Arch as default profile if installed
      firedragon  userChrome.css, userContent.css and user.js in every FireDragon profile
      vscode      all 22 VS Code themes as a local extension (pick one with Ctrl+K Ctrl+T)
      accent      accent colour, dark/light mode, transparency (accent.reg)
      wallpaper   wallpaper.png, if rendered (npm run render:wallpapers)
      wsl         starship.toml and fish colours inside the Arch WSL distro, if installed

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\windows\apply.ps1 -Theme synthwave
.EXAMPLE
    .\windows\apply.ps1 -Theme cyberpunk -Skip wallpaper,accent -DryRun
#>
[CmdletBinding()]
param(
    # Leave it out to pick from a list; -List just prints the list.
    [Parameter(Position = 0)]
    [string]$Theme = '',
    [switch]$List,
    [ValidateSet('yasb', 'mica', 'terminal', 'firedragon', 'vscode', 'accent', 'wallpaper', 'lockscreen', 'windhawk', 'wsl')]
    [string[]]$Skip = @(),
    # Run only these steps; everything else is skipped. Used by the elevated
    # re-run of the lockscreen step.
    [ValidateSet('yasb', 'mica', 'terminal', 'firedragon', 'vscode', 'accent', 'wallpaper', 'lockscreen', 'windhawk', 'wsl')]
    [string[]]$Only = @(),
    # accent: one set of Windhawk styles that follows the Windows accent colour,
    # so switching themes needs no pasting. theme: this theme's exact colours.
    [ValidateSet('accent', 'theme')]
    [string]$WindhawkFlavour = 'accent',
    [string]$WslDistro = 'archlinux',
    [string]$TerminalFont = '',
    [switch]$RestartExplorer,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2

$Root = $PSScriptRoot
$ThemeDir = Join-Path $Root $Theme
$RepoRoot = Split-Path $Root -Parent
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$All = @(Get-Content (Join-Path $Root 'themes.json') -Raw | ConvertFrom-Json)

function Show-Themes {
    Write-Host ''
    Write-Host '  kp-themes' -ForegroundColor Cyan
    for ($i = 0; $i -lt $All.Count; $i++) {
        $t = $All[$i]
        $kind = if ($t.dark) { 'dark ' } else { 'light' }
        Write-Host ('  {0,2}. {1,-14} {2}  {3}' -f ($i + 1), $t.name, $kind, $t.label)
    }
    Write-Host ''
}

if ($List) { Show-Themes; return }

# No theme named: pick one from the list, so one command is the whole switch.
if (-not $Theme) {
    Show-Themes
    $answer = Read-Host '  Theme (number or name)'
    $Theme = if ($answer -match '^\d+$' -and [int]$answer -ge 1 -and [int]$answer -le $All.Count) { $All[[int]$answer - 1].name } else { $answer.Trim() }
}

$ThemeDir = Join-Path $Root $Theme
if (-not (Test-Path (Join-Path $ThemeDir 'terminal.json'))) {
    throw "Unknown theme '$Theme'. Known: $(($All | ForEach-Object { $_.name }) -join ', '). Run 'npm run generate:windows' if the folder is missing."
}
$Meta = $All | Where-Object { $_.name -eq $Theme }

function Say([string]$step, [string]$text, [string]$colour = 'Gray') {
    Write-Host ('  {0,-11}' -f $step) -ForegroundColor Magenta -NoNewline
    Write-Host $text -ForegroundColor $colour
}

function Backup([string]$path) {
    if (Test-Path $path) {
        $target = "$path.kp-backup-$Stamp"
        if (-not $DryRun) { Copy-Item $path $target -Force }
        return $target
    }
    return $null
}

function Write-Text([string]$path, [string]$text) {
    if ($DryRun) { return }
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllText($path, $text, $Utf8NoBom)
}

function Copy-Themed([string]$source, [string]$dest) {
    Backup $dest | Out-Null
    if (-not $DryRun) {
        $dir = Split-Path $dest -Parent
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Copy-Item $source $dest -Force
    }
}

# PowerShell 5 turns anything a native program writes to stderr into an error,
# and with ErrorActionPreference = Stop that ends the script, even when the
# program succeeded (reg.exe reports "completed successfully" on stderr).
# Run native programs through this and judge them by their exit code.
function Invoke-Native([string]$exe, [string[]]$arguments) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try { $output = & $exe @arguments 2>&1 | ForEach-Object { "$_" } }
    finally { $ErrorActionPreference = $old }
    return [pscustomobject]@{ Code = $LASTEXITCODE; Output = @($output) }
}

# Strict mode refuses .PSObject.Properties.Name on an object with no properties.
function Has($object, [string]$name) { return ($null -ne $object) -and ($null -ne $object.PSObject.Properties[$name]) }

function Set-Prop($object, [string]$name, $value) {
    if (Has $object $name) { $object.$name = $value }
    else { $object | Add-Member -NotePropertyName $name -NotePropertyValue $value }
}

# Windows Terminal writes JSON with comments and trailing commas; PowerShell 5 reads neither.
function Read-Jsonc([string]$path) {
    $text = Get-Content $path -Raw -Encoding UTF8
    $text = [regex]::Replace($text, '(?m)^\s*//.*$', '')
    $text = [regex]::Replace($text, ',(\s*[}\]])', '$1')
    return $text | ConvertFrom-Json
}

function Test-Font([string]$face) {
    foreach ($hive in 'HKLM:', 'HKCU:') {
        $key = "$hive\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"
        if (Test-Path $key) {
            $names = (Get-Item $key).GetValueNames()
            if ($names | Where-Object { $_ -like "$face*" }) { return $true }
        }
    }
    return $false
}

# One gate for every step: -Only wins, -Skip removes.
function Step([string]$name) {
    if ($Only.Count -gt 0) { return $Only -contains $name }
    return $Skip -notcontains $name
}

function Test-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    return (New-Object Security.Principal.WindowsPrincipal($id)).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

Write-Host ''
Write-Host "  kp-themes -> Windows: KP $($Meta.label) ($Theme)" -ForegroundColor Cyan
if ($DryRun) { Write-Host '  dry run: nothing is written' -ForegroundColor Yellow }
Write-Host ''

# --- YASB -------------------------------------------------------------------
if (Step 'yasb') {
    $yasbHome = if ($env:YASB_CONFIG_HOME) { $env:YASB_CONFIG_HOME } else { Join-Path $HOME '.config\yasb' }
    if (Test-Path $yasbHome) {
        Copy-Themed (Join-Path $ThemeDir 'yasb-styles.css') (Join-Path $yasbHome 'styles.css')
        Say 'yasb' 'styles.css replaced; YASB reloads it by itself (watch_stylesheet).'
    } else { Say 'yasb' "no YASB config at $yasbHome, skipped" 'DarkGray' }
}

# --- Mica For Everyone --------------------------------------------------------
if (Step 'mica') {
    $pkg = Get-ChildItem (Join-Path $env:LOCALAPPDATA 'Packages') -Directory -Filter 'MicaForEveryone*' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($pkg) {
        Copy-Themed (Join-Path $ThemeDir 'mica-settings.json') (Join-Path $pkg.FullName 'LocalState\settings.json')
        Say 'mica' 'settings.json replaced; restart Mica For Everyone to pick it up.'
    } else { Say 'mica' 'Mica For Everyone not found, skipped' 'DarkGray' }
}

# --- Windows Terminal ---------------------------------------------------------
if (Step 'terminal') {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'),
        (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json'),
        (Join-Path $env:LOCALAPPDATA 'Microsoft\Windows Terminal\settings.json')
    ) | Where-Object { Test-Path $_ }

    $generated = Get-Content (Join-Path $ThemeDir 'terminal.json') -Raw | ConvertFrom-Json
    $face = $TerminalFont
    if (-not $face) {
        # The registry lists a font by its file name ("JetBrainsMono NFM Regular"), but
        # Windows Terminal looks it up by its family name ("JetBrainsMono Nerd Font Mono").
        # Each pair is: what to look for in the registry, what to write in settings.json.
        $fonts = @(
            @('JetBrainsMono Nerd Font Mono', 'JetBrainsMono Nerd Font Mono'),
            @('JetBrainsMono NFM', 'JetBrainsMono Nerd Font Mono'),
            @('JetBrainsMono Nerd Font', 'JetBrainsMono Nerd Font'),
            @('JetBrainsMono NF', 'JetBrainsMono Nerd Font'),
            @('JetBrains Mono', 'JetBrains Mono'),
            @('CaskaydiaCove', 'CaskaydiaCove Nerd Font Mono'),
            @('Cascadia Code', 'Cascadia Code')
        )
        foreach ($f in $fonts) {
            if (Test-Font $f[0]) { $face = $f[1]; break }
        }
    }

    if (-not $candidates) { Say 'terminal' 'Windows Terminal settings.json not found (open Terminal once first), skipped' 'DarkGray' }
    foreach ($path in $candidates) {
        $s = Read-Jsonc $path
        $name = $generated.scheme.name

        $schemes = @()
        if (Has $s 'schemes') { $schemes = @($s.schemes | Where-Object { $_.name -ne $name }) }
        Set-Prop $s 'schemes' (@($schemes) + $generated.scheme)

        $themes = @()
        if (Has $s 'themes') { $themes = @($s.themes | Where-Object { $_.name -ne $name }) }
        Set-Prop $s 'themes' (@($themes) + $generated.theme)
        Set-Prop $s 'theme' $name

        if (-not (Has $s 'profiles')) { Set-Prop $s 'profiles' ([pscustomobject]@{ defaults = [pscustomobject]@{}; list = @() }) }
        if ($s.profiles -is [array]) { Set-Prop $s 'profiles' ([pscustomobject]@{ defaults = [pscustomobject]@{}; list = $s.profiles }) }
        if (-not (Has $s.profiles 'defaults') -or $null -eq $s.profiles.defaults) { Set-Prop $s.profiles 'defaults' ([pscustomobject]@{}) }
        $d = $s.profiles.defaults
        Set-Prop $d 'colorScheme' $name
        Set-Prop $d 'opacity' 88
        Set-Prop $d 'useAcrylic' $true
        Set-Prop $d 'padding' '10, 8'
        Set-Prop $d 'cursorShape' 'bar'
        if ($face) { Set-Prop $d 'font' ([pscustomobject]@{ face = $face; size = 11 }) }

        # Arch in WSL as the default tab, starting in the Linux home.
        $arch = @($s.profiles.list) | Where-Object {
            (Has $_ 'source') -and ($_.source -like '*Wsl*') -and ($_.name -match $WslDistro)
        } | Select-Object -First 1
        if ($arch) {
            Set-Prop $s 'defaultProfile' $arch.guid
            Set-Prop $arch 'startingDirectory' '~'
            Set-Prop $arch 'hidden' $false
        }

        Backup $path | Out-Null
        Write-Text $path (($s | ConvertTo-Json -Depth 64) + "`n")
        $note = if ($face) { "font $face" } else { 'no Nerd Font found: winget install DEVCOM.JetBrainsMonoNerdFont' }
        $archNote = if ($arch) { "; default profile: $($arch.name)" } else { '' }
        Say 'terminal' "scheme and window theme '$name', $note$archNote"
    }
}

# --- FireDragon -----------------------------------------------------------------
if (Step 'firedragon') {
    # Windows paths ignore case, so FireDragon and firedragon can be one folder: compare them resolved.
    $bases = @((Join-Path $env:APPDATA 'FireDragon'), (Join-Path $env:APPDATA 'garuda\firedragon')) |
        Where-Object { Test-Path $_ } | ForEach-Object { (Resolve-Path $_).Path } | Sort-Object -Unique
    $profiles = @()
    foreach ($base in $bases) {
        $profiles += Get-ChildItem $base -Recurse -Depth 3 -Filter 'prefs.js' -ErrorAction SilentlyContinue | ForEach-Object { $_.Directory.FullName }
    }
    # Sort-Object -Unique ignores case, Select-Object -Unique does not. The updater's
    # BackgroundTask profiles never show a window, so they are left alone.
    $profiles = @($profiles | Sort-Object -Unique | Where-Object { (Split-Path $_ -Leaf) -notmatch 'BackgroundTask' })
    if (-not $profiles) { Say 'firedragon' 'no FireDragon profile found (start it once first), skipped' 'DarkGray' }
    $userJs = Get-Content (Join-Path $Root 'firedragon-user.js') -Raw
    foreach ($p in $profiles) {
        Copy-Themed (Join-Path $ThemeDir 'firedragon\userChrome.css') (Join-Path $p 'chrome\userChrome.css')
        Copy-Themed (Join-Path $ThemeDir 'firedragon\userContent.css') (Join-Path $p 'chrome\userContent.css')
        $dest = Join-Path $p 'user.js'
        [string]$existing = if (Test-Path $dest) { Get-Content $dest -Raw } else { '' }
        if ($existing -notmatch 'kp-themes: begin') {
            Backup $dest | Out-Null
            Write-Text $dest ($existing.TrimEnd() + "`n`n" + $userJs)
        }
        Say 'firedragon' "$(Split-Path $p -Leaf): chrome/ written; restart FireDragon"
    }
    if (Get-Process -Name 'firedragon' -ErrorAction SilentlyContinue) { Say 'firedragon' 'FireDragon is running: the new look appears after a restart' 'Yellow' }
}

# --- VS Code ----------------------------------------------------------------------
if (Step 'vscode') {
    $vsHome = Join-Path $HOME '.vscode\extensions'
    $vsSource = Join-Path $RepoRoot 'vscode'
    if ((Test-Path $vsHome) -and (Test-Path $vsSource)) {
        $ext = Join-Path $vsHome 'kp-soft.kp-themes-local-0.0.0'
        $contributes = @()
        foreach ($file in Get-ChildItem $vsSource -Filter 'kp-*-color-theme.json') {
            $json = Get-Content $file.FullName -Raw | ConvertFrom-Json
            $contributes += [pscustomobject]@{
                label   = $json.name
                uiTheme = $(if ($json.type -eq 'light') { 'vs' } else { 'vs-dark' })
                path    = "./themes/$($file.Name)"
            }
            if (-not $DryRun) {
                New-Item -ItemType Directory -Path (Join-Path $ext 'themes') -Force | Out-Null
                Copy-Item $file.FullName (Join-Path $ext "themes\$($file.Name)") -Force
            }
        }
        $manifest = [pscustomobject]@{
            name        = 'kp-themes-local'
            displayName = 'KP Themes (local)'
            publisher   = 'kp-soft'
            version     = '0.0.0'
            engines     = [pscustomobject]@{ vscode = '^1.70.0' }
            categories  = @('Themes')
            contributes = [pscustomobject]@{ themes = $contributes }
        }
        Write-Text (Join-Path $ext 'package.json') ($manifest | ConvertTo-Json -Depth 8)
        Say 'vscode' "$($contributes.Count) themes installed; pick 'KP $($Meta.label)' with Ctrl+K Ctrl+T"
    } else { Say 'vscode' 'VS Code not found, skipped' 'DarkGray' }
}

# --- Accent colour and dark mode ----------------------------------------------
if (Step 'accent') {
    if (-not $DryRun) {
        $r = Invoke-Native 'reg.exe' @('import', (Join-Path $ThemeDir 'accent.reg'))
        if ($r.Code -ne 0) { throw "reg.exe import failed ($($r.Code)): $($r.Output -join ' ')" }
    }
    $restart = if ($RestartExplorer) { 'restarting Explorer' } else { 'sign out, or run with -RestartExplorer, to see it everywhere' }
    Say 'accent' "accent colour and $(if ($Meta.dark) { 'dark' } else { 'light' }) mode set; $restart"
    if ($RestartExplorer -and -not $DryRun) { Stop-Process -Name explorer -Force }
}

# --- Wallpaper ----------------------------------------------------------------------
if (Step 'wallpaper') {
    $png = Join-Path $ThemeDir 'wallpaper.png'
    if (Test-Path $png) {
        $keep = Join-Path ([Environment]::GetFolderPath('MyPictures')) "kp-themes\$Theme.png"
        if (-not $DryRun) {
            New-Item -ItemType Directory -Path (Split-Path $keep -Parent) -Force | Out-Null
            Copy-Item $png $keep -Force
            Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;
public static class KpWallpaper {
    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    public static extern bool SystemParametersInfo(int action, int param, string value, int flags);
}
'@ -ErrorAction SilentlyContinue
            # SPI_SETDESKWALLPAPER, SPIF_UPDATEINIFILE | SPIF_SENDCHANGE
            [KpWallpaper]::SystemParametersInfo(20, 0, $keep, 3) | Out-Null
        }
        Say 'wallpaper' "set from $keep"
    } else { Say 'wallpaper' 'no wallpaper.png (run: npm run render:wallpapers), skipped' 'DarkGray' }
}

# --- Lock screen and sign-in screen -------------------------------------------------
# PersonalizationCSP is the one place every edition of Windows 11 reads, and the
# sign-in screen shows the lock screen picture, so both are set here. It writes
# under HKLM, so this step needs administrator rights and asks for them once.
if (Step 'lockscreen') {
    $shared = 'C:\Users\Public\Pictures\kp-themes'
    $desktop = Join-Path $ThemeDir 'wallpaper.png'
    $lock = Join-Path $ThemeDir 'wallpaper-lock.png'
    if (-not (Test-Path $desktop) -or -not (Test-Path $lock)) {
        Say 'lockscreen' 'no rendered wallpapers (run: npm run render:wallpapers), skipped' 'DarkGray'
    } elseif ($DryRun) {
        Say 'lockscreen' "would copy both pictures to $shared and import personalization.reg"
    } elseif (Test-Admin) {
        New-Item -ItemType Directory -Path $shared -Force | Out-Null
        Copy-Item $desktop (Join-Path $shared "$Theme.png") -Force
        Copy-Item $lock (Join-Path $shared "$Theme-lock.png") -Force
        $r = Invoke-Native 'reg.exe' @('import', (Join-Path $ThemeDir 'personalization.reg'))
        if ($r.Code -ne 0) { throw "reg.exe import failed ($($r.Code)): $($r.Output -join ' ')" }
        Say 'lockscreen' 'lock and sign-in picture set; lock with Win+L to see it'
    } else {
        Say 'lockscreen' 'asking for administrator rights (the lock screen lives under HKLM)...' 'Yellow'
        $p = Start-Process -FilePath 'powershell.exe' -Verb RunAs -PassThru -Wait -ArgumentList @(
            '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$PSCommandPath`"", '-Theme', $Theme, '-Only', 'lockscreen')
        if ($p.ExitCode -eq 0) { Say 'lockscreen' 'lock and sign-in picture set' }
        else { Say 'lockscreen' "the elevated run ended with $($p.ExitCode); run this script as administrator to set it" 'Yellow' }
    }
}

# --- Windhawk: Explorer, taskbar, start menu, menus ----------------------------------
# Windhawk keeps mod settings in the registry in a shape it does not document,
# so this step writes the styles where they are easy to paste and says where.
if (Step 'windhawk') {
    $source = if ($WindhawkFlavour -eq 'accent') { Join-Path $Root 'windhawk-accent' } else { Join-Path $ThemeDir 'windhawk' }
    $dest = Join-Path $HOME '.config\kp-themes\windhawk'
    if (Test-Path $source) {
        foreach ($file in Get-ChildItem $source -Filter '*.yaml') { Copy-Themed $file.FullName (Join-Path $dest $file.Name) }
        $installed = $env:ProgramData -and (Test-Path (Join-Path $env:ProgramData 'Windhawk'))
        $note = if ($installed) { 'Windhawk is installed' } else { 'Windhawk is not installed yet (windhawk.net)' }
        $flavour = if ($WindhawkFlavour -eq 'accent') { 'accent-following styles: paste once, they follow every theme' } else { "this theme's exact colours: paste again after a theme switch" }
        Say 'windhawk' "$flavour"
        Say 'windhawk' "$note; styles are in $dest"
        Say 'windhawk' 'per mod: Settings tab > Textual mode > paste the matching .yaml > Save'
    } else { Say 'windhawk' 'no styles found, skipped' 'DarkGray' }
}

# --- The shell inside WSL -------------------------------------------------------------
if (Step 'wsl') {
    $distros = @()
    if (Get-Command wsl.exe -ErrorAction SilentlyContinue) {
        # wsl.exe prints UTF-16; PowerShell reads it with a NUL after every letter.
        $distros = @((Invoke-Native 'wsl.exe' @('--list', '--quiet')).Output | ForEach-Object { ($_ -replace "`0", '').Trim() } | Where-Object { $_ })
    }
    if ($distros -contains $WslDistro) {
        $star = (Join-Path $ThemeDir 'starship.toml') -replace '\\', '/'
        $fish = (Join-Path $ThemeDir 'kp-colors.fish') -replace '\\', '/'
        # PowerShell 5 mangles quotes in native arguments, so the script travels as base64.
        $sh = "set -e`nmkdir -p ~/.config/fish/conf.d`ncp `"`$(wslpath -u '$star')`" ~/.config/starship.toml`ncp `"`$(wslpath -u '$fish')`" ~/.config/fish/conf.d/kp-colors.fish`n"
        $b64 = [Convert]::ToBase64String($Utf8NoBom.GetBytes($sh))
        if (-not $DryRun) {
            $r = Invoke-Native 'wsl.exe' @('-d', $WslDistro, '-e', 'sh', '-c', "echo $b64 | base64 -d | sh")
            if ($r.Code -ne 0) { throw "copying into $WslDistro failed ($($r.Code)): $($r.Output -join ' ')" }
        }
        Say 'wsl' "starship.toml and fish colours copied into $WslDistro"
    } else { Say 'wsl' "no WSL distro '$WslDistro' (see windows/wsl/README.md), skipped" 'DarkGray' }
}

Write-Host ''
Write-Host "  Done. Backups end in .kp-backup-$Stamp" -ForegroundColor Cyan
Write-Host ''
