// Generated by build.mjs from the pen routes; do not edit by hand.
/** The six drawings (viewBox 480 x 200). `__U__` is replaced by a unique number: the page holds each drawing twice. */
export const ART = {
    dimension: `<rect class="ba2-part-line" x="150" y="50" width="180" height="56"/>
        <circle class="ba2-part-line" cx="240" cy="78" r="10"/>
        <path class="ba2-part-line" d="M226 78H254M240 64V92"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-dm-pen-s1" pathLength="1" stroke-linejoin="round" d="M150 112L150 148"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-round ba2-dm-pen-s2" pathLength="1" stroke-linejoin="round" d="M145 147L155 137"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-dm-pen-s3" pathLength="1" stroke-linejoin="round" d="M150 142L330 142"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-round ba2-dm-pen-s4" pathLength="1" stroke-linejoin="round" d="M325 147L335 137"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-dm-pen-s5" pathLength="1" stroke-linejoin="round" d="M330 112L330 148"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-note ba2-bold ba2-round ba2-dm-pen-s6" pathLength="1" stroke-linejoin="round" d="M217 118L219 115L222.5 114L226 115L228 118L227 122L217 131L228 131"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-note ba2-bold ba2-round ba2-dm-pen-s7" pathLength="1" stroke-linejoin="round" d="M242 131L242 114L234 126L245 126"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-note ba2-bold ba2-round ba2-dm-pen-s8" pathLength="1" stroke-linejoin="round" d="M254 114L259 114L262 118L262 127L259 131L254 131L251 127L251 118L254 114"/>
        <path class="ba2-p ba2-ln ba2-steel ba2-dm-pen-rail" d="M40 -2.5H440M40 2.5H440"/>
        <g class="ba2-p ba2-dm-pen-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-dm-pen-nib" r="3.5"/>
        </g>`,
    plotter: `<defs><pattern id="ba2-g-__U__" width="10" height="10" patternUnits="userSpaceOnUse"><path class="ba2-mm" d="M10 0H0V10"/></pattern></defs><rect x="70" y="40" width="350" height="140" fill="url(#ba2-g-__U__)"/>
        <path class="ba2-p ba2-ln ba2-steel ba2-pl-rail" d="M40 -2.5H440M40 2.5H440"/>
        <path class="ba2-p ba2-ln ba2-bold ba2-pen ba2-draw ba2-pl-line" pathLength="1" stroke-linejoin="round" d="M80 138L140 112L190 126L250 84L310 98L400 54"/>
        <path class="ba2-p ba2-ln ba2-pen ba2-draw ba2-pl-mark" pathLength="1" d="M405 54A5 5 0 1 1 395 54A5 5 0 1 1 405 54"/>
        <path class="ba2-p ba2-ln ba2-note ba2-draw ba2-pl-leader" pathLength="1" d="M400 54L432 30"/>
        <text class="ba2-p ba2-note-text ba2-pl-label" x="438" y="34">412 KN</text>
        <g class="ba2-p ba2-pl-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-pl-nib" r="3.5"/>
        </g>`,
    straightedge: `<path class="ba2-ln ba2-steel" d="M104 40V160M96 40H104M99 50H104M96 60H104M99 70H104M96 80H104M99 90H104M96 100H104M99 110H104M96 120H104M99 130H104M96 140H104M99 150H104M96 160H104"/>
        <path class="ba2-ln ba2-steel" d="M156 54V46H164M324 54V46H316M324 146V154H316M156 146V154H164"/>
        <text class="ba2-note-text" x="30" y="80">DIST</text>
        <g class="ba2-sx-win"><g class="ba2-p ba2-sx-odo"><text class="ba2-note-text" x="30" y="101">020</text><text class="ba2-note-text" x="30" y="117">040</text><text class="ba2-note-text" x="30" y="133">060</text><text class="ba2-note-text" x="30" y="149">080</text><text class="ba2-note-text" x="30" y="165">100</text></g></g>
        <text x="60" y="101">MM</text>
        <g class="ba2-p ba2-sx-blade">
            <rect class="ba2-fill-ground" x="108" y="-24" width="16" height="32"/>
            <rect class="ba2-ln ba2-steel" x="108" y="-24" width="16" height="32"/>
            <rect class="ba2-fill-ground" x="124" y="-10" width="300" height="10"/>
            <path class="ba2-ln ba2-steel" d="M124 -10H424V0H124M134 -10v3M134 -10v5M144 -10v3M154 -10v3M164 -10v3M174 -10v3M184 -10v5M194 -10v3M204 -10v3M214 -10v3M224 -10v3M234 -10v5M244 -10v3M254 -10v3M264 -10v3M274 -10v3M284 -10v5M294 -10v3M304 -10v3M314 -10v3M324 -10v3M334 -10v5M344 -10v3M354 -10v3M364 -10v3M374 -10v3M384 -10v5M394 -10v3M404 -10v3M414 -10v3"/>
        </g>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-sx-pen-s1" pathLength="1" stroke-linejoin="round" d="M170 62L310 62"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-sx-pen-s2" pathLength="1" stroke-linejoin="round" d="M310 82L170 82"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-sx-pen-s3" pathLength="1" stroke-linejoin="round" d="M170 102L310 102"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-sx-pen-s4" pathLength="1" stroke-linejoin="round" d="M310 122L170 122"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-sx-pen-s5" pathLength="1" stroke-linejoin="round" d="M170 142L310 142"/>
        <g class="ba2-p ba2-sx-pen-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-sx-pen-nib" r="3.5"/>
        </g>`,
    dividers: `<path class="ba2-ln ba2-steel" d="M48 150H432"/>
        <text class="ba2-note-text" x="60" y="52">STEPS</text>
        <g class="ba2-dv-win"><g class="ba2-p ba2-dv-odo"><text class="ba2-note-text" x="106" y="52">0</text><text class="ba2-note-text" x="106" y="68">1</text><text class="ba2-note-text" x="106" y="84">2</text><text class="ba2-note-text" x="106" y="100">3</text><text class="ba2-note-text" x="106" y="116">4</text><text class="ba2-note-text" x="106" y="132">5</text><text class="ba2-note-text" x="106" y="148">6</text><text class="ba2-note-text" x="106" y="164">7</text></g></g>
        <text x="122" y="52">× 60 MM</text>
        <g class="ba2-p ba2-dv-inst">
            <g class="ba2-p ba2-dv-legA"><path class="ba2-ln ba2-bold ba2-steel" d="M0 0V72"/><path class="ba2-ln ba2-bold ba2-pen" d="M0 62V72"/></g>
            <g class="ba2-p ba2-dv-legB"><path class="ba2-ln ba2-bold ba2-steel" d="M0 0V72"/><path class="ba2-ln ba2-bold ba2-pen" d="M0 62V72"/></g>
            <g class="ba2-p ba2-dv-apex">
                <rect class="ba2-fill-ground" x="-3" y="-24" width="6" height="18"/>
                <rect class="ba2-ln ba2-steel" x="-3" y="-24" width="6" height="18"/>
                <circle class="ba2-fill-ground" r="4"/>
                <circle class="ba2-ln ba2-steel" r="4"/>
            </g>
        </g>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s1" pathLength="1" stroke-linejoin="round" d="M60 142L60 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s2" pathLength="1" stroke-linejoin="round" d="M120 142L120 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s3" pathLength="1" stroke-linejoin="round" d="M180 142L180 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s4" pathLength="1" stroke-linejoin="round" d="M240 142L240 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s5" pathLength="1" stroke-linejoin="round" d="M300 142L300 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s6" pathLength="1" stroke-linejoin="round" d="M360 142L360 158"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-bold ba2-dv-pen-s7" pathLength="1" stroke-linejoin="round" d="M420 142L420 158"/>
        <path class="ba2-p ba2-ln ba2-steel ba2-dv-pen-rail" d="M20 -2.5H460M20 2.5H460"/>
        <g class="ba2-p ba2-dv-pen-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-dv-pen-nib" r="3.5"/>
        </g>`,
    hatching: `<circle class="ba2-ln ba2-steel" cx="240" cy="92" r="54"/>
        <path class="ba2-ln ba2-steel" d="M172 92H192M288 92H308M240 24V44M240 140V160" style="stroke: hsl(from var(--ba2-line) h s l / 0.5)"/>
        <text class="ba2-p ba2-note-text ba2-ht-label" x="240" y="174" text-anchor="middle">SECTION A–A</text>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s1" pathLength="1" stroke-linejoin="round" d="M188.57 75.55L223.55 40.57"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s2" pathLength="1" stroke-linejoin="round" d="M243 38.08L186.08 95"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s3" pathLength="1" stroke-linejoin="round" d="M188.82 109.23L257.23 40.82"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s4" pathLength="1" stroke-linejoin="round" d="M268.74 46.29L194.29 120.74"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s5" pathLength="1" stroke-linejoin="round" d="M201.82 130.18L278.18 53.82"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s6" pathLength="1" stroke-linejoin="round" d="M285.71 63.26L211.26 137.71"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s7" pathLength="1" stroke-linejoin="round" d="M222.77 143.18L291.18 74.77"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s8" pathLength="1" stroke-linejoin="round" d="M293.92 89L237 145.92"/>
        <path class="ba2-p ba2-ln ba2-draw ba2-pen ba2-ht-pen-s9" pathLength="1" stroke-linejoin="round" d="M256.45 143.43L291.43 108.45"/>
        <path class="ba2-p ba2-ln ba2-steel ba2-ht-pen-rail" d="M40 -2.5H440M40 2.5H440"/>
        <g class="ba2-p ba2-ht-pen-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-ht-pen-nib" r="3.5"/>
        </g>`,
    tracing: `<path class="ba2-mm" style="stroke-width: 0.8" d="M126 154V34M156 154V34M186 154V34M216 154V34M246 154V34M276 154V34M306 154V34M336 154V34M366 154V34M396 154V34M96 134H396M96 114H396M96 94H396M96 74H396M96 54H396M96 34H396"/>
        <path class="ba2-ln ba2-steel" d="M96 34V154H396M96 154v7M126 154v4M156 154v4M186 154v4M216 154v4M246 154v7M276 154v4M306 154v4M336 154v4M366 154v4M396 154v7M96 154h-7M96 134h-4M96 114h-4M96 94h-7M96 74h-4M96 54h-4M96 34h-7"/>
        <g style="font-size: 10px"><text x="96" y="174" text-anchor="middle">0</text><text x="246" y="174" text-anchor="middle">5</text><text x="396" y="174" text-anchor="middle">10</text>
        <text x="84" y="157" text-anchor="end">0</text><text x="84" y="97" text-anchor="end">75</text><text x="84" y="37" text-anchor="end">150</text></g>
        <path class="ba2-p ba2-ln ba2-bold ba2-pen ba2-draw ba2-tr-ink" pathLength="1" stroke-linejoin="round" d="M96 154L101.36 145.76L106.71 135.82L112.07 124.88L117.43 113.57L122.79 102.42L128.14 91.9L133.5 82.33L138.86 73.98L144.21 66.99L149.57 61.44L154.93 57.33L160.29 54.61L165.64 53.15L171 52.81L176.36 53.44L181.71 54.83L187.07 56.81L192.43 59.19L197.79 61.82L203.14 64.53L208.5 67.2L213.86 69.72L219.21 72.02L224.57 74.02L229.93 75.69L235.29 77.02L240.64 78L246 78.65L251.36 79L256.71 79.08L262.07 78.93L267.43 78.59L272.79 78.12L278.14 77.55L283.5 76.92L288.86 76.27L294.21 75.63L299.57 75.02L304.93 74.47L310.29 73.99L315.64 73.59L321 73.27L326.36 73.04L331.71 72.88L337.07 72.8L342.43 72.78L347.79 72.82L353.14 72.9L358.5 73.01L363.86 73.15L369.21 73.3L374.57 73.46L379.93 73.61L385.29 73.76L390.64 73.89L396 74"/>
        <path class="ba2-p ba2-ln ba2-note ba2-nse ba2-tr-wv" d="M0 0V-1"/>
        <path class="ba2-p ba2-ln ba2-note ba2-nse ba2-tr-wh" d="M0 0H1"/>
        <path class="ba2-p ba2-fill-note ba2-tr-px" d="M0 156L-4 164H4Z"/>
        <path class="ba2-p ba2-fill-note ba2-tr-py" d="M94 0L86 -4V4Z"/>
        <text class="ba2-p ba2-note-text ba2-tr-label" x="404" y="66">100</text>
        <path class="ba2-p ba2-ln ba2-steel ba2-tr-pen-rail" d="M40 -2.5H440M40 2.5H440"/>
        <g class="ba2-p ba2-tr-pen-car">
            <rect class="ba2-fill-ground" x="-8" y="-8" width="16" height="16"/>
            <rect class="ba2-ln ba2-steel" x="-8" y="-8" width="16" height="16"/>
            <path class="ba2-ln ba2-steel" d="M-13 0H-3M3 0H13M0 -13V-3M0 3V13"/>
            <circle class="ba2-p ba2-nib ba2-tr-pen-nib" r="3.5"/>
        </g>`,
};
