# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Titanium. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal EDF0F2
set -g fish_color_command 373C43
set -g fish_color_keyword D9DDE3
set -g fish_color_quote F3B549
set -g fish_color_redirection F36B49
set -g fish_color_end F36B49
set -g fish_color_error F36B49
set -g fish_color_param EDF0F2
set -g fish_color_option 89909A
set -g fish_color_comment 89909A
set -g fish_color_operator D9DDE3
set -g fish_color_escape 373C43
set -g fish_color_autosuggestion 89909A
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=2B2F36
set -g fish_color_search_match --background=2B2F36
set -g fish_pager_color_prefix D9DDE3 --bold
set -g fish_pager_color_completion EDF0F2
set -g fish_pager_color_description 89909A
set -g fish_pager_color_progress 373C43
