# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Lapis. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal F2E9D4
set -g fish_color_command E24536
set -g fish_color_keyword D5A52A
set -g fish_color_quote F2E9D4
set -g fish_color_redirection E8D7B0
set -g fish_color_end E8D7B0
set -g fish_color_error F7796E
set -g fish_color_param F2E9D4
set -g fish_color_option A9AFD1
set -g fish_color_comment A9AFD1
set -g fish_color_operator D5A52A
set -g fish_color_escape E24536
set -g fish_color_autosuggestion A9AFD1
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=3B4E97
set -g fish_color_search_match --background=3B4E97
set -g fish_pager_color_prefix D5A52A --bold
set -g fish_pager_color_completion F2E9D4
set -g fish_pager_color_description A9AFD1
set -g fish_pager_color_progress E24536
