# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Grotesk. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 121212
set -g fish_color_command 121212
set -g fish_color_keyword E00618
set -g fish_color_quote 121212
set -g fish_color_redirection 1F4EAD
set -g fish_color_end 1F4EAD
set -g fish_color_error C70515
set -g fish_color_param 121212
set -g fish_color_option 666666
set -g fish_color_comment 666666
set -g fish_color_operator E00618
set -g fish_color_escape 121212
set -g fish_color_autosuggestion 666666
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=DBDBDB
set -g fish_color_search_match --background=DBDBDB
set -g fish_pager_color_prefix E00618 --bold
set -g fish_pager_color_completion 121212
set -g fish_pager_color_description 666666
set -g fish_pager_color_progress 121212
