# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Shade (dark). Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 9CA9AB
set -g fish_color_command 2AA298
set -g fish_color_keyword 50A5E2
set -g fish_color_quote 251D04
set -g fish_color_redirection 2AA298
set -g fish_color_end 2AA298
set -g fish_color_error F2615F
set -g fish_color_param 9CA9AB
set -g fish_color_option 96A4A6
set -g fish_color_comment 96A4A6
set -g fish_color_operator 50A5E2
set -g fish_color_escape 2AA298
set -g fish_color_autosuggestion 96A4A6
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=244F5B
set -g fish_color_search_match --background=244F5B
set -g fish_pager_color_prefix 50A5E2 --bold
set -g fish_pager_color_completion 9CA9AB
set -g fish_pager_color_description 96A4A6
set -g fish_pager_color_progress 2AA298
