# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Retro. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 1A1A1A
set -g fish_color_command 006666
set -g fish_color_keyword 000080
set -g fish_color_quote 1A1A1A
set -g fish_color_redirection 800080
set -g fish_color_end 800080
set -g fish_color_error 800000
set -g fish_color_param 1A1A1A
set -g fish_color_option 404040
set -g fish_color_comment 404040
set -g fish_color_operator 000080
set -g fish_color_escape 006666
set -g fish_color_autosuggestion 404040
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=C9C9C9
set -g fish_color_search_match --background=C9C9C9
set -g fish_pager_color_prefix 000080 --bold
set -g fish_pager_color_completion 1A1A1A
set -g fish_pager_color_description 404040
set -g fish_pager_color_progress 006666
