// The razor tear, generated at build [TH121, T18, AR41].
//
// The approved demo drew the tear in the browser with a seeded generator.
// The theme does not: a dashboard should get the tear without running a
// script, the shape must be identical in every release, and S44 admits
// no artwork. So this generator runs at build, writes the path as a data
// URI into css/cyberpunk-register.css between two marker comments, and
// `--check` fails when what is committed differs from what the
// parameters produce — the same contract css/themes.css has with
// gates/generate-themes.mjs.
//
// The whole parameter set is the contract (gates/tear.json), not only the
// seed: the critic measured that the run, cut and notch numbers and the
// viewBox are the shape, and the seed alone is not. Two tears, because
// the demo Kenny approved used two — `--fx-tear` (seed 7) and
// `--fx-tear-alt` (seed 23) — and the cyan hairline is a third URI a
// register draws as its own layer, because a mask cannot carry a second
// colour.
//
// The path is the region BELOW the ridge (closing along the bottom
// edge), so a container paints the section above and the path is masked
// to the section below. The first build of the demo closed the path along
// the top and put each colour inside the other; Kenny saw it before any
// test did, and gates/check-tear.mjs measures pixels for exactly that.
//
// Usage:
//   node gates/generate-tear.mjs           write the block
//   node gates/generate-tear.mjs --check   exit 1 if the block would change

import { readFileSync, writeFileSync } from 'node:fs';
import process from 'node:process';

const REGISTER = new URL('../css/cyberpunk-register.css', import.meta.url);
export const PARAMS = JSON.parse(readFileSync(new URL('tear.json', import.meta.url), 'utf8'));

const BEGIN = '    /* generated by gates/generate-tear.mjs from gates/tear.json — do not edit */';
const END = '    /* end of the generated tear */';

/**
 * A seeded linear congruential generator, exact in double precision.
 *
 * @param {number} seed
 * @returns {() => number} uniform in [0, 1)
 */
export function lcg(seed) {
    const { a, c, m } = PARAMS.lcg;
    let s = seed >>> 0;
    return () => {
        s = (s * a + c) % m;
        return s / m;
    };
}

/**
 * The ridge as a list of points along the width, from the parameters.
 *
 * @param {number} seed
 * @returns {{ x: number, y: number }[]}
 */
export function ridge(seed) {
    const p = PARAMS;
    const rand = lcg(seed);
    const W = p.viewBox.width;
    /** @type {{ x: number, y: number }[]} */
    const points = [];
    let x = 0;
    let y = p.ridge.yMin + (p.ridge.yMax - p.ridge.yMin) / 2;
    points.push({ x: 0, y });
    while (x < W) {
        const run = p.run.min + Math.floor(rand() * (p.run.max - p.run.min));
        x = Math.min(W, x + run);
        const roll = rand();
        if (roll < p.cuts.deep) {
            const w = p.widths.deep[0] + Math.floor(rand() * (p.widths.deep[1] - p.widths.deep[0]));
            points.push({ x: Math.min(W, x), y });
            points.push({ x: Math.min(W, x + w / 2), y: p.ridge.depth + p.ridge.yMin });
            x = Math.min(W, x + w);
            points.push({ x, y });
        } else if (roll < p.cuts.deep + p.cuts.notch) {
            const w = p.widths.notch[0] + Math.floor(rand() * (p.widths.notch[1] - p.widths.notch[0]));
            points.push({ x: Math.min(W, x), y });
            points.push({ x: Math.min(W, x), y: y + p.notchDrop });
            x = Math.min(W, x + w);
            points.push({ x, y: y + p.notchDrop });
            points.push({ x, y });
        } else {
            const w = p.widths.step[0] + Math.floor(rand() * (p.widths.step[1] - p.widths.step[0]));
            const ny = p.ridge.yMin + Math.floor(rand() * (p.ridge.yMax - p.ridge.yMin));
            points.push({ x: Math.min(W, x), y });
            x = Math.min(W, x + w);
            points.push({ x, y: ny });
            y = ny;
        }
    }
    if (points[points.length - 1].x < W) points.push({ x: W, y });
    return points;
}

/**
 * The path below the ridge, closed along the bottom edge.
 *
 * @param {number} seed
 * @returns {string}
 */
export function tearPath(seed) {
    const H = PARAMS.viewBox.height;
    const W = PARAMS.viewBox.width;
    const pts = ridge(seed);
    const d = [`M0 ${H}`, ...pts.map((pt) => `L${pt.x} ${pt.y}`), `L${W} ${H}`, 'Z'];
    return d.join(' ');
}

/**
 * The ridge alone as an open polyline, for the hairline layer.
 *
 * @param {number} seed
 * @returns {string}
 */
export function linePath(seed) {
    const pts = ridge(seed);
    return pts.map((pt, i) => `${i === 0 ? 'M' : 'L'}${pt.x} ${pt.y}`).join(' ');
}

/** @param {string} svg @returns {string} */
const dataUri = (svg) =>
    `url("data:image/svg+xml,${encodeURIComponent(svg).replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/')}")`;

/** The generated block, as it must appear in the register. */
export function block() {
    const { width, height } = PARAMS.viewBox;
    const box = `viewBox='0 0 ${width} ${height}' preserveAspectRatio='none'`;
    const mask = (/** @type {number} */ seed) =>
        dataUri(`<svg xmlns='http://www.w3.org/2000/svg' ${box}><path fill='black' d='${tearPath(seed)}'/></svg>`);
    const line = (/** @type {number} */ seed) =>
        dataUri(
            `<svg xmlns='http://www.w3.org/2000/svg' ${box}><path fill='none' stroke='white' stroke-width='1' stroke-opacity='${PARAMS.line.opacity}' transform='translate(0 ${PARAMS.line.offset})' d='${linePath(seed)}'/></svg>`,
        );
    return [
        BEGIN,
        `    [data-theme='cyberpunk'] {`,
        `        --fx-tear: ${mask(PARAMS.seeds.tear)};`,
        `        --fx-tear-alt: ${mask(PARAMS.seeds.alt)};`,
        `        --fx-tear-line: ${line(PARAMS.seeds.tear)};`,
        `        --fx-tear-line-alt: ${line(PARAMS.seeds.alt)};`,
        `    }`,
        END,
    ].join('\n');
}

/**
 * The register with the generated block in place: replaced when the
 * markers exist, appended before the layer's closing brace when not.
 *
 * @param {string} source
 * @returns {string}
 */
export function withBlock(source) {
    const start = source.indexOf(BEGIN);
    const end = source.indexOf(END);
    if (start >= 0 && end > start) return source.slice(0, start) + block() + source.slice(end + END.length);
    const close = source.lastIndexOf('}');
    return `${source.slice(0, close).trimEnd()}\n\n${block()}\n${source.slice(close)}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
    const current = readFileSync(REGISTER, 'utf8');
    const next = withBlock(current);
    if (process.argv.includes('--check')) {
        if (current !== next) {
            console.error(
                'css/cyberpunk-register.css: the generated tear does not match gates/tear.json. Run `npm run generate:tear` and commit the result.',
            );
            process.exit(1);
        }
        console.log('Tear: the register carries the tear gates/tear.json produces (two seeds, two hairlines).');
        process.exit(0);
    }
    writeFileSync(REGISTER, next);
    console.log('wrote the tear block into css/cyberpunk-register.css.');
}
