# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Art Deco. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal F3E8CE
set -g fish_color_command 21836A
set -g fish_color_keyword D4A735
set -g fish_color_quote FBF0DA
set -g fish_color_redirection E64C59
set -g fish_color_end E64C59
set -g fish_color_error EA3E4C
set -g fish_color_param F3E8CE
set -g fish_color_option CDC0A2
set -g fish_color_comment CDC0A2
set -g fish_color_operator D4A735
set -g fish_color_escape 21836A
set -g fish_color_autosuggestion CDC0A2
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=354046
set -g fish_color_search_match --background=354046
set -g fish_pager_color_prefix D4A735 --bold
set -g fish_pager_color_completion F3E8CE
set -g fish_pager_color_description CDC0A2
set -g fish_pager_color_progress 21836A
