# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Forest. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 1A2E27
set -g fish_color_command EFD7C8
set -g fish_color_keyword 235744
set -g fish_color_quote 864F18
set -g fish_color_redirection 63833F
set -g fish_color_end 63833F
set -g fish_color_error A53827
set -g fish_color_param 1A2E27
set -g fish_color_option 4C615A
set -g fish_color_comment 4C615A
set -g fish_color_operator 235744
set -g fish_color_escape EFD7C8
set -g fish_color_autosuggestion 4C615A
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=D1CDC1
set -g fish_color_search_match --background=D1CDC1
set -g fish_pager_color_prefix 235744 --bold
set -g fish_pager_color_completion 1A2E27
set -g fish_pager_color_description 4C615A
set -g fish_pager_color_progress EFD7C8
