# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Phantom. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal FAFAFA
set -g fish_color_command DBDBDB
set -g fish_color_keyword FF293B
set -g fish_color_quote FFF5D6
set -g fish_color_redirection CF1726
set -g fish_color_end CF1726
set -g fish_color_error FF293B
set -g fish_color_param FAFAFA
set -g fish_color_option ADADAD
set -g fish_color_comment ADADAD
set -g fish_color_operator FF293B
set -g fish_color_escape DBDBDB
set -g fish_color_autosuggestion ADADAD
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=383838
set -g fish_color_search_match --background=383838
set -g fish_pager_color_prefix FF293B --bold
set -g fish_pager_color_completion FAFAFA
set -g fish_pager_color_description ADADAD
set -g fish_pager_color_progress DBDBDB
