# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP High contrast. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 000000
set -g fish_color_command FFCC00
set -g fish_color_keyword 003399
set -g fish_color_quote FFFFFF
set -g fish_color_redirection 8F4700
set -g fish_color_end 8F4700
set -g fish_color_error A30000
set -g fish_color_param 000000
set -g fish_color_option 333333
set -g fish_color_comment 333333
set -g fish_color_operator 003399
set -g fish_color_escape FFCC00
set -g fish_color_autosuggestion 333333
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=EBEBEB
set -g fish_color_search_match --background=EBEBEB
set -g fish_pager_color_prefix 003399 --bold
set -g fish_pager_color_completion 000000
set -g fish_pager_color_description 333333
set -g fish_pager_color_progress FFCC00
