# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Synthwave. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal E0D1FF
set -g fish_color_command 34F9F5
set -g fish_color_keyword FF4782
set -g fish_color_quote FDDD5D
set -g fish_color_redirection 9B70FF
set -g fish_color_end 9B70FF
set -g fish_color_error FE4350
set -g fish_color_param E0D1FF
set -g fish_color_option 9E90D0
set -g fish_color_comment 9E90D0
set -g fish_color_operator FF4782
set -g fish_color_escape 34F9F5
set -g fish_color_autosuggestion 9E90D0
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=343144
set -g fish_color_search_match --background=343144
set -g fish_pager_color_prefix FF4782 --bold
set -g fish_pager_color_completion E0D1FF
set -g fish_pager_color_description 9E90D0
set -g fish_pager_color_progress 34F9F5
