# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Formal. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 171E2B
set -g fish_color_command EDE0D4
set -g fish_color_keyword 223659
set -g fish_color_quote 835A21
set -g fish_color_redirection B25334
set -g fish_color_end B25334
set -g fish_color_error A32929
set -g fish_color_param 171E2B
set -g fish_color_option 515867
set -g fish_color_comment 515867
set -g fish_color_operator 223659
set -g fish_color_escape EDE0D4
set -g fish_color_autosuggestion 515867
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=D6D3CD
set -g fish_color_search_match --background=D6D3CD
set -g fish_pager_color_prefix 223659 --bold
set -g fish_pager_color_completion 171E2B
set -g fish_pager_color_description 515867
set -g fish_pager_color_progress EDE0D4
