// Generates research/uniform-size/option-d.css from today's measurements
// (the "a-comfortable" run of measurements.json).
//
//   node research/uniform-size/build-d.mjs
//
// Option D keeps every theme's own box metrics but holds each one inside a
// band: for every element and every property below, a theme's value is
// clamped to the cross-theme median ±8% (at least ±2px, so a median of 0 is
// not a band of zero). In the package this would be a `clamp()` in the base
// layer around a size token a register sets, e.g.
//   min-height: clamp(2.07rem, var(--kp-button-height), 2.43rem);
// which needs registers to express their sizes as tokens first. The demo
// cannot read a register's value inside clamp(), so it writes the clamped
// value per theme instead — the same result, spelled out.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('./', import.meta.url));
const run = JSON.parse(readFileSync(`${HERE}measurements.json`, 'utf8')).runs['a-comfortable'];
const THEMES = JSON.parse(readFileSync(`${HERE}../../themes/order.json`, 'utf8'));
const BAND = 0.08;

// measured element → the package selector the clamp would sit on, and which
// of its properties are clamped.
const TARGETS = [
    ['button', '.kp-button', ['minHeight', 'padBlock', 'padInline', 'fontSize']],
    ['button-sm', '.kp-button.kp-button--sm', ['minHeight', 'padBlock', 'padInline', 'fontSize']],
    ['input', ':is(.kp-field__input, .kp-combobox__input)', ['padBlock', 'padInline', 'fontSize']],
    ['field-label', '.kp-field__label', ['fontSize']],
    ['card', '.kp-card', ['padBlock', 'padInline']],
    ['card-title', '.kp-card__title', ['fontSize']],
    ['badge', '.kp-badge', ['padBlock', 'padInline', 'fontSize']],
    ['alert', '.kp-alert', ['padBlock', 'padInline', 'fontSize']],
    ['tab', '.kp-tab', ['padBlock', 'padInline', 'fontSize']],
    ['nav', '.kp-nav', ['padBlock', 'padInline']],
    ['nav-link', '.kp-nav__link', ['padBlock', 'padInline', 'fontSize']],
    ['sidenav-item', '.kp-sidenav__link', ['padBlock', 'padInline', 'fontSize']],
    ['table-row', '.kp-table td', ['cellBlock', 'fontSize']],
    ['dialog', '.kp-dialog', ['padBlock', 'padInline']],
    ['dialog-title', '.kp-dialog__title', ['fontSize']],
];

const median = (xs) => {
    const s = [...xs].sort((a, b) => a - b);
    const m = s.length >> 1;
    return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const px = (v) => (typeof v === 'number' ? v : parseFloat(v));
const READ = {
    minHeight: (m) => px(m.minHeight) || 0,
    padBlock: (m) => [m.padding[0], m.padding[2]],
    padInline: (m) => [m.padding[3], m.padding[1]],
    cellBlock: (m) => [m.cellPadding[0], m.cellPadding[2]],
    fontSize: (m) => m.fontSize,
};
const WRITE = {
    minHeight: ([v]) => `min-height: ${v}px`,
    padBlock: ([a, b]) => `padding-block: ${a}px ${b}px`,
    padInline: ([a, b]) => `padding-inline: ${a}px ${b}px`,
    cellBlock: ([a, b]) => `padding-block: ${a}px ${b}px`,
    fontSize: ([v]) => `font-size: ${v}px`,
};

const r2 = (x) => Math.round(x * 100) / 100;
let css = `/* research/uniform-size/option-d.css — MOCK, GENERATED by build-d.mjs; not part of the package.

   Option D · every theme keeps its own sizes, clamped to a band of ±${BAND * 100}% (at
   least ±2px) around the cross-theme median of each property. Only the values
   that fall outside the band are written. Scoped to <html data-option="d">. */\n`;
let count = 0;
for (const theme of THEMES) {
    const lines = [];
    for (const [element, selector, props] of TARGETS) {
        const decls = [];
        for (const prop of props) {
            const values = THEMES.map((t) => [].concat(READ[prop](run[t].elements[element])));
            const mine = [].concat(READ[prop](run[theme].elements[element]));
            const meds = mine.map((_, i) => median(values.map((v) => v[i])));
            const clamped = mine.map((v, i) => {
                const d = Math.max(meds[i] * BAND, 2);
                return r2(Math.min(meds[i] + d, Math.max(meds[i] - d, v)));
            });
            if (clamped.some((v, i) => Math.abs(v - mine[i]) > 0.01)) decls.push(WRITE[prop](clamped));
        }
        if (decls.length) {
            count += decls.length;
            lines.push(`[data-option='d'][data-theme='${theme}'] ${selector} {\n    ${decls.join(';\n    ')};\n}`);
        }
    }
    if (lines.length) css += `\n/* ${theme} */\n${lines.join('\n')}\n`;
}
writeFileSync(`${HERE}option-d.css`, css);
console.log(`option-d.css: ${count} declarations clamped`);
