# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Brutalism. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 121212
set -g fish_color_command B9A6F2
set -g fish_color_keyword 121212
set -g fish_color_quote 121212
set -g fish_color_redirection 096AAE
set -g fish_color_end 096AAE
set -g fish_color_error BD0F0F
set -g fish_color_param 121212
set -g fish_color_option 474747
set -g fish_color_comment 474747
set -g fish_color_operator 121212
set -g fish_color_escape B9A6F2
set -g fish_color_autosuggestion 474747
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=EBC400
set -g fish_color_search_match --background=EBC400
set -g fish_pager_color_prefix 121212 --bold
set -g fish_pager_color_completion 121212
set -g fish_pager_color_description 474747
set -g fish_pager_color_progress B9A6F2
