# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Terminal. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 68F368
set -g fish_color_command DFF20D
set -g fish_color_keyword 0DF20D
set -g fish_color_quote C9DB00
set -g fish_color_redirection 47D1D1
set -g fish_color_end 47D1D1
set -g fish_color_error F54747
set -g fish_color_param 68F368
set -g fish_color_option 86B686
set -g fish_color_comment 86B686
set -g fish_color_operator 0DF20D
set -g fish_color_escape DFF20D
set -g fish_color_autosuggestion 86B686
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=1D251D
set -g fish_color_search_match --background=1D251D
set -g fish_pager_color_prefix 0DF20D --bold
set -g fish_pager_color_completion 68F368
set -g fish_pager_color_description 86B686
set -g fish_pager_color_progress DFF20D
