@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). Double-click: the whole desktop in KP Grotesk.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\..\apply.ps1" -Theme grotesk -Pause
