@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). Back to the Windows 11 right-click menu.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\..\context-menu.ps1" -Style Modern -Pause
