@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). The full right-click menu at once, as in Windows 10.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\..\context-menu.ps1" -Style Classic -Pause
