@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). All KP themes in VS Code; the active theme is left alone.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\..\install-vscode.ps1" -Pause
