@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). Arch Linux in WSL, Garuda-style, with ~/Projects/kp-themes cloned.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\..\setup-wsl.ps1" -Pause
