@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs). Build desktop/ in the WSL clone and install it here.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\windows\install.ps1" -FromWsl -Pause
