// The concept page's words, per theme [S49, A1 of 2026-09-08].
//
// One approved concept demo per theme (S46), and Kenny's rule is that a
// demo is implemented exactly — "voor de rest moet het gewoon zo
// geimplementeerd worden voor alle tokens/elementen" (2026-09-08, S49).
// Until this file existed, examples/concept.html carried cyberpunk's
// words under every theme: phantom's calling card said "Stop looking
// like a theme", retro's desktop booted a neural uplink. The structure
// and the markers are the same for every theme (S46, KT11); only the
// words change, and they are the words of that theme's own demo.
//
// Every entry has the same slots, which is what makes the pages
// comparable: gates/gates.test.mjs holds the shape and refuses a theme
// whose entry is missing one. `cyberpunk` is the default the picker page
// shows; a theme with no entry here shows that default, which is the
// honest state for a theme whose demo has not been built yet.

/** @typedef {Record<string, string>} ConceptCopy */

/** @type {Record<string, ConceptCopy>} */
export const CONCEPT_COPY = {
    cyberpunk: {
        brand: 'kp-themes',
        brandTag: 'SIG//06',
        navThemes: 'Themes',
        navThemes1: 'Signal',
        navThemes2: 'Synthwave',
        navThemes3: 'Nostromo',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NC · 2077 · SECTOR 06 · 0x1F',
        laurel1b: '“Spits off the screen”',
        laurel1: 'the brief',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'register 02 · preview build',
        headline: 'Stop looking like a theme.',
        lede1: 'Signal yellow on void. Blood red ',
        ledeMark1: 'where it counts',
        lede2: '. Neon only ',
        ledeMark2: 'where it hurts',
        lede3: '. A cyberpunk register for kp-themes that behaves like a place, not a palette.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'label',
        spec5: 'glitch',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@dogtown.nc',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'District',
        district1: 'Watson',
        district2: 'Westbrook',
        district3: 'Santo Domingo',
        district4: 'Dogtown',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this register ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.kp-themes-06',
        h2Dossier: 'The register, on record',
        cardTitle: 'Signal',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A second cyberpunk register for kp-themes. The first one was ',
        dossierMark1: 'violet night and magenta',
        dossier2: '; this one is built on ',
        dossierMark2: 'signal yellow and blood red',
        dossier3: ', with cyan for what must be read and violet only inside a glitch. Every effect is ',
        dossierMark3: 'opt-in and reduced-motion safe',
        dossier4: ', and the old register stays exactly as shipped.',
        dossierPara2:
            'Open the file to clear the redactions. They lift one after another, the way a document does when the clearance comes through — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, six registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Signal',
        footerCol2b: 'Cyberpunk (archived)',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '▶ Calibrating neural uplink',
        arrivalReady: 'OK',
    },
    phantom: {
        brand: 'kp-themes',
        brandTag: 'PH//15',
        navThemes: 'Themes',
        navThemes1: 'Phantom',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Case files',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'FILE 15 · CUT PAPER · NO GLOW',
        laurel1b: '“Energy without light”',
        laurel1: 'the anatomy',
        laurel2b: 'Three colours',
        laurel2: 'black, white, one red',
        laurel3b: 'DI5 safe',
        laurel3: 'every gesture a transform',
        microlabelHero: 'theme 15 · preview build',
        headline: 'We are taking your interface.',
        lede1: 'Cut paper, not glass. A halftone screen ',
        ledeMark1: 'where it prints',
        lede2: ', one violent red ',
        ledeMark2: 'where it cuts',
        lede3: ', and condensed italic capitals doing the shouting. A phantom theme for kp-themes that behaves like a heist, not a palette.',
        btnPrimary: 'Send the card',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'void #0A0A0A',
        spec2: 'void #0A0A0A',
        spec3: 'yellow #FFC61A',
        spec4: 'grey #ADADAD',
        spec5: 'red #FF293B',
        spec6: 'Barlow Condensed 800 italic',
        spec7: 'Barlow 400–700',
        spec8: 'system ui-monospace',
        microlabelForm: 'access.calling_card',
        h2Form: 'Request a codename',
        handleLabel: 'Codename',
        handlePlaceholder: 'joker',
        handleHelp: 'Lowercase, no spaces. One word is enough.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@phantom.example',
        mailHelp: 'We answer before the deadline you did not set.',
        districtLabel: 'Target',
        district1: 'The navigation',
        district2: 'The empty state',
        district3: 'The settings screen',
        district4: 'All of it',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the card',
        btnWipe: 'Burn the card',
        wipeConfirm: 'Burn it — sure?',
        microlabelDossier: 'case_file.kp-themes-15',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Phantom',
        stampLabel: 'Calling card',
        stampLabelOpen: 'Card read',
        dossierMeta: 'FILE 15 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phantom theme for kp-themes. Cyberpunk emits light; this one is ',
        dossierMark1: 'print, not screen',
        dossier2: '. The red is ',
        dossierMark2: 'a plate, never a word',
        dossier3: ', the headings are condensed italic capitals, and every gesture is ',
        dossierMark3: 'a transform or a clip-path',
        dossier4: ', which is why the flash threshold never enters.',
        dossierPara2:
            'Open the file to lift the censor plates. They shear off one after another, right edge first, the way a page is torn rather than faded.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-four themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Phantom',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '▮ Build 5.0.0-preview · cut from tokens · no hearts were harmed',
        arrivalLine: 'Phantom',
        arrivalReady: 'Delivered.',
    },
    retro: {
        brand: 'kp-themes 95',
        brandTag: '— [Retro]',
        navThemes: 'Themes',
        navThemes1: 'Retro',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Fields',
        navComponents3: 'Windows',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'SYSTEM PROPERTIES · BUILD 95 · READY',
        laurel1b: 'Chrome you can press',
        laurel1: 'the brief',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 ms',
        laurel3: 'every transition',
        microlabelHero: 'C:\\KP\\THEMES\\RETRO> theme 03 · preview build',
        headline: 'Press it. It goes down.',
        lede1: 'Mid-grey chrome, a navy title bar, and an edge you can point at. Bevels ',
        ledeMark1: 'where you press',
        lede2: '. Wells ',
        ledeMark2: 'where you type',
        lede3: '. A retro theme for kp-themes that behaves like a desktop, not a filter.',
        btnPrimary: 'Open the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Help',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'window',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'title',
        spec6: 'display',
        spec7: 'body',
        spec8: 'dos',
        microlabelForm: 'C:\\KP\\ACCESS> request.exe',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'user95',
        handleHelp: 'Eight characters, no spaces. It was 1995.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@lan.local',
        mailHelp: 'We answer before the modem finishes.',
        districtLabel: 'Workgroup',
        district1: 'WORKGROUP',
        district2: 'LAB',
        district3: 'NIGHTSHIFT',
        district4: 'DIALUP',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — are you sure?',
        microlabelDossier: 'C:\\KP\\DOCS> type dossier.txt',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Retro',
        stampLabel: 'READ ONLY',
        stampLabelOpen: 'READ/WRITE',
        dossierMeta: 'FILE 03 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A 1995 desktop for kp-themes. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'square and grey',
        dossier3: ': every control a bevel, every field a well, every edge a real boundary at ',
        dossierMark3: '3.31 on the chrome',
        dossier4: '. Nothing here eases, blinks or scrolls by itself.',
        dossierPara2:
            'Open the file to lift the dither. The brush comes off one block at a time, left to right, the way a 1995 screen actually repainted — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Retro',
        footerCol2b: 'Signal',
        footerCol2c: 'Synthwave',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 5.0.0-preview · rendered from tokens · 0 bytes of images',
        arrivalLine: 'KP Modular BIOS v4.51PG · kp-themes 95 — retro build · Memory Test : 0K',
        arrivalReady: 'OK',
    },
    terminal: {
        brand: 'kp-themes',
        brandTag: 'TTY//06',
        navThemes: 'themes',
        navThemes1: 'signal',
        navThemes2: 'synthwave',
        navThemes3: 'terminal',
        navComponents: 'components',
        navComponents1: 'buttons',
        navComponents2: 'forms',
        navComponents3: 'dossiers',
        navEffects: 'effects',
        navDocs: 'man',
        navLang: 'LANG=EN',
        navLang1: 'nl_NL',
        navLang2: 'en_GB',
        navCta: 'run it',
        sideNote: '● REC · VT220 · 80×24 · 9600 8N1',
        laurel1b: 'tty06',
        laurel1: 'terminal 5.0.0',
        laurel2b: '93',
        laurel2: 'tokens at parity',
        laurel3b: '1 Hz',
        laurel3: 'the only loop',
        microlabelHero: 'kp@vt220:~$ cat MOTD',
        headline: 'Everything is a character cell.',
        lede1: 'Phosphor green on near-black glass, one monospaced face, no rounded corners. Emphasis is ',
        ledeMark1: 'inverse video',
        lede2: '; a boundary is ',
        ledeMark2: 'a dimmer phosphor',
        lede3: '. The screen draws with what it has, and it has one colour.',
        btnPrimary: 'run the demo',
        btnSecondary: 'read the man page',
        btnGhost: 'dry run',
        platform1: 'chromium',
        platform2: 'firefox',
        platform3: 'framework-free',
        platform4: 'react',
        spec1: 'ground: void #0B0E0B',
        spec2: 'panel: well #0F140F',
        spec3: 'text: phosphor #68F368',
        spec4: 'plate: bright #0DF20D',
        spec5: 'muted: dim #86B686',
        spec6: 'accent: signal #DFF20D',
        spec7: 'alarm: red #F54747',
        spec8: 'face: Share Tech Mono 400 — the only face',
        microlabelForm: 'kp@vt220:~$ ./request --handle',
        h2Form: 'Request a handle',
        handleLabel: 'handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'lowercase, dots allowed, no spaces',
        mailLabel: 'contact',
        mailPlaceholder: 'you@vt220.net',
        mailHelp: 'we answer within one session',
        districtLabel: 'tty',
        district1: 'tty0 — console',
        district2: 'tty1 — serial',
        district3: 'pts/0 — pseudo',
        district4: 'screen — multiplexed',
        whyLabel: 'why you',
        whyPlaceholder: 'Two lines. Eighty columns each.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'send request',
        btnWipe: 'wipe form',
        wipeConfirm: 'wipe — y/n?',
        microlabelDossier: 'dossier.terminal-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'terminal',
        stampLabel: 'CLASSIFIED',
        stampLabelOpen: 'DECLASSIFIED',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phosphor CRT theme. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'quiet and gridded',
        dossier3: ': eighty columns, twenty-four rows, and ',
        dossierMark3: 'one hue at 120°',
        dossier4: '. It does not merely look like a terminal — it accepts a terminal\u0027s constraints.',
        dossierPara2:
            'Open the file to clear the redactions. They repaint left to right, one cell at a time, the way a screen draws a line — not the way a curtain opens.',
        dossierTrigger: 'open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'registers',
        footerCol2a: 'plain',
        footerCol2b: 'expressive',
        footerCol2c: 'terminal fx',
        footerCol3: 'channels',
        footerCol3a: 'framework-free',
        footerCol3b: 'react',
        footerCol3c: 'home assistant',
        footerFine: '$ build 5.0.0-preview · rendered from tokens · no phosphor was burned',
        arrivalLine: 'KP-THEMES BIOS v5.0.0 · MEMORY TEST ......... 640K OK · PHOSPHOR PROFILE .... terminal · CRT WARM-UP ......... OK · READY.',
        arrivalReady: 'READY.',
    },
    brutalism: {
        brand: 'kp-themes',
        brandTag: 'THM//12',
        navThemes: 'Themes',
        navThemes1: 'Brutalism',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Plates',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NO BLUR · NO GRADIENT · RADIUS 0',
        laurel1b: '"Flat by exaggeration"',
        laurel1: 'the anatomy',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'one marquee, no flash',
        microlabelHero: 'theme 12 · preview build',
        headline: 'Hard lines. Hard shadow. No apology.',
        lede1: 'Off-white paper, a three-pixel black line, and a shadow that sits exactly where the box would fall ',
        ledeMark1: 'if you let go',
        lede2: '. Candy plates, black ink, ',
        ledeMark2: 'nothing blurred',
        lede3: '. A brutalist theme for kp-themes that behaves like printed matter, not a surface.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'Paper #FFFCF0',
        spec2: 'Ink #121212',
        spec3: 'Signal red #F43333',
        spec4: 'Yellow #FFD633',
        spec5: 'Lavender #B9A6F2',
        spec6: 'Archivo Black',
        spec7: 'Space Grotesk 400–700',
        spec8: 'System ui-monospace',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'k.passenier',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@paper.press',
        mailHelp: 'We answer in one working day.',
        districtLabel: 'Your plate',
        district1: 'Yellow',
        district2: 'Lavender',
        district3: 'Mint',
        district4: 'Sky',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — sure?',
        microlabelDossier: 'dossier.kp-themes-12',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Brutalism',
        stampLabel: 'Sealed',
        stampLabelOpen: 'Open',
        dossierMeta: 'FILE 12 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'Neo-brutalism, the 2021 kind, not the concrete of the 1960s. Black is ',
        dossierMark1: 'the structure',
        dossier2: '; the shadow is ',
        dossierMark2: 'a knob, not a rule',
        dossier3: '; and the loud colour is ',
        dossierMark3: 'the common one',
        dossier4: '. Nothing is blurred, nothing is translucent, nothing pretends to be a material.',
        dossierPara2: 'Open the file to lift the bars. They go one after another, the way a redaction pen is dragged off a page — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Brutalism',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED · NO GRADIENTS · NO BLUR · RADIUS 0',
        arrivalLine: '',
        arrivalReady: '',
    },
    'shade-dark': {
        brand: 'kp-themes',
        brandTag: 'SD//06',
        navThemes: 'Themes',
        navThemes1: 'Shade (light)',
        navThemes2: 'Shade (dark)',
        navThemes3: 'Nishiki',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'ED. II · NIGHT DESK · BASE03',
        laurel1b: 'Solarized, mirrored',
        laurel1: 'same scheme, lightness flipped',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'nothing loops',
        microlabelHero: 'register · shade, dark half',
        headline: 'Legible after the lights go down.',
        lede1: "Solarized's own ground, lifted for reading — ",
        ledeMark1: 'medium contrast',
        lede2: ' where white would glare, ',
        ledeMark2: 'plates that hold the line',
        lede3: ' where a boundary has to be seen.',
        btnPrimary: 'Open the desk',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'chart',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request access',
        handleLabel: 'Handle',
        handlePlaceholder: 'n.reyes',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@nightdesk.io',
        mailHelp: 'We read the night desk once a shift.',
        districtLabel: 'Desk',
        district1: 'Night desk',
        district2: 'Wire desk',
        district3: 'Archive',
        district4: 'Standing bureau',
        whyLabel: 'Why',
        whyPlaceholder: 'Two lines. Keep it plain.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.shade-dark-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Shade',
        stampLabel: 'Classified',
        stampLabelOpen: 'Lifted',
        dossierMeta: 'FILE 06 · STATUS: LIFTED · CLEARANCE: KENNY',
        dossier1: 'The dark half mirrors ',
        dossierMark1: "the light half's own scheme",
        dossier2: ' rather than inventing a second palette; the ground moved from ',
        dossierMark2: "Solarized's paper",
        dossier3: ' to ',
        dossierMark3: 'its base03 ink',
        dossier4: ', and every accent lifted to match.',
        dossierPara2: 'Open the file to clear the redactions. They lift left to right, the way a document does when the clearance comes through.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Themes',
        footerCol2a: 'Shade (light)',
        footerCol2b: 'Shade (dark)',
        footerCol2c: 'Nishiki',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// SHADE, DARK HALF · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    tazhib: {
        brand: 'Lapis & Leaf',
        brandTag: 'MS//07',
        navThemes: 'Folios',
        navThemes1: 'Diwan pages',
        navThemes2: 'Frontispieces',
        navThemes3: 'Marginalia',
        navComponents: 'Workshop',
        navComponents1: 'Pigments',
        navComponents2: 'Gold ground',
        navComponents3: 'Ruling',
        navEffects: 'Commissions',
        navDocs: 'Colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request a folio',
        sideNote: 'MS · SAFAVID HAND · f.1r',
        laurel1b: '“Gold acts.”',
        laurel1: "the anatomy's own rule",
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'the ruling never flashes',
        microlabelHero: 'atelier · folio 07 · new commission',
        headline: 'Every page begins in gold.',
        lede1: 'Lapis for the ground, gold for the ruling, and vermilion where the eye must stop. Ten-fold geometry drawn once, felt ',
        ledeMark1: 'everywhere it repeats',
        lede2: ', seen nowhere as a flourish — a single hand, disciplined the way ',
        ledeMark2: 'a manuscript page is disciplined',
        lede3: '.',
        btnPrimary: 'Open a commission',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'See the ruling',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'gold',
        spec4: 'vermilion',
        spec5: 'jade',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'workshop.request_form',
        h2Form: 'Commission a folio',
        handleLabel: 'Patron',
        handlePlaceholder: 'Farrukh Beg',
        handleHelp: 'The name entered in the colophon.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@atelier.example',
        mailHelp: 'We answer within one moon.',
        districtLabel: 'Ground',
        district1: 'Lapis lazuli',
        district2: 'Verdigris wash',
        district3: 'Plain vellum',
        district4: 'Gold ground',
        whyLabel: 'Brief',
        whyPlaceholder: 'Two lines. The border carries the rest.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the commission',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.folio-07',
        h2Dossier: 'The commission, on record',
        cardTitle: 'Folio 07',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 07 · STATUS: IN THE WORKSHOP · HAND: UNVERIFIED',
        dossier1: 'The commission was placed by ',
        dossierMark1: "Farrukh Beg's workshop",
        dossier2: ' for a sum of ',
        dossierMark2: '140 dinars',
        dossier3: ', delivery promised by ',
        dossierMark3: 'the spring new moon',
        dossier4: '. Every ring on the frame is one declaration; every star repeats at 36 degrees and never once as decoration.',
        dossierPara2:
            "Lift the seal to read it whole. The ground clears left to right, the way a gilder's burnish reveals gold that was always there — not all at once.",
        dossierTrigger: 'Lift the seal',
        footerTitle: 'Lapis & Leaf',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Folios',
        footerCol2a: 'Diwan pages',
        footerCol2b: 'Frontispieces',
        footerCol2c: 'Marginalia',
        footerCol3: 'Workshop',
        footerCol3a: 'Pigments',
        footerCol3b: 'Gold ground',
        footerCol3c: 'Ruling',
        footerFine: '/// TAZHIB · RENDERED FROM TOKENS · NO GOLD LEAF WAS HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    'high-contrast': {
        brand: 'kp-themes',
        brandTag: 'AAA//21:1',
        navThemes: 'Theme',
        navThemes1: 'Anatomy',
        navThemes2: 'Tokens',
        navThemes3: 'Invariants',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'AAA · WCAG 2.2 · 21:1',
        laurel1b: '21:1',
        laurel1: 'ink on paper',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 gradients',
        laurel3: 'nothing to fade',
        microlabelHero: 'accessibility floor · reference build',
        headline: 'Built to be read, not admired.',
        lede1: 'Twenty-one to one, ',
        ledeMark1: 'every time',
        lede2: '. One accent colour with a job, ',
        ledeMark2: 'never a decoration',
        lede3: '. This is kp-themes for the reader who needs contrast, not comfort.',
        btnPrimary: 'Read the anatomy',
        btnSecondary: 'See the tokens',
        btnGhost: 'No fill',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'page',
        spec3: 'alert',
        spec4: 'signal',
        spec5: 'flag',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'form.request',
        h2Form: 'Request access',
        handleLabel: 'Name',
        handlePlaceholder: 'Jordan Reyes',
        handleHelp: 'As it should appear on the record.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within one business day.',
        districtLabel: 'Reason for access',
        district1: 'Low vision',
        district2: 'Bright-daylight use',
        district3: 'End-of-shift fatigue',
        district4: 'Other',
        whyLabel: 'Notes',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: "Wipe everything you've typed?",
        microlabelDossier: 'dossier.high-contrast',
        h2Dossier: 'The record, unredacted',
        cardTitle: 'Who this theme is for',
        stampLabel: 'On record',
        stampLabelOpen: 'On record',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: AAA',
        dossier1: 'This is the theme for someone who finds the other twenty-four too soft: ',
        dossierMark1: 'low vision',
        dossier2: ', ',
        dossierMark2: 'a screen in daylight',
        dossier3: ', or ',
        dossierMark3: 'tired eyes at the end of a shift',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Related themes',
        footerCol2a: 'Formal',
        footerCol2b: 'Light',
        footerCol2c: 'Blueprint',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
};

/** The theme the picker page and every page without its own copy shows. */
export const DEFAULT_COPY_THEME = 'cyberpunk';

/** The themes that carry their own words, in the order they were lifted. */
export const COPY_THEMES = Object.keys(CONCEPT_COPY);

/**
 * The copy a page is rendered with.
 *
 * @param {string} [theme]
 * @returns {ConceptCopy}
 */
export function conceptCopy(theme) {
    return CONCEPT_COPY[theme ?? DEFAULT_COPY_THEME] ?? CONCEPT_COPY[DEFAULT_COPY_THEME];
}
