// The concept page's words, per theme [S49, A1 of 2026-09-08].
//
// One approved concept demo per theme (S46), and Kenny's rule is that a
// demo is implemented exactly — "voor de rest moet het gewoon zo
// geimplementeerd worden voor alle tokens/elementen" (2026-09-08, S49).
// Until this file existed, examples/concept.html carried cyberpunk's
// words under every theme: phantom's calling card said "Stop looking
// like a theme", retro's desktop booted a neural uplink. The structure
// and the markers are the same for every theme (S46, KT11); only the
// words change, and they are the words of that theme's own demo.
//
// Every entry has the same slots, which is what makes the pages
// comparable: gates/gates.test.mjs holds the shape and refuses a theme
// whose entry is missing one. `cyberpunk` is the default the picker page
// shows; a theme with no entry here shows that default, which is the
// honest state for a theme whose demo has not been built yet.

/** @typedef {Record<string, string>} ConceptCopy */

/** @type {Record<string, ConceptCopy>} */
export const CONCEPT_COPY = {
    cyberpunk: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'SIG//06',
        navThemes: 'Themes',
        navThemes1: 'Signal',
        navThemes2: 'Synthwave',
        navThemes3: 'Nostromo',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NC · 2077 · SECTOR 06 · 0x1F',
        band1: 'SECTOR 06 ONLINE',
        band2: 'SIGNAL YELLOW · BLOOD RED',
        band3: 'NO FLASHING · DI5 CLEAR',
        band4: '0x1F // TRACE CLEAN',
        laurel1b: '“Spits off the screen”',
        laurel1: 'the brief',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'register 02 · preview build',
        headline: 'Stop looking like a theme.',
        lede1: 'Signal yellow on void. Blood red ',
        ledeMark1: 'where it counts',
        lede2: '. Neon only ',
        ledeMark2: 'where it hurts',
        lede3: '. A cyberpunk register for kp-themes that behaves like a place, not a palette.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'label',
        spec5: 'glitch',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@dogtown.nc',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'District',
        district1: 'Watson',
        district2: 'Westbrook',
        district3: 'Santo Domingo',
        district4: 'Dogtown',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this register ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.kp-themes-06',
        h2Dossier: 'The register, on record',
        cardTitle: 'Signal',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A second cyberpunk register for kp-themes. The first one was ',
        dossierMark1: 'violet night and magenta',
        dossier2: '; this one is built on ',
        dossierMark2: 'signal yellow and blood red',
        dossier3: ', with cyan for what must be read and violet only inside a glitch. Every effect is ',
        dossierMark3: 'opt-in and reduced-motion safe',
        dossier4: ', and the old register stays exactly as shipped.',
        dossierPara2:
            'Open the file to clear the redactions. They lift one after another, the way a document does when the clearance comes through — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Signal',
        footerCol2b: 'Cyberpunk (archived)',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '▶ Calibrating neural uplink',
        arrivalReady: 'OK',
    },
    phantom: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'PH//15',
        navThemes: 'Themes',
        navThemes1: 'Phantom',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Case files',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'FILE 15 · CUT PAPER · NO GLOW',
        band1: 'CALLING CARD 15',
        band2: 'CUT PAPER · NO GLOW',
        band3: 'THREE COLOURS, NO MORE',
        band4: 'EVERY GESTURE A TRANSFORM',
        laurel1b: '“Energy without light”',
        laurel1: 'the anatomy',
        laurel2b: 'Three colours',
        laurel2: 'black, white, one red',
        laurel3b: 'DI5 safe',
        laurel3: 'every gesture a transform',
        microlabelHero: 'theme 15 · preview build',
        headline: 'We are taking your interface.',
        lede1: 'Cut paper, not glass. A halftone screen ',
        ledeMark1: 'where it prints',
        lede2: ', one violent red ',
        ledeMark2: 'where it cuts',
        lede3: ', and condensed italic capitals doing the shouting. A phantom theme for kp-themes that behaves like a heist, not a palette.',
        btnPrimary: 'Send the card',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'void #0A0A0A',
        spec2: 'void #0A0A0A',
        spec3: 'yellow #FFC61A',
        spec4: 'grey #ADADAD',
        spec5: 'red #FF293B',
        spec6: 'Barlow Condensed 800 italic',
        spec7: 'Barlow 400–700',
        spec8: 'system ui-monospace',
        microlabelForm: 'access.calling_card',
        h2Form: 'Request a codename',
        handleLabel: 'Codename',
        handlePlaceholder: 'joker',
        handleHelp: 'Lowercase, no spaces. One word is enough.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@phantom.example',
        mailHelp: 'We answer before the deadline you did not set.',
        districtLabel: 'Target',
        district1: 'The navigation',
        district2: 'The empty state',
        district3: 'The settings screen',
        district4: 'All of it',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the card',
        btnWipe: 'Burn the card',
        wipeConfirm: 'Burn it — sure?',
        microlabelDossier: 'case_file.kp-themes-15',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Phantom',
        stampLabel: 'Calling card',
        stampLabelOpen: 'Card read',
        dossierMeta: 'FILE 15 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phantom theme for kp-themes. Cyberpunk emits light; this one is ',
        dossierMark1: 'print, not screen',
        dossier2: '. The red is ',
        dossierMark2: 'a plate, never a word',
        dossier3: ', the headings are condensed italic capitals, and every gesture is ',
        dossierMark3: 'a transform or a clip-path',
        dossier4: ', which is why the flash threshold never enters.',
        dossierPara2:
            'Open the file to lift the censor plates. They shear off one after another, right edge first, the way a page is torn rather than faded.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Phantom',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '▮ Build 5.0.0-preview · cut from tokens · no hearts were harmed',
        arrivalLine: 'Phantom',
        arrivalReady: 'Delivered.',
    },
    retro: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes 95',
        brandTag: '— [Retro]',
        navThemes: 'Themes',
        navThemes1: 'Retro',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Fields',
        navComponents3: 'Windows',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'SYSTEM PROPERTIES · BUILD 95 · READY',
        band1: 'SYSTEM PROPERTIES',
        band2: 'CHROME YOU CAN PRESS',
        band3: '0 MS TRANSITIONS',
        band4: 'BUILD 95 · READY',
        laurel1b: 'Chrome you can press',
        laurel1: 'the brief',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 ms',
        laurel3: 'every transition',
        microlabelHero: 'C:\\KP\\THEMES\\RETRO> theme 03 · preview build',
        headline: 'Press it. It goes down.',
        lede1: 'Mid-grey chrome, a navy title bar, and an edge you can point at. Bevels ',
        ledeMark1: 'where you press',
        lede2: '. Wells ',
        ledeMark2: 'where you type',
        lede3: '. A retro theme for kp-themes that behaves like a desktop, not a filter.',
        btnPrimary: 'Open the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Help',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'window',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'title',
        spec6: 'display',
        spec7: 'body',
        spec8: 'dos',
        microlabelForm: 'C:\\KP\\ACCESS> request.exe',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'user95',
        handleHelp: 'Eight characters, no spaces. It was 1995.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@lan.local',
        mailHelp: 'We answer before the modem finishes.',
        districtLabel: 'Workgroup',
        district1: 'WORKGROUP',
        district2: 'LAB',
        district3: 'NIGHTSHIFT',
        district4: 'DIALUP',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — are you sure?',
        microlabelDossier: 'C:\\KP\\DOCS> type dossier.txt',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Retro',
        stampLabel: 'READ ONLY',
        stampLabelOpen: 'READ/WRITE',
        dossierMeta: 'FILE 03 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A 1995 desktop for kp-themes. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'square and grey',
        dossier3: ': every control a bevel, every field a well, every edge a real boundary at ',
        dossierMark3: '3.31 on the chrome',
        dossier4: '. Nothing here eases, blinks or scrolls by itself.',
        dossierPara2:
            'Open the file to lift the dither. The brush comes off one block at a time, left to right, the way a 1995 screen actually repainted — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Retro',
        footerCol2b: 'Signal',
        footerCol2c: 'Synthwave',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 5.0.0-preview · rendered from tokens · 0 bytes of images',
        arrivalLine: 'KP Modular BIOS v4.51PG · kp-themes 95 — retro build · Memory Test : 0K',
        arrivalReady: 'OK',
    },
    terminal: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'TTY//06',
        navThemes: 'themes',
        navThemes1: 'signal',
        navThemes2: 'synthwave',
        navThemes3: 'terminal',
        navComponents: 'components',
        navComponents1: 'buttons',
        navComponents2: 'forms',
        navComponents3: 'dossiers',
        navEffects: 'effects',
        navDocs: 'man',
        navLang: 'LANG=EN',
        navLang1: 'nl_NL',
        navLang2: 'en_GB',
        navCta: 'run it',
        sideNote: '● REC · VT220 · 80×24 · 9600 8N1',
        band1: '80×24 · 9600 8N1',
        band2: 'EVERY CELL A CHARACTER',
        band3: 'CURSOR AT 1 HZ',
        band4: 'TTY06 · READY',
        laurel1b: 'tty06',
        laurel1: 'terminal 5.0.0',
        laurel2b: '93',
        laurel2: 'tokens at parity',
        laurel3b: '1 Hz',
        laurel3: 'the only loop',
        microlabelHero: 'kp@vt220:~$ cat MOTD',
        headline: 'Everything is a character cell.',
        lede1: 'Phosphor green on near-black glass, one monospaced face, no rounded corners. Emphasis is ',
        ledeMark1: 'inverse video',
        lede2: '; a boundary is ',
        ledeMark2: 'a dimmer phosphor',
        lede3: '. The screen draws with what it has, and it has one colour.',
        btnPrimary: 'run the demo',
        btnSecondary: 'read the man page',
        btnGhost: 'dry run',
        platform1: 'chromium',
        platform2: 'firefox',
        platform3: 'framework-free',
        platform4: 'react',
        spec1: 'ground: void #0B0E0B',
        spec2: 'panel: well #0F140F',
        spec3: 'text: phosphor #68F368',
        spec4: 'plate: bright #0DF20D',
        spec5: 'muted: dim #86B686',
        spec6: 'accent: signal #DFF20D',
        spec7: 'alarm: red #F54747',
        spec8: 'face: Share Tech Mono 400 — the only face',
        microlabelForm: 'kp@vt220:~$ ./request --handle',
        h2Form: 'Request a handle',
        handleLabel: 'handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'lowercase, dots allowed, no spaces',
        mailLabel: 'contact',
        mailPlaceholder: 'you@vt220.net',
        mailHelp: 'we answer within one session',
        districtLabel: 'tty',
        district1: 'tty0 — console',
        district2: 'tty1 — serial',
        district3: 'pts/0 — pseudo',
        district4: 'screen — multiplexed',
        whyLabel: 'why you',
        whyPlaceholder: 'Two lines. Eighty columns each.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'send request',
        btnWipe: 'wipe form',
        wipeConfirm: 'wipe — y/n?',
        microlabelDossier: 'dossier.terminal-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'terminal',
        stampLabel: 'CLASSIFIED',
        stampLabelOpen: 'DECLASSIFIED',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phosphor CRT theme. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'quiet and gridded',
        dossier3: ': eighty columns, twenty-four rows, and ',
        dossierMark3: 'one hue at 120°',
        dossier4: '. It does not merely look like a terminal — it accepts a terminal\u0027s constraints.',
        dossierPara2:
            'Open the file to clear the redactions. They repaint left to right, one cell at a time, the way a screen draws a line — not the way a curtain opens.',
        dossierTrigger: 'open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'registers',
        footerCol2a: 'plain',
        footerCol2b: 'expressive',
        footerCol2c: 'terminal fx',
        footerCol3: 'channels',
        footerCol3a: 'framework-free',
        footerCol3b: 'react',
        footerCol3c: 'home assistant',
        footerFine: '$ build 5.0.0-preview · rendered from tokens · no phosphor was burned',
        arrivalLine: 'KP-THEMES BIOS v5.0.0 · MEMORY TEST ......... 640K OK · PHOSPHOR PROFILE .... terminal · CRT WARM-UP ......... OK · READY.',
        arrivalReady: 'READY.',
    },
    brutalism: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'THM//12',
        navThemes: 'Themes',
        navThemes1: 'Brutalism',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Plates',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NO BLUR · NO GRADIENT · RADIUS 0',
        band1: 'RADIUS 0',
        band2: 'NO BLUR',
        band3: 'NO GRADIENT',
        band4: 'HARD SHADOW ONLY',
        laurel1b: '"Flat by exaggeration"',
        laurel1: 'the anatomy',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'one marquee, no flash',
        microlabelHero: 'theme 12 · preview build',
        headline: 'Hard lines. Hard shadow. No apology.',
        lede1: 'Off-white paper, a three-pixel black line, and a shadow that sits exactly where the box would fall ',
        ledeMark1: 'if you let go',
        lede2: '. Candy plates, black ink, ',
        ledeMark2: 'nothing blurred',
        lede3: '. A brutalist theme for kp-themes that behaves like printed matter, not a surface.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'Paper #FFFCF0',
        spec2: 'Ink #121212',
        spec3: 'Signal red #F43333',
        spec4: 'Yellow #FFD633',
        spec5: 'Lavender #B9A6F2',
        spec6: 'Archivo Black',
        spec7: 'Space Grotesk 400–700',
        spec8: 'System ui-monospace',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'k.passenier',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@paper.press',
        mailHelp: 'We answer in one working day.',
        districtLabel: 'Your plate',
        district1: 'Yellow',
        district2: 'Lavender',
        district3: 'Mint',
        district4: 'Sky',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — sure?',
        microlabelDossier: 'dossier.kp-themes-12',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Brutalism',
        stampLabel: 'Sealed',
        stampLabelOpen: 'Open',
        dossierMeta: 'FILE 12 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'Neo-brutalism, the 2021 kind, not the concrete of the 1960s. Black is ',
        dossierMark1: 'the structure',
        dossier2: '; the shadow is ',
        dossierMark2: 'a knob, not a rule',
        dossier3: '; and the loud colour is ',
        dossierMark3: 'the common one',
        dossier4: '. Nothing is blurred, nothing is translucent, nothing pretends to be a material.',
        dossierPara2: 'Open the file to lift the bars. They go one after another, the way a redaction pen is dragged off a page — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Brutalism',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED · NO GRADIENTS · NO BLUR · RADIUS 0',
        arrivalLine: '',
        arrivalReady: '',
    },
    'shade-dark': {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'SD//06',
        navThemes: 'Themes',
        navThemes1: 'Shade (light)',
        navThemes2: 'Shade (dark)',
        navThemes3: 'Nishiki',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'ED. II · NIGHT DESK · BASE03',
        band1: 'Night desk · base03',
        band2: 'Solarized, mirrored',
        band3: 'Nothing loops',
        band4: '94 tokens at parity',
        laurel1b: 'Solarized, mirrored',
        laurel1: 'same scheme, lightness flipped',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'nothing loops',
        microlabelHero: 'register · shade, dark half',
        headline: 'Legible after the lights go down.',
        lede1: "Solarized's own ground, lifted for reading — ",
        ledeMark1: 'medium contrast',
        lede2: ' where white would glare, ',
        ledeMark2: 'plates that hold the line',
        lede3: ' where a boundary has to be seen.',
        btnPrimary: 'Open the desk',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'chart',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request access',
        handleLabel: 'Handle',
        handlePlaceholder: 'n.reyes',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@nightdesk.io',
        mailHelp: 'We read the night desk once a shift.',
        districtLabel: 'Desk',
        district1: 'Night desk',
        district2: 'Wire desk',
        district3: 'Archive',
        district4: 'Standing bureau',
        whyLabel: 'Why',
        whyPlaceholder: 'Two lines. Keep it plain.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.shade-dark-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Shade',
        stampLabel: 'Classified',
        stampLabelOpen: 'Lifted',
        dossierMeta: 'FILE 06 · STATUS: LIFTED · CLEARANCE: KENNY',
        dossier1: 'The dark half mirrors ',
        dossierMark1: "the light half's own scheme",
        dossier2: ' rather than inventing a second palette; the ground moved from ',
        dossierMark2: "Solarized's paper",
        dossier3: ' to ',
        dossierMark3: 'its base03 ink',
        dossier4: ', and every accent lifted to match.',
        dossierPara2: 'Open the file to clear the redactions. They lift left to right, the way a document does when the clearance comes through.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Themes',
        footerCol2a: 'Shade (light)',
        footerCol2b: 'Shade (dark)',
        footerCol2c: 'Nishiki',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// SHADE, DARK HALF · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    lapis: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Lapis & Leaf',
        brandTag: 'MS//07',
        navThemes: 'Folios',
        navThemes1: 'Diwan pages',
        navThemes2: 'Frontispieces',
        navThemes3: 'Marginalia',
        navComponents: 'Workshop',
        navComponents1: 'Pigments',
        navComponents2: 'Gold ground',
        navComponents3: 'Ruling',
        navEffects: 'Commissions',
        navDocs: 'Colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request a folio',
        sideNote: 'MS · SAFAVID HAND · f.1r',
        band1: 'Folio 07 · in the workshop',
        band2: 'Gold acts, ink speaks',
        band3: 'Ruled before it is painted',
        band4: 'No leaf was harmed',
        laurel1b: '“Gold acts.”',
        laurel1: "the anatomy's own rule",
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'the ruling never flashes',
        microlabelHero: 'atelier · folio 07 · new commission',
        headline: 'Every page begins in gold.',
        lede1: 'Lapis for the ground, gold for the ruling, and vermilion where the eye must stop. Ten-fold geometry drawn once, felt ',
        ledeMark1: 'everywhere it repeats',
        lede2: ', seen nowhere as a flourish — a single hand, disciplined the way ',
        ledeMark2: 'a manuscript page is disciplined',
        lede3: '.',
        btnPrimary: 'Open a commission',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'See the ruling',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'gold',
        spec4: 'vermilion',
        spec5: 'jade',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'workshop.request_form',
        h2Form: 'Commission a folio',
        handleLabel: 'Patron',
        handlePlaceholder: 'Farrukh Beg',
        handleHelp: 'The name entered in the colophon.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@atelier.example',
        mailHelp: 'We answer within one moon.',
        districtLabel: 'Ground',
        district1: 'Lapis lazuli',
        district2: 'Verdigris wash',
        district3: 'Plain vellum',
        district4: 'Gold ground',
        whyLabel: 'Brief',
        whyPlaceholder: 'Two lines. The border carries the rest.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the commission',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.folio-07',
        h2Dossier: 'The commission, on record',
        cardTitle: 'Folio 07',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 07 · STATUS: IN THE WORKSHOP · HAND: UNVERIFIED',
        dossier1: 'The commission was placed by ',
        dossierMark1: "Farrukh Beg's workshop",
        dossier2: ' for a sum of ',
        dossierMark2: '140 dinars',
        dossier3: ', delivery promised by ',
        dossierMark3: 'the spring new moon',
        dossier4: '. Every ring on the frame is one declaration; every star repeats at 36 degrees and never once as decoration.',
        dossierPara2:
            "Lift the seal to read it whole. The ground clears left to right, the way a gilder's burnish reveals gold that was always there — not all at once.",
        dossierTrigger: 'Lift the seal',
        footerTitle: 'Lapis & Leaf',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Folios',
        footerCol2a: 'Diwan pages',
        footerCol2b: 'Frontispieces',
        footerCol2c: 'Marginalia',
        footerCol3: 'Workshop',
        footerCol3a: 'Pigments',
        footerCol3b: 'Gold ground',
        footerCol3c: 'Ruling',
        footerFine: '/// TAZHIB · RENDERED FROM TOKENS · NO GOLD LEAF WAS HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    'high-contrast': {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'AAA//21:1',
        navThemes: 'Theme',
        navThemes1: 'Anatomy',
        navThemes2: 'Tokens',
        navThemes3: 'Invariants',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'AAA · WCAG 2.2 · 21:1',
        band1: '21:1 EVERYWHERE',
        band2: 'INK ON PAPER',
        band3: 'NO GRADIENTS',
        band4: 'WCAG 2.2 AAA',
        laurel1b: '21:1',
        laurel1: 'ink on paper',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 gradients',
        laurel3: 'nothing to fade',
        microlabelHero: 'accessibility floor · reference build',
        headline: 'Built to be read, not admired.',
        lede1: 'Twenty-one to one, ',
        ledeMark1: 'every time',
        lede2: '. One accent colour with a job, ',
        ledeMark2: 'never a decoration',
        lede3: '. This is kp-themes for the reader who needs contrast, not comfort.',
        btnPrimary: 'Read the anatomy',
        btnSecondary: 'See the tokens',
        btnGhost: 'No fill',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'page',
        spec3: 'alert',
        spec4: 'signal',
        spec5: 'flag',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'form.request',
        h2Form: 'Request access',
        handleLabel: 'Name',
        handlePlaceholder: 'Jordan Reyes',
        handleHelp: 'As it should appear on the record.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within one business day.',
        districtLabel: 'Reason for access',
        district1: 'Low vision',
        district2: 'Bright-daylight use',
        district3: 'End-of-shift fatigue',
        district4: 'Other',
        whyLabel: 'Notes',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: "Wipe everything you've typed?",
        microlabelDossier: 'dossier.high-contrast',
        h2Dossier: 'The record, unredacted',
        cardTitle: 'Who this theme is for',
        stampLabel: 'On record',
        stampLabelOpen: 'On record',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: AAA',
        dossier1: 'This is the theme for someone who finds the other twenty-four too soft: ',
        dossierMark1: 'low vision',
        dossier2: ', ',
        dossierMark2: 'a screen in daylight',
        dossier3: ', or ',
        dossierMark3: 'tired eyes at the end of a shift',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Related themes',
        footerCol2a: 'Formal',
        footerCol2b: 'Light',
        footerCol2c: 'Blueprint',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    solstice: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Low Sun',
        brandTag: '',
        navThemes: 'Field guide',
        navThemes1: 'Palette & type',
        navThemes2: 'Try the form',
        navThemes3: 'Field notes',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Fields',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Get warm',
        sideNote: 'VOL. III · LOW SUN · 28°',
        band1: 'Firelight, not screenlight',
        band2: 'Warm dark at 28°',
        band3: '240 ms, the slowest fade',
        band4: 'Vol. III · Low Sun',
        laurel1b: 'No neon',
        laurel1: 'firelight only',
        laurel2b: 'Still legible',
        laurel2: 'every boundary holds',
        laurel3b: 'Unhurried',
        laurel3: '240ms, the slowest',
        microlabelHero: 'Firelight, not screenlight',
        headline: 'Warm dark, calibrated.',
        lede1: 'Solstice trades neon for firelight: an interface tuned like ',
        ledeMark1: "a print before it's fixed",
        lede2: ', where amber leads and rust follows, and ',
        ledeMark2: 'every boundary still holds its line',
        lede3: '.',
        btnPrimary: 'Open the field guide',
        btnSecondary: 'See the palette',
        btnGhost: 'Read the anatomy',
        platform1: 'macOS',
        platform2: 'Windows',
        platform3: 'the open web',
        platform4: 'Linux',
        spec1: 'ground',
        spec2: 'page',
        spec3: 'alert',
        spec4: 'rust',
        spec5: 'ember',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'request.notebook',
        h2Form: 'Try it warm',
        handleLabel: 'Name',
        handlePlaceholder: 'Your name',
        handleHelp: 'As it appears on the file.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We reply before the light changes.',
        districtLabel: 'Desk',
        district1: 'Editorial',
        district2: 'Field',
        district3: 'Archive',
        district4: 'Studio',
        whyLabel: 'Notes',
        whyPlaceholder: 'Two lines. Keep them warm.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.solstice-18',
        h2Dossier: 'Field notes, on record',
        cardTitle: 'Low Sun — Round Six',
        stampLabel: 'On file',
        stampLabelOpen: 'On file',
        dossierMeta: 'FILE 18 · STATUS: LIFT · REGISTER: SOLSTICE',
        dossier1: 'Solstice keeps its palette close: primary and accent are ',
        dossierMark1: 'the only pair in the set that share a hue family',
        dossier2: ', the radius is ',
        dossierMark2: 'the softest of the twenty-five',
        dossier3: ', and reduced motion still holds — ',
        dossierMark3: '240ms is the slowest resting duration of all eleven lifted themes',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the marks. They lift right to left, one after another, the way a page catches the last of the light.',
        dossierTrigger: 'Reveal the notes',
        footerTitle: 'Low Sun',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Solstice',
        footerCol2b: 'Sepia',
        footerCol2c: 'Dark',
        footerCol3: 'Elsewhere',
        footerCol3a: 'Documentation',
        footerCol3b: 'Changelog',
        footerCol3c: 'Source',
        footerFine: '/// theme: solstice · concept demo · round six lift · no images were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    sepia: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'the sepia specimen',
        navThemes: 'themes',
        navThemes1: 'formal',
        navThemes2: 'sepia',
        navThemes3: 'solstice',
        navComponents: 'components',
        navComponents1: 'buttons',
        navComponents2: 'forms',
        navComponents3: 'dossiers',
        navEffects: 'essays',
        navDocs: 'colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'reserve a copy',
        sideNote: 'every hue between 24° and 45°',
        band1: 'Every hue between 24° and 45°',
        band2: 'Long-form, not dashboards',
        band3: 'Set in Instrument Serif',
        band4: 'A page that has aged well',
        laurel1b: 'long-form',
        laurel1: 'not dashboards',
        laurel2b: '94 tokens',
        laurel2: 'at parity',
        laurel3b: '220ms',
        laurel3: 'the slowest fade in the set',
        microlabelHero: 'from the margin',
        headline: 'A page that has aged well.',
        lede1: 'Warm parchment, brown ink, and not one cool hue in the body. This is the only theme built for ',
        ledeMark1: 'long reading',
        lede2: " rather than for dashboards — restful in a way the others aren't, and ",
        ledeMark2: 'never in a hurry to prove it',
        lede3: '.',
        btnPrimary: 'reserve a copy',
        btnSecondary: 'read the specimen',
        btnGhost: 'preview a page',
        platform1: 'chromium',
        platform2: 'firefox',
        platform3: 'framework-free',
        platform4: 'react',
        spec1: 'paper #F6F1E9',
        spec2: 'ink #3B2816',
        spec3: 'sienna #7E4925',
        spec4: 'rule #A0856A',
        spec5: 'mark #EFDBC8',
        spec6: 'danger #9B3227',
        spec7: 'Instrument Serif, italic',
        spec8: 'Instrument Sans',
        microlabelForm: 'request.reading_copy',
        h2Form: 'Reserve a reading copy',
        handleLabel: 'name',
        handlePlaceholder: 'V. Night',
        handleHelp: 'Whatever name suits the copy.',
        mailLabel: 'email',
        mailPlaceholder: 'you@longreading.press',
        mailHelp: 'We answer eventually, and gladly.',
        districtLabel: 'edition',
        district1: 'reading copy — unbound',
        district2: 'library binding',
        district3: 'facsimile, numbered',
        district4: 'digital only',
        whyLabel: 'why this one',
        whyPlaceholder: "A line or two. There's no rush.",
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'send request',
        btnWipe: 'wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'specimen.sepia-09',
        h2Dossier: 'The specimen, on file',
        cardTitle: 'sepia',
        stampLabel: 'specimen — sepia',
        stampLabelOpen: 'specimen — sepia',
        dossierMeta: 'FILE 09 · STATUS: reference demo · ROUND SIX',
        dossier1: 'Cyberpunk shouts in ',
        dossierMark1: 'signal yellow on a void',
        dossier2: '; sepia ',
        dossierMark2: 'sits still and reads',
        dossier3: '. The palette holds to ',
        dossierMark3: 'one warm family, twenty-four to forty-five degrees',
        dossier4: ', and nothing here is trying to be seen from across the room.',
        dossierPara2:
            'Open the file to clear the redactions. Each bar lifts left to right, the way ink lifts off a page under a blade — not the way a curtain opens.',
        dossierTrigger: 'open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'registers',
        footerCol2a: 'cyberpunk',
        footerCol2b: 'synthwave',
        footerCol2c: 'retro',
        footerCol3: 'channels',
        footerCol3a: 'framework-free',
        footerCol3b: 'react',
        footerCol3c: 'home assistant',
        footerFine: 'Set in Instrument Serif and Instrument Sans · 94 tokens at parity · a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
    formal: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Fair Copy',
        brandTag: 'A kp-themes specimen',
        navThemes: 'Editions',
        navThemes1: 'The specimen sheet',
        navThemes2: 'Register two: sepia',
        navThemes3: 'Compare all 25',
        navComponents: 'Provenance',
        navComponents1: 'The lift plan',
        navComponents2: 'Research, 2026-09',
        navComponents3: 'Design invariants',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'NL',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'Fair Copy — specimen set, round six',
        band1: 'Fair Copy · specimen sixteen',
        band2: 'Vol. VI · round six',
        band3: 'A released theme never changes',
        band4: 'MMXXVI',
        laurel1b: 'Vol. VI',
        laurel1: 'round six',
        laurel2b: 'No. 016',
        laurel2: 'specimen sixteen',
        laurel3b: 'MMXXVI',
        laurel3: 'this year',
        microlabelHero: 'The formal register',
        headline: 'A promise set once, and unchanged.',
        lede1: 'Every theme in this package keeps its word: what shipped stays ',
        ledeMark1: 'exactly as it shipped',
        lede2: ', and a new idea becomes ',
        ledeMark2: 'a new version',
        lede3: ', never a silent edit.',
        btnPrimary: 'Request the specimen',
        btnSecondary: 'View the ledger',
        btnGhost: 'Read the promise',
        platform1: 'JobTracker',
        platform2: 'Almanac',
        platform3: 'kyu',
        platform4: 'kp-soft',
        spec1: 'Ground',
        spec2: 'Page',
        spec3: 'Brick',
        spec4: 'Bronze',
        spec5: 'Rust',
        spec6: 'Fraunces',
        spec7: 'Instrument Sans',
        spec8: 'System mono',
        microlabelForm: 'Intake — new correspondence',
        h2Form: 'Correspondence',
        handleLabel: 'Full name',
        handlePlaceholder: 'As it should appear in the ledger',
        handleHelp: 'The name on the specimen record.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'Where the specimen sheet is sent.',
        districtLabel: 'Department',
        district1: 'Editorial',
        district2: 'Production',
        district3: 'Rights',
        district4: 'Archive',
        whyLabel: 'Note',
        whyPlaceholder: 'Anything the desk should know.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit for review',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.fair-copy-016',
        h2Dossier: 'On file',
        cardTitle: 'Fair Copy',
        stampLabel: 'Draft — not for release',
        stampLabelOpen: 'Draft — not for release',
        dossierMeta: 'Dossier — draft 3',
        dossier1: 'Correspondence on file: ',
        dossierMark1: 'Applicant confirmed for the November review',
        dossier2: '. ',
        dossierMark2: 'Reference on file, dated 2026-08-11',
        dossier3: '. ',
        dossierMark3: 'Decision: proceed to the second register',
        dossier4: '.',
        dossierPara2:
            'Open the file to clear the redactions. They lift left to right, the way a redaction pen is dragged off a page — not all at once.',
        dossierTrigger: 'Reveal redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Consumers',
        footerCol2a: 'JobTracker',
        footerCol2b: 'Almanac',
        footerCol2c: 'kyu',
        footerCol3: 'Provenance',
        footerCol3a: 'Round six research',
        footerCol3b: 'Design invariants',
        footerCol3c: 'MIGRATION 5.0.0',
        footerFine: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
    dark: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: 'READY',
        brand: 'kp-themes',
        brandTag: 'SP·15',
        navThemes: 'Themes',
        navThemes1: 'Dark',
        navThemes2: 'Titanium',
        navThemes3: 'Phantom',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dialogs',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'SPECTRAL INSTRUMENT · GROUND AT 5% · ONE PALE SIGNAL',
        band1: 'Read the line',
        band2: '5% ground, 94% ink',
        band3: 'Colour only in the film',
        band4: 'Built to be looked at for hours',
        laurel1b: '5% ground, 94% ink',
        laurel1: 'a near-black instrument face, never pure black on pure white',
        laurel2b: 'One pale signal',
        laurel2: 'the interface is achromatic; every colour belongs to the oxide',
        laurel3b: 'DI5 safe',
        laurel3: 'every reveal is one change, or bound to your own scroll',
        microlabelHero: 'theme 15 · dark · spectral instrument',
        headline: 'An instrument reads the line, not the label.',
        lede1: 'A near-black face at 5% lightness, and a signal that is ',
        ledeMark1: 'almost white',
        lede2: ' rather than coloured — because on an instrument the reading is the bright thing and everything else gets out of its way. The colour that is here belongs to ',
        ledeMark2: 'the oxide film',
        lede3: ', which runs along an edge, under a heading and through a panel border, and shifts as the pointer moves the way interference really does.',
        btnPrimary: 'Take a reading',
        btnSecondary: 'See the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'face',
        spec3: 'hazard',
        spec4: 'film',
        spec5: 'edge',
        spec6: 'display',
        spec7: 'body',
        spec8: 'read',
        microlabelForm: 'access.instrument_handle',
        h2Form: 'Request an instrument handle',
        handleLabel: 'Operator name',
        handlePlaceholder: 'night shift',
        handleHelp: 'However you want the log to record the reading.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'Only used if a reading needs checking before the shift ends.',
        districtLabel: 'Reading window',
        district1: 'Just past midnight',
        district2: 'The small hours',
        district3: "Until it's light out",
        district4: 'No fixed hour',
        whyLabel: 'What you are measuring',
        whyPlaceholder: "Two lines. That's plenty.",
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Save the handle',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'This clears every field above. It cannot be undone.',
        microlabelDossier: 'log.kp-themes-15',
        h2Dossier: 'The register, on record',
        cardTitle: 'Dark',
        stampLabel: 'Reading 15',
        // invented: the demo's stamp never swaps its label; "Read" is
        // written in its own voice for the dossier's open state.
        stampLabelOpen: 'Read',
        dossierMeta: 'FILE 15 · STATUS: PREVIEW · READ AT: NIGHT',
        dossier1: 'The theme that replaced the old dark outright. The face sits at 5% lightness with a blue cast, ',
        dossierMark1: 'never true black',
        dossier2: '. The signal is a pale near-white, so the interface itself carries no hue and the one coloured thing on the page is ',
        dossierMark2: 'the film',
        dossier3: '. It runs along a control under the pointer, closes two brackets on a label, and turns as your hand does — because that is ',
        dossierMark3: 'what interference does',
        dossier4: '.',
        // invented: the demo's dossier carries one paragraph; this second
        // one is written in its voice, the way every other theme's own
        // second paragraph explains what the trigger does.
        dossierPara2:
            'Open the log to clear the redactions. They lift right to left, one after another, the way a line settles once you have read enough of it to trust it.',
        dossierTrigger: 'Open the log',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-six themes, twenty-six registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Dark',
        footerCol2b: 'Titanium',
        footerCol2c: 'Phantom',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 6.0.0-preview · 96 tokens, one near-black face · no hearts were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    titanium: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: 'PART 26',
        brand: 'kp-themes',
        brandTag: 'TI·26',
        navThemes: 'Themes',
        navThemes1: 'Titanium',
        navThemes2: 'Dark',
        navThemes3: 'Blueprint',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dialogs',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'ANODISED TITANIUM · CARBON TWILL · 60MS, LINEAR',
        band1: 'Not a place, a material',
        band2: '10% ground, 94% ink',
        band3: 'The colour has a cause',
        band4: 'Metal does not ease',
        laurel1b: 'The colour has a cause',
        laurel1: 'anodising grows an oxide film; the thickness decides the wavelength',
        laurel2b: 'Sixty milliseconds',
        laurel2: 'linear, because an eased curve is the signature of something with give',
        laurel3b: 'DI5 safe',
        laurel3: 'every reveal is one change, or bound to your own scroll',
        microlabelHero: 'theme 26 · titanium · anodised',
        headline: 'The colour is not paint. It is thickness.',
        lede1: 'Anodising adds no pigment. It grows an oxide film, and the ',
        ledeMark1: 'thickness of that film',
        lede2: ' decides which wavelength survives — so the blue-violet on every edge here really is interference, and it really does shift with the angle you look from. Underneath it, ',
        ledeMark2: 'carbon twill',
        lede3: ': two diagonals crossing, the weave of the cloth the part was laid up on.',
        btnPrimary: 'See the part',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'face',
        spec3: 'hazard',
        spec4: 'oxide',
        spec5: 'edge',
        spec6: 'display',
        spec7: 'body',
        spec8: 'read',
        microlabelForm: 'access.part_record',
        h2Form: 'Open a part record',
        handleLabel: 'Machinist',
        handlePlaceholder: 'second shift',
        handleHelp: 'However you want the record to name the hand that cut it.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'Only used if a tolerance needs checking before the part ships.',
        districtLabel: 'Finish',
        district1: 'Anodised, natural',
        district2: 'Anodised, struck',
        district3: 'Bead blast',
        district4: 'As machined',
        whyLabel: 'What it is for',
        whyPlaceholder: "Two lines. That's plenty.",
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Save the record',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'This clears every field above. It cannot be undone.',
        microlabelDossier: 'record.kp-themes-26',
        h2Dossier: 'The material, on record',
        cardTitle: 'Titanium',
        stampLabel: 'Part 26',
        // invented: the demo's stamp never swaps its label; "Read" is
        // written in its own voice for the dossier's open state.
        stampLabelOpen: 'Open',
        dossierMeta: 'PART 26 · STATUS: PREVIEW · FINISH: ANODISED',
        dossier1:
            'The round opened asking for a theme called hypertech — a category, defined by an empty place on the colour wheel — and it cost six refused worlds before the answer turned out to be ',
        dossierMark1: 'a material',
        dossier2: ', which is how every theme here is named. Retro is the desktop, blueprint is the drawing, lapis is the stone. The corner is ',
        dossierMark2: 'cut, never rounded',
        dossier3: ', with a bright line along the top where the tool left the face, and a press drops the whole control one pixel because metal has ',
        dossierMark3: 'no give',
        dossier4: '.',
        // invented: the demo's dossier carries one paragraph; this second
        // one is written in its voice, the way every other theme's own
        // second paragraph explains what the trigger does.
        dossierPara2:
            'Open the log to clear the redactions. They lift right to left, one after another, the way a line settles once you have read enough of it to trust it.',
        dossierTrigger: 'Open the record',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-six themes, twenty-six registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Titanium',
        footerCol2b: 'Dark',
        footerCol2c: 'Blueprint',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 6.0.0-preview · 96 tokens, anodised over twill · no hearts were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    nostromo: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: 'REG//19',
        navThemes: 'Manifest',
        navThemes1: 'Signal',
        navThemes2: 'Synthwave',
        navThemes3: 'Nostromo',
        navComponents: 'Systems',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Signals',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'REG 19 · DECK B · SN 044-7',
        band1: 'DECK B · SN 044-7',
        band2: 'REG 19 · CARGO MANIFEST',
        band3: 'BUILT LIKE THE CASE',
        band4: 'NO FLICKER',
        laurel1b: 'The case, not the screen',
        laurel1: 'the thesis',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing, no flicker',
        microlabelHero: 'register 19 · preview build',
        headline: 'Built like the case, not the screen.',
        lede1: 'Warm-grey plastic, thirty years of yellowing, and one orange LED that never blinks. ',
        ledeMark1: 'Ink acts',
        lede2: '. ',
        ledeMark2: 'Orange indicates',
        lede3: '. A cassette-futurism register for kp-themes, working panel first.',
        btnPrimary: 'Open the panel',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'plate',
        spec3: 'ink',
        spec4: 'signal',
        spec5: 'LED',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'cargo.manifest_form',
        h2Form: 'Request a berth',
        handleLabel: 'Callsign',
        handlePlaceholder: 'ripley.8',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@freight.co',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'Deck',
        district1: 'Bridge',
        district2: 'Mid-deck',
        district3: 'Hold',
        district4: 'Engineering',
        whyLabel: 'Cargo notes',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Log it',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.kp-themes-19',
        h2Dossier: 'The panel, on file',
        cardTitle: 'The Case',
        stampLabel: 'Sealed',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 19 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A nineteenth theme for kp-themes, built as cassette futurism: ',
        dossierMark1: 'warm beige plastic',
        dossier2: ', ',
        dossierMark2: 'one orange LED that never blinks',
        dossier3: ', and ',
        dossierMark3: 'label tape for every plate',
        dossier4: '. Every panel is a token, and every token ships in all twenty-five themes.',
        dossierPara2: 'Open the panel to clear the redactions. They lift together, the way label tape peels — one motion, not a flicker.',
        dossierTrigger: 'Open the panel',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Signal',
        footerCol2b: 'Synthwave',
        footerCol2c: 'Nostromo',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    blueprint: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: '/ blueprint',
        navThemes: 'Sheets',
        navThemes1: 'Elevations',
        navThemes2: 'Sections',
        navThemes3: 'Details',
        navComponents: 'Legend',
        navComponents1: 'Line weights',
        navComponents2: 'Annotations',
        navComponents3: 'Symbols',
        navEffects: 'Symbols',
        navDocs: 'Request',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request a set',
        sideNote: 'SHEET 07 · SCALE 1:1 · REV C · 0x1F',
        band1: 'SHEET 07 · SCALE 1:1',
        band2: 'REV C',
        band3: 'DRAWN FROM TOKENS',
        band4: 'NOTHING HERE LOOPS',
        laurel1b: "Vercel's crosshair",
        laurel1: 'grid intersections, not decoration',
        laurel2b: '96 tokens',
        laurel2: 'one register, nothing hidden',
        laurel3b: 'DI5 clear',
        laurel3: 'nothing here loops or flickers',
        microlabelHero: 'SHEET 07 · BLUEPRINT · REV C',
        headline: 'Draw it before you build it.',
        lede1: "Cyan ink on Prussian blue, ruled like a drawing that hasn't been built yet. Nothing is rendered ",
        ledeMark1: "until it's dimensioned",
        lede2: ', and nothing ships ',
        ledeMark2: 'without a boundary you can see',
        lede3: '.',
        btnPrimary: 'Open the drawing set',
        btnSecondary: 'Read the annotations',
        btnGhost: 'View the sheet index',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'ground',
        spec3: 'alert',
        spec4: 'annotation',
        spec5: 'detail',
        spec6: 'display',
        spec7: 'text',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a print',
        handleLabel: 'Drawing number',
        handlePlaceholder: 'DWG-2031-A',
        handleHelp: 'The reference this print is filed under.',
        mailLabel: 'Contact',
        mailPlaceholder: 'drafting@studio.blue',
        mailHelp: 'We answer within one revision cycle.',
        districtLabel: 'Sheet size',
        district1: 'A4',
        district2: 'A3',
        district3: 'A1',
        district4: 'Custom',
        whyLabel: 'Notes',
        whyPlaceholder: 'Annotations go here, one line per revision.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit for review',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.blueprint-07',
        h2Dossier: 'The sheet, on file',
        cardTitle: 'Blueprint',
        stampLabel: 'Approved for construction',
        stampLabelOpen: 'As built',
        dossierMeta: 'FILE 07 · STATUS: DRAFT · CLEARANCE: KENNY',
        dossier1: 'The seventh theme lifted for 5.0.0. Where cyberpunk is ',
        dossierMark1: 'a dark blue theme that glows',
        dossier2: ', this one is ',
        dossierMark2: 'a dark blue theme that measures',
        dossier3: ', drawn from ',
        dossierMark3: 'ninety-six tokens, nothing hidden',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, on request — not all at once.',
        dossierTrigger: 'Lift the redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Legend',
        footerCol2a: 'Line weights',
        footerCol2b: 'Annotations',
        footerCol2c: '96 tokens',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// SHEET 07 · DRAWN FROM TOKENS · NO PHOTOGRAPHS WERE TAKEN',
        arrivalLine: '',
        arrivalReady: '',
    },
    grotesk: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Grotesk',
        brandTag: '',
        navThemes: 'Type',
        navThemes1: 'Weights',
        navThemes2: 'Grid',
        navThemes3: 'Specimen',
        navComponents: 'System',
        navComponents1: 'Tokens',
        navComponents2: 'Components',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'BASEL · MOD. 12 · REV. 03',
        band1: 'BASEL · MOD. 12',
        band2: 'TWELVE COLUMNS, ONE RED',
        band3: 'IDENTITY BY LETTER',
        band4: 'REV. 03',
        laurel1b: '“Identity by letter, not colour”',
        laurel1: 'the brief',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'grotesk · concept demo',
        headline: 'Twelve columns, one red, no noise.',
        lede1: 'Grotesk is the International Typographic Style built for interfaces: flush-left type, oversized headings and one ',
        ledeMark1: 'signal red',
        lede2: ' that never competes with black. Colour is not the identity here — ',
        ledeMark2: 'the grid is',
        lede3: '.',
        btnPrimary: 'View the grid',
        btnSecondary: 'Read the manual',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'ground',
        spec3: 'alarm',
        spec4: 'ink',
        spec5: 'info',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'system.request_form',
        h2Form: 'Request an environment',
        handleLabel: 'Handle',
        handlePlaceholder: 'j.muller-brockmann',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@basel.ch',
        mailHelp: 'We answer within one working day.',
        districtLabel: 'Studio',
        district1: 'Basel',
        district2: 'Zurich',
        district3: 'Ulm',
        district4: 'Amsterdam',
        whyLabel: 'Brief',
        whyPlaceholder: 'Two lines. Set them flush left.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.grotesk-12',
        h2Dossier: 'The grid, on record',
        cardTitle: 'Grotesk',
        stampLabel: 'Restricted · Rev. 03',
        stampLabelOpen: 'Cleared · Rev. 03',
        dossierMeta: 'FILE 12 · STATUS: CONCEPT · CLEARANCE: KENNY',
        dossier1: 'The type style is ',
        dossierMark1: 'Helvetica-class, set at 800 for headings',
        dossier2: ', the grid is ',
        dossierMark2: 'twelve columns, ink at four percent',
        dossier3: ', and the identity is carried by ',
        dossierMark3: 'letterform and grid, never by a second hue',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. Each one cuts away in three steps — not a fade, a decision.',
        dossierTrigger: 'Open the file',
        footerTitle: 'Grotesk',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Grid',
        footerCol2a: 'Columns',
        footerCol2b: 'Type scale',
        footerCol2c: 'Tokens',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    light: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        brandTag: '',
        navThemes: 'Themes',
        navThemes1: 'Light',
        navThemes2: 'Pastel',
        navThemes3: 'Formal',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'THEME 22 · WHITE GROUND · NO ORNAMENT',
        band1: 'THEME 22 · WHITE GROUND',
        band2: '17.2:1 BODY ON GROUND',
        band3: 'NO ORNAMENT',
        band4: 'THIS THEME CUTS NO CORNERS',
        laurel1b: '17.2:1',
        laurel1: 'body on ground',
        laurel2b: '94 tokens',
        laurel2: 'declared, no exceptions',
        laurel3b: '0px',
        laurel3: 'corner notch — this theme cuts no corners',
        microlabelHero: 'theme 22 of 25 · restraint, chosen on purpose',
        headline: 'White isn’t neutral. It’s a decision.',
        lede1: 'Pure white ground, near-black ink, and one indigo that ',
        ledeMark1: 'never apologizes',
        lede2: '. No texture, no display face — just the words, ',
        ledeMark2: 'in focus',
        lede3: '.',
        btnPrimary: 'See the spec sheet',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'ink',
        spec3: 'signal',
        spec4: 'label',
        spec5: 'fx',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Say what you need',
        handleLabel: 'Name',
        handlePlaceholder: 'Your name',
        handleHelp: 'Two words is plenty.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within a day.',
        districtLabel: 'Where do you work',
        district1: 'Design',
        district2: 'Engineering',
        district3: 'Product',
        district4: 'Other',
        whyLabel: 'Anything else',
        whyPlaceholder: 'Two lines is plenty.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.light-22',
        h2Dossier: 'The record, reviewed',
        cardTitle: 'Light',
        stampLabel: 'Reviewed',
        stampLabelOpen: 'Open',
        dossierMeta: 'FILE 22 · STATUS: SHIPPED · CLEARANCE: OPEN',
        dossier1: 'This theme carries ',
        dossierMark1: 'no texture',
        dossier2: ', ',
        dossierMark2: 'no display face',
        dossier3: ' and ',
        dossierMark3: 'no second accent',
        dossier4: '. Everything you see is the content, on a ground that stays exactly white.',
        dossierPara2:
            'Open the file to clear the redactions. They lift one after another, the way a document does when the clearance comes through — not all at once.',
        dossierTrigger: 'Reveal the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Light',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
    deco: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Aurelia',
        brandTag: 'REG//08',
        navThemes: 'Suites',
        navThemes1: 'Penthouse',
        navThemes2: 'Corner Suite',
        navThemes3: 'Garden Suite',
        navComponents: 'Ateliers',
        navComponents1: "Jewellers' Row",
        navComponents2: 'The Print Room',
        navComponents3: 'Silver Bar',
        navEffects: 'Bulletin',
        navDocs: 'Concierge',
        navLang: 'EN',
        navLang1: 'FR — Français',
        navLang2: 'NL — Nederlands',
        navCta: 'Reserve a suite',
        sideNote: 'TOWER XLI · MERIDIAN AVENUE · MCMXXVIII',
        band1: 'TOWER XLI · MERIDIAN AVENUE',
        band2: 'MCMXXVIII',
        band3: 'DRAWN WITH A RULER',
        band4: 'ONE GESTURE, NO FLASHING',
        laurel1b: 'DI1 clear',
        laurel1: 'boundary at 6.1:1',
        laurel2b: 'DI2 two-channel',
        laurel2: 'the ring never disappears',
        laurel3b: 'DI5 safe',
        laurel3: 'one gesture, no flashing',
        microlabelHero: 'register 08 · concept demo',
        headline: 'Drawn with a ruler, not a filter.',
        lede1: 'Gold is the structure, not the sparkle: ',
        ledeMark1: 'no metallic gradient',
        lede2: ', no soft edge. Every rule is compass-drawn, and ',
        ledeMark2: 'every corner is cut on purpose',
        lede3: '.',
        btnPrimary: 'Enter the lobby',
        btnSecondary: 'Read the terms',
        btnGhost: 'House rules',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'Hero ground',
        spec2: 'Page ground',
        spec3: 'Ruby',
        spec4: 'Emerald',
        spec5: 'Chart accent',
        spec6: 'Display',
        spec7: 'Body',
        spec8: 'Mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a key',
        handleLabel: 'Name',
        handlePlaceholder: 'V. Ashworth',
        handleHelp: 'As it appears on the reservation.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@aurelia.example',
        mailHelp: 'We reply within one business day.',
        districtLabel: 'Suite',
        district1: 'Penthouse',
        district2: 'Corner Suite',
        district3: 'Garden Suite',
        district4: 'Terrace Suite',
        whyLabel: 'Occasion',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Reserve',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'Wipe it clean?',
        microlabelDossier: 'dossier.aurelia-08',
        h2Dossier: 'The house, on record',
        cardTitle: 'Aurelia',
        stampLabel: 'Classified',
        stampLabelOpen: 'Classified',
        dossierMeta: 'FILE 08 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'Reserved under ',
        dossierMark1: 'Aurelia & Co.',
        dossier2: ', suite ',
        dossierMark2: 'Penthouse 41',
        dossier3: ', at a rate of ',
        dossierMark3: '$4,200 / night',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the jewel plates. They lift together, gold cut from gold, once you ask.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Deco',
        footerCol2b: 'Synthwave',
        footerCol2c: 'Cyberpunk',
        footerCol3: 'House rules',
        footerCol3a: 'Accessibility',
        footerCol3b: 'Terms',
        footerCol3c: 'Contact',
        footerFine:
            'Twenty-five themes, twenty-five registers, one promise: a released theme never changes. /// deco · register 08 · rendered from tokens · no images were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    forest: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'kp-themes',
        // invented: the demo's brand carries no file code; RDG//12 fits its side note's "RIDGE-12".
        brandTag: 'RDG//12',
        navThemes: 'Trails',
        navThemes1: 'Ridge Loop',
        navThemes2: 'Basin Crossing',
        navThemes3: 'Coastal Spur',
        navComponents: 'Guides',
        navComponents1: 'Packing list',
        navComponents2: 'Permits',
        navComponents3: 'Weather',
        navEffects: 'Elevation',
        navDocs: 'Field notes',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Get a permit',
        sideNote: 'N 47° · RIDGE-12 · +840M',
        band1: 'RIDGE-12 · +840M',
        band2: 'N 47° · CONTOUR 20 M',
        band3: 'BEARING 118°',
        band4: 'SURVEYED FROM TOKENS',
        laurel1b: '94 tokens',
        laurel1: 'parity gate',
        laurel2b: 'DI1 boundaries',
        laurel2: '3:1 everywhere',
        laurel3b: 'Contour, not clipart',
        laurel3: 'the signature',
        microlabelHero: 'field station · build preview',
        headline: 'Read the ground before you walk it.',
        lede1: 'Kraft paper, forest ink, a clay trail. Contour lines wander ',
        ledeMark1: 'at a felt, not seen opacity',
        lede2: ', and the only colour that ',
        ledeMark2: 'acts',
        lede3: ' is the forest green.',
        btnPrimary: 'Plan a route',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'kraft',
        spec3: 'alert',
        spec4: 'clay',
        spec5: 'moss',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.permit_request',
        h2Form: 'Request a trail permit',
        handleLabel: 'Name',
        handlePlaceholder: 'J. Ranger',
        // invented: the demo's name field carries no help text.
        handleHelp: 'First initial, last name.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@fieldstation.org',
        mailHelp: 'We answer within one business day.',
        districtLabel: 'Trail',
        district1: 'Ridge Loop',
        district2: 'Basin Crossing',
        district3: 'Coastal Spur',
        district4: 'Backcountry (permit required)',
        whyLabel: 'Notes for the ranger',
        whyPlaceholder: 'Party size, expected return time.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit permit request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.ridge-12',
        h2Dossier: 'The ridge, on record',
        cardTitle: 'Survey notes — Ridge 12',
        stampLabel: 'Field copy',
        stampLabelOpen: 'Field copy',
        dossierMeta: 'FILE T-12 · STATUS: ARCHIVED · SURVEYOR: KP',
        dossier1: 'The trail crosses ',
        dossierMark1: 'private land at the north fence',
        dossier2: ' before the switchback, and the spring at ',
        dossierMark2: '400m east of marker 7',
        dossier3: ' runs dry after August. Permits close once ',
        dossierMark3: 'the station logs three no-shows',
        dossier4: '.',
        dossierPara2:
            'Clear the file to read the notes. They lift one after another, the way a survey does when a second pass confirms the first — not all at once.',
        dossierTrigger: 'Clear the redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Trails',
        footerCol2a: 'Ridge Loop',
        footerCol2b: 'Basin Crossing',
        footerCol2c: 'Coastal Spur',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-ALPHA · RENDERED FROM TOKENS · NO SUMMITS WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    'shade-light': {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Quiet Margin',
        brandTag: 'SL//094',
        navThemes: 'Reading',
        navThemes1: 'Essays',
        navThemes2: 'Marginalia',
        navThemes3: 'Reading lists',
        navComponents: 'Library',
        navComponents1: 'Collections',
        navComponents2: 'Annotations',
        navComponents3: 'Archive',
        navEffects: 'Anatomy',
        navDocs: 'Token sheet',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Start reading',
        sideNote: 'Marginal note — shade-light, the light half of a mirrored pair',
        band1: 'Shelf SL-094 · on loan',
        band2: 'Solarized, the light half',
        band3: 'Medium contrast, by design',
        band4: 'Due Tuesday',
        laurel1b: 'Solarized',
        laurel1: 'the source scheme',
        laurel2b: 'AA',
        laurel2: 'medium contrast, by design',
        laurel3b: '94',
        laurel3: 'tokens, one contract',
        microlabelHero: 'Concept demo — shade-light',
        headline: 'A book read in the shade, not in the sun.',
        lede1: 'Warm paper, a blue-grey ink that stops well short of black, and accents that stay ',
        ledeMark1: 'plates, never words',
        lede2: '. Every boundary holds 3:1, every line of body copy holds ',
        ledeMark2: 'at least 4.5:1',
        lede3: ', and nothing on the page moves more than once.',
        btnPrimary: 'Open the library',
        btnSecondary: 'See the token sheet',
        btnGhost: 'Read the anatomy →',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'ground',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'chart',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'Correspondence',
        h2Form: 'Request a reading copy',
        handleLabel: 'Name',
        handlePlaceholder: 'Kenny P.',
        handleHelp: 'As it should appear on the shelf card.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We reply within a week.',
        districtLabel: 'Shelf',
        district1: 'Essays',
        district2: 'Field notes',
        district3: 'Marginalia',
        district4: 'Reading lists',
        whyLabel: 'Note to the margin',
        whyPlaceholder: 'Two lines. Say why this one matters.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.shade-light-06',
        h2Dossier: 'The margin, on record',
        cardTitle: 'Quiet Margin',
        stampLabel: "Reviewer's copy",
        stampLabelOpen: 'Cleared',
        dossierMeta: 'SHELF SL-094 · STATUS: ON LOAN · DUE: TUESDAY',
        dossier1: 'Held by ',
        dossierMark1: 'Kenny P.',
        dossier2: ', shelf mark ',
        dossierMark2: 'SL-094-A',
        dossier3: ', due back ',
        dossierMark3: 'Tuesday',
        dossier4: '.',
        dossierPara2:
            "Open the file to clear the redactions. They lift one after another, the way a reviewer's copy is checked out — not all at once.",
        dossierTrigger: 'Reveal redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Theme',
        footerCol2a: 'Anatomy',
        footerCol2b: 'Token sheet',
        footerCol2c: 'shade-dark, the mirror',
        footerCol3: 'Package',
        footerCol3a: 'Documentation',
        footerCol3b: 'Changelog',
        footerCol3c: 'Migration notes',
        footerFine: '94 tokens. Source Sans 3 and Source Serif 4, SIL OFL 1.1, via Google Fonts.',
        arrivalLine: '',
        arrivalReady: '',
    },
    pastel: {
        // The small reading above the primary control [readout-words, Kenny 2026-09-12].
        // Empty where this theme's register does not style the surface.
        readout: '',
        brand: 'Milkweed Press',
        brandTag: 'Riso & letterpress studio',
        navThemes: 'Work',
        navThemes1: 'Posters',
        navThemes2: 'Zines',
        navThemes3: 'Risograph runs',
        navComponents: 'Studio',
        navComponents1: 'The drums',
        navComponents2: 'Paper stock',
        navComponents3: 'Visit',
        navEffects: 'Journal',
        navDocs: 'Notes',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Book a slot',
        sideNote: 'Press proof — run 003',
        band1: 'Milkweed Press · run 003',
        band2: 'Two-colour pass',
        band3: 'Ink that never quite lines up',
        band4: 'Small batch, every run',
        laurel1b: 'Est. 2019',
        laurel1: 'the studio',
        laurel2b: 'Riso certified',
        laurel2: 'the process',
        laurel3b: 'Small batch',
        laurel3: 'every run',
        microlabelHero: 'Two-colour pass',
        headline: 'Ink that never quite lines up.',
        lede1: 'Every poster runs through the drum twice: once in plum, once in ',
        ledeMark1: 'mint',
        lede2: '. The overlap is the point, not the ',
        ledeMark2: 'mistake',
        lede3: '.',
        btnPrimary: 'Book the drum',
        btnSecondary: 'See the run sheet',
        btnGhost: 'Read the notes',
        platform1: 'Riso GR3770',
        platform2: 'Riso GR2750',
        platform3: 'Offset proof',
        platform4: 'PDF/X-1a',
        spec1: 'ground',
        spec2: 'paper',
        spec3: 'rose',
        spec4: 'mint',
        spec5: 'amber',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'press.run_004',
        h2Form: 'Send it to press',
        handleLabel: 'Name',
        handlePlaceholder: 'Kenny',
        handleHelp: 'Whoever signs off the run.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@milkweedpress.nl',
        mailHelp: 'We answer within one pass.',
        districtLabel: 'Paper stock',
        district1: 'Milk white, 120gsm',
        district2: 'Oyster, 160gsm',
        district3: 'Kraft, 100gsm',
        district4: 'Recycled, 100gsm',
        whyLabel: 'Notes for the drum',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send to press',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'Wipe everything on this form?',
        microlabelDossier: 'proof.kp-themes-06',
        h2Dossier: 'The run, on record',
        cardTitle: 'Proof',
        stampLabel: 'Proof approved',
        stampLabelOpen: 'Proof opened',
        dossierMeta: 'PROOF #003 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'Second pass registers ',
        dossierMark1: '2px low and 2px right',
        dossier2: ' on the standing plum plate. The mint drum needs ',
        dossierMark2: 'a 40-sheet warm-up',
        dossier3: ' before colour holds true, and run 004 moves to ',
        dossierMark3: 'the 160gsm oyster stock',
        dossier4: ', Kenny’s call.',
        dossierPara2:
            'Open the file to lift the redactions. They clear one after another, staggered like the drum settling into register — not all at once.',
        dossierTrigger: 'Reveal the proof notes',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, twenty-five registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Pastel',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 5.0.0-preview · rendered from tokens · every ink a var()',
        arrivalLine: '',
        arrivalReady: '',
    },
};

/** The theme the picker page and every page without its own copy shows. */
export const DEFAULT_COPY_THEME = 'cyberpunk';

/** The themes that carry their own words, in the order they were lifted. */
export const COPY_THEMES = Object.keys(CONCEPT_COPY);

/**
 * The copy a page is rendered with.
 *
 * @param {string} [theme]
 * @returns {ConceptCopy}
 */
export function conceptCopy(theme) {
    return CONCEPT_COPY[theme ?? DEFAULT_COPY_THEME] ?? CONCEPT_COPY[DEFAULT_COPY_THEME];
}
