// The concept page's words, per theme [S49, A1 of 2026-09-08].
//
// One approved concept demo per theme (S46), and Kenny's rule is that a
// demo is implemented exactly — "voor de rest moet het gewoon zo
// geimplementeerd worden voor alle tokens/elementen" (2026-09-08, S49).
// Until this file existed, examples/concept.html carried cyberpunk's
// words under every theme: phantom's calling card said "Stop looking
// like a theme", retro's desktop booted a neural uplink. The structure
// and the markers are the same for every theme (S46, KT11); only the
// words change, and they are the words of that theme's own demo.
//
// Every entry has the same slots, which is what makes the pages
// comparable: gates/gates.test.mjs holds the shape and refuses a theme
// whose entry is missing one. `cyberpunk` is the default the picker page
// shows; a theme with no entry here shows that default, which is the
// honest state for a theme whose demo has not been built yet.

/** @typedef {Record<string, string>} ConceptCopy */

/** @type {Record<string, ConceptCopy>} */
export const CONCEPT_COPY = {
    cyberpunk: {
        brand: 'kp-themes',
        brandTag: 'SIG//06',
        navThemes: 'Themes',
        navThemes1: 'Signal',
        navThemes2: 'Synthwave',
        navThemes3: 'Nostromo',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NC · 2077 · SECTOR 06 · 0x1F',
        laurel1b: '“Spits off the screen”',
        laurel1: 'the brief',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'register 02 · preview build',
        headline: 'Stop looking like a theme.',
        lede1: 'Signal yellow on void. Blood red ',
        ledeMark1: 'where it counts',
        lede2: '. Neon only ',
        ledeMark2: 'where it hurts',
        lede3: '. A cyberpunk register for kp-themes that behaves like a place, not a palette.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'label',
        spec5: 'glitch',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@dogtown.nc',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'District',
        district1: 'Watson',
        district2: 'Westbrook',
        district3: 'Santo Domingo',
        district4: 'Dogtown',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this register ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.kp-themes-06',
        h2Dossier: 'The register, on record',
        cardTitle: 'Signal',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A second cyberpunk register for kp-themes. The first one was ',
        dossierMark1: 'violet night and magenta',
        dossier2: '; this one is built on ',
        dossierMark2: 'signal yellow and blood red',
        dossier3: ', with cyan for what must be read and violet only inside a glitch. Every effect is ',
        dossierMark3: 'opt-in and reduced-motion safe',
        dossier4: ', and the old register stays exactly as shipped.',
        dossierPara2:
            'Open the file to clear the redactions. They lift one after another, the way a document does when the clearance comes through — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, six registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Signal',
        footerCol2b: 'Cyberpunk (archived)',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '▶ Calibrating neural uplink',
        arrivalReady: 'OK',
    },
    phantom: {
        brand: 'kp-themes',
        brandTag: 'PH//15',
        navThemes: 'Themes',
        navThemes1: 'Phantom',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Case files',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'FILE 15 · CUT PAPER · NO GLOW',
        laurel1b: '“Energy without light”',
        laurel1: 'the anatomy',
        laurel2b: 'Three colours',
        laurel2: 'black, white, one red',
        laurel3b: 'DI5 safe',
        laurel3: 'every gesture a transform',
        microlabelHero: 'theme 15 · preview build',
        headline: 'We are taking your interface.',
        lede1: 'Cut paper, not glass. A halftone screen ',
        ledeMark1: 'where it prints',
        lede2: ', one violent red ',
        ledeMark2: 'where it cuts',
        lede3: ', and condensed italic capitals doing the shouting. A phantom theme for kp-themes that behaves like a heist, not a palette.',
        btnPrimary: 'Send the card',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'void #0A0A0A',
        spec2: 'void #0A0A0A',
        spec3: 'yellow #FFC61A',
        spec4: 'grey #ADADAD',
        spec5: 'red #FF293B',
        spec6: 'Barlow Condensed 800 italic',
        spec7: 'Barlow 400–700',
        spec8: 'system ui-monospace',
        microlabelForm: 'access.calling_card',
        h2Form: 'Request a codename',
        handleLabel: 'Codename',
        handlePlaceholder: 'joker',
        handleHelp: 'Lowercase, no spaces. One word is enough.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@phantom.example',
        mailHelp: 'We answer before the deadline you did not set.',
        districtLabel: 'Target',
        district1: 'The navigation',
        district2: 'The empty state',
        district3: 'The settings screen',
        district4: 'All of it',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the card',
        btnWipe: 'Burn the card',
        wipeConfirm: 'Burn it — sure?',
        microlabelDossier: 'case_file.kp-themes-15',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Phantom',
        stampLabel: 'Calling card',
        stampLabelOpen: 'Card read',
        dossierMeta: 'FILE 15 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phantom theme for kp-themes. Cyberpunk emits light; this one is ',
        dossierMark1: 'print, not screen',
        dossier2: '. The red is ',
        dossierMark2: 'a plate, never a word',
        dossier3: ', the headings are condensed italic capitals, and every gesture is ',
        dossierMark3: 'a transform or a clip-path',
        dossier4: ', which is why the flash threshold never enters.',
        dossierPara2:
            'Open the file to lift the censor plates. They shear off one after another, right edge first, the way a page is torn rather than faded.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-four themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Phantom',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '▮ Build 5.0.0-preview · cut from tokens · no hearts were harmed',
        arrivalLine: 'Phantom',
        arrivalReady: 'Delivered.',
    },
    retro: {
        brand: 'kp-themes 95',
        brandTag: '— [Retro]',
        navThemes: 'Themes',
        navThemes1: 'Retro',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Fields',
        navComponents3: 'Windows',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'SYSTEM PROPERTIES · BUILD 95 · READY',
        laurel1b: 'Chrome you can press',
        laurel1: 'the brief',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 ms',
        laurel3: 'every transition',
        microlabelHero: 'C:\\KP\\THEMES\\RETRO> theme 03 · preview build',
        headline: 'Press it. It goes down.',
        lede1: 'Mid-grey chrome, a navy title bar, and an edge you can point at. Bevels ',
        ledeMark1: 'where you press',
        lede2: '. Wells ',
        ledeMark2: 'where you type',
        lede3: '. A retro theme for kp-themes that behaves like a desktop, not a filter.',
        btnPrimary: 'Open the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Help',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'window',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'title',
        spec6: 'display',
        spec7: 'body',
        spec8: 'dos',
        microlabelForm: 'C:\\KP\\ACCESS> request.exe',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'user95',
        handleHelp: 'Eight characters, no spaces. It was 1995.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@lan.local',
        mailHelp: 'We answer before the modem finishes.',
        districtLabel: 'Workgroup',
        district1: 'WORKGROUP',
        district2: 'LAB',
        district3: 'NIGHTSHIFT',
        district4: 'DIALUP',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — are you sure?',
        microlabelDossier: 'C:\\KP\\DOCS> type dossier.txt',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Retro',
        stampLabel: 'READ ONLY',
        stampLabelOpen: 'READ/WRITE',
        dossierMeta: 'FILE 03 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A 1995 desktop for kp-themes. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'square and grey',
        dossier3: ': every control a bevel, every field a well, every edge a real boundary at ',
        dossierMark3: '3.31 on the chrome',
        dossier4: '. Nothing here eases, blinks or scrolls by itself.',
        dossierPara2:
            'Open the file to lift the dither. The brush comes off one block at a time, left to right, the way a 1995 screen actually repainted — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Retro',
        footerCol2b: 'Signal',
        footerCol2c: 'Synthwave',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 5.0.0-preview · rendered from tokens · 0 bytes of images',
        arrivalLine: 'KP Modular BIOS v4.51PG · kp-themes 95 — retro build · Memory Test : 0K',
        arrivalReady: 'OK',
    },
    terminal: {
        brand: 'kp-themes',
        brandTag: 'TTY//06',
        navThemes: 'themes',
        navThemes1: 'signal',
        navThemes2: 'synthwave',
        navThemes3: 'terminal',
        navComponents: 'components',
        navComponents1: 'buttons',
        navComponents2: 'forms',
        navComponents3: 'dossiers',
        navEffects: 'effects',
        navDocs: 'man',
        navLang: 'LANG=EN',
        navLang1: 'nl_NL',
        navLang2: 'en_GB',
        navCta: 'run it',
        sideNote: '● REC · VT220 · 80×24 · 9600 8N1',
        laurel1b: 'tty06',
        laurel1: 'terminal 5.0.0',
        laurel2b: '93',
        laurel2: 'tokens at parity',
        laurel3b: '1 Hz',
        laurel3: 'the only loop',
        microlabelHero: 'kp@vt220:~$ cat MOTD',
        headline: 'Everything is a character cell.',
        lede1: 'Phosphor green on near-black glass, one monospaced face, no rounded corners. Emphasis is ',
        ledeMark1: 'inverse video',
        lede2: '; a boundary is ',
        ledeMark2: 'a dimmer phosphor',
        lede3: '. The screen draws with what it has, and it has one colour.',
        btnPrimary: 'run the demo',
        btnSecondary: 'read the man page',
        btnGhost: 'dry run',
        platform1: 'chromium',
        platform2: 'firefox',
        platform3: 'framework-free',
        platform4: 'react',
        spec1: 'ground: void #0B0E0B',
        spec2: 'panel: well #0F140F',
        spec3: 'text: phosphor #68F368',
        spec4: 'plate: bright #0DF20D',
        spec5: 'muted: dim #86B686',
        spec6: 'accent: signal #DFF20D',
        spec7: 'alarm: red #F54747',
        spec8: 'face: Share Tech Mono 400 — the only face',
        microlabelForm: 'kp@vt220:~$ ./request --handle',
        h2Form: 'Request a handle',
        handleLabel: 'handle',
        handlePlaceholder: 'v.night',
        handleHelp: 'lowercase, dots allowed, no spaces',
        mailLabel: 'contact',
        mailPlaceholder: 'you@vt220.net',
        mailHelp: 'we answer within one session',
        districtLabel: 'tty',
        district1: 'tty0 — console',
        district2: 'tty1 — serial',
        district3: 'pts/0 — pseudo',
        district4: 'screen — multiplexed',
        whyLabel: 'why you',
        whyPlaceholder: 'Two lines. Eighty columns each.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'send request',
        btnWipe: 'wipe form',
        wipeConfirm: 'wipe — y/n?',
        microlabelDossier: 'dossier.terminal-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'terminal',
        stampLabel: 'CLASSIFIED',
        stampLabelOpen: 'DECLASSIFIED',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A phosphor CRT theme. Cyberpunk is ',
        dossierMark1: 'loud and diagonal',
        dossier2: '; this one is ',
        dossierMark2: 'quiet and gridded',
        dossier3: ': eighty columns, twenty-four rows, and ',
        dossierMark3: 'one hue at 120°',
        dossier4: '. It does not merely look like a terminal — it accepts a terminal\u0027s constraints.',
        dossierPara2:
            'Open the file to clear the redactions. They repaint left to right, one cell at a time, the way a screen draws a line — not the way a curtain opens.',
        dossierTrigger: 'open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'registers',
        footerCol2a: 'plain',
        footerCol2b: 'expressive',
        footerCol2c: 'terminal fx',
        footerCol3: 'channels',
        footerCol3a: 'framework-free',
        footerCol3b: 'react',
        footerCol3c: 'home assistant',
        footerFine: '$ build 5.0.0-preview · rendered from tokens · no phosphor was burned',
        arrivalLine: 'KP-THEMES BIOS v5.0.0 · MEMORY TEST ......... 640K OK · PHOSPHOR PROFILE .... terminal · CRT WARM-UP ......... OK · READY.',
        arrivalReady: 'READY.',
    },
    brutalism: {
        brand: 'kp-themes',
        brandTag: 'THM//12',
        navThemes: 'Themes',
        navThemes1: 'Brutalism',
        navThemes2: 'Signal',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Plates',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'NO BLUR · NO GRADIENT · RADIUS 0',
        laurel1b: '"Flat by exaggeration"',
        laurel1: 'the anatomy',
        laurel2b: '93 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'one marquee, no flash',
        microlabelHero: 'theme 12 · preview build',
        headline: 'Hard lines. Hard shadow. No apology.',
        lede1: 'Off-white paper, a three-pixel black line, and a shadow that sits exactly where the box would fall ',
        ledeMark1: 'if you let go',
        lede2: '. Candy plates, black ink, ',
        ledeMark2: 'nothing blurred',
        lede3: '. A brutalist theme for kp-themes that behaves like printed matter, not a surface.',
        btnPrimary: 'Try the demo',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'Paper #FFFCF0',
        spec2: 'Ink #121212',
        spec3: 'Signal red #F43333',
        spec4: 'Yellow #FFD633',
        spec5: 'Lavender #B9A6F2',
        spec6: 'Archivo Black',
        spec7: 'Space Grotesk 400–700',
        spec8: 'System ui-monospace',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a handle',
        handleLabel: 'Handle',
        handlePlaceholder: 'k.passenier',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@paper.press',
        mailHelp: 'We answer in one working day.',
        districtLabel: 'Your plate',
        district1: 'Yellow',
        district2: 'Lavender',
        district3: 'Mint',
        district4: 'Sky',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe — sure?',
        microlabelDossier: 'dossier.kp-themes-12',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Brutalism',
        stampLabel: 'Sealed',
        stampLabelOpen: 'Open',
        dossierMeta: 'FILE 12 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'Neo-brutalism, the 2021 kind, not the concrete of the 1960s. Black is ',
        dossierMark1: 'the structure',
        dossier2: '; the shadow is ',
        dossierMark2: 'a knob, not a rule',
        dossier3: '; and the loud colour is ',
        dossierMark3: 'the common one',
        dossier4: '. Nothing is blurred, nothing is translucent, nothing pretends to be a material.',
        dossierPara2: 'Open the file to lift the bars. They go one after another, the way a redaction pen is dragged off a page — not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Brutalism',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED · NO GRADIENTS · NO BLUR · RADIUS 0',
        arrivalLine: '',
        arrivalReady: '',
    },
    'shade-dark': {
        brand: 'kp-themes',
        brandTag: 'SD//06',
        navThemes: 'Themes',
        navThemes1: 'Shade (light)',
        navThemes2: 'Shade (dark)',
        navThemes3: 'Nishiki',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'ED. II · NIGHT DESK · BASE03',
        laurel1b: 'Solarized, mirrored',
        laurel1: 'same scheme, lightness flipped',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'nothing loops',
        microlabelHero: 'register · shade, dark half',
        headline: 'Legible after the lights go down.',
        lede1: "Solarized's own ground, lifted for reading — ",
        ledeMark1: 'medium contrast',
        lede2: ' where white would glare, ',
        ledeMark2: 'plates that hold the line',
        lede3: ' where a boundary has to be seen.',
        btnPrimary: 'Open the desk',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'alert',
        spec4: 'accent',
        spec5: 'chart',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request access',
        handleLabel: 'Handle',
        handlePlaceholder: 'n.reyes',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@nightdesk.io',
        mailHelp: 'We read the night desk once a shift.',
        districtLabel: 'Desk',
        district1: 'Night desk',
        district2: 'Wire desk',
        district3: 'Archive',
        district4: 'Standing bureau',
        whyLabel: 'Why',
        whyPlaceholder: 'Two lines. Keep it plain.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.shade-dark-06',
        h2Dossier: 'The theme, on record',
        cardTitle: 'Shade',
        stampLabel: 'Classified',
        stampLabelOpen: 'Lifted',
        dossierMeta: 'FILE 06 · STATUS: LIFTED · CLEARANCE: KENNY',
        dossier1: 'The dark half mirrors ',
        dossierMark1: "the light half's own scheme",
        dossier2: ' rather than inventing a second palette; the ground moved from ',
        dossierMark2: "Solarized's paper",
        dossier3: ' to ',
        dossierMark3: 'its base03 ink',
        dossier4: ', and every accent lifted to match.',
        dossierPara2: 'Open the file to clear the redactions. They lift left to right, the way a document does when the clearance comes through.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Themes',
        footerCol2a: 'Shade (light)',
        footerCol2b: 'Shade (dark)',
        footerCol2c: 'Nishiki',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// SHADE, DARK HALF · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    tazhib: {
        brand: 'Lapis & Leaf',
        brandTag: 'MS//07',
        navThemes: 'Folios',
        navThemes1: 'Diwan pages',
        navThemes2: 'Frontispieces',
        navThemes3: 'Marginalia',
        navComponents: 'Workshop',
        navComponents1: 'Pigments',
        navComponents2: 'Gold ground',
        navComponents3: 'Ruling',
        navEffects: 'Commissions',
        navDocs: 'Colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request a folio',
        sideNote: 'MS · SAFAVID HAND · f.1r',
        laurel1b: '“Gold acts.”',
        laurel1: "the anatomy's own rule",
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'the ruling never flashes',
        microlabelHero: 'atelier · folio 07 · new commission',
        headline: 'Every page begins in gold.',
        lede1: 'Lapis for the ground, gold for the ruling, and vermilion where the eye must stop. Ten-fold geometry drawn once, felt ',
        ledeMark1: 'everywhere it repeats',
        lede2: ', seen nowhere as a flourish — a single hand, disciplined the way ',
        ledeMark2: 'a manuscript page is disciplined',
        lede3: '.',
        btnPrimary: 'Open a commission',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'See the ruling',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'gold',
        spec4: 'vermilion',
        spec5: 'jade',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'workshop.request_form',
        h2Form: 'Commission a folio',
        handleLabel: 'Patron',
        handlePlaceholder: 'Farrukh Beg',
        handleHelp: 'The name entered in the colophon.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@atelier.example',
        mailHelp: 'We answer within one moon.',
        districtLabel: 'Ground',
        district1: 'Lapis lazuli',
        district2: 'Verdigris wash',
        district3: 'Plain vellum',
        district4: 'Gold ground',
        whyLabel: 'Brief',
        whyPlaceholder: 'Two lines. The border carries the rest.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send the commission',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.folio-07',
        h2Dossier: 'The commission, on record',
        cardTitle: 'Folio 07',
        stampLabel: 'Classified',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 07 · STATUS: IN THE WORKSHOP · HAND: UNVERIFIED',
        dossier1: 'The commission was placed by ',
        dossierMark1: "Farrukh Beg's workshop",
        dossier2: ' for a sum of ',
        dossierMark2: '140 dinars',
        dossier3: ', delivery promised by ',
        dossierMark3: 'the spring new moon',
        dossier4: '. Every ring on the frame is one declaration; every star repeats at 36 degrees and never once as decoration.',
        dossierPara2:
            "Lift the seal to read it whole. The ground clears left to right, the way a gilder's burnish reveals gold that was always there — not all at once.",
        dossierTrigger: 'Lift the seal',
        footerTitle: 'Lapis & Leaf',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Folios',
        footerCol2a: 'Diwan pages',
        footerCol2b: 'Frontispieces',
        footerCol2c: 'Marginalia',
        footerCol3: 'Workshop',
        footerCol3a: 'Pigments',
        footerCol3b: 'Gold ground',
        footerCol3c: 'Ruling',
        footerFine: '/// TAZHIB · RENDERED FROM TOKENS · NO GOLD LEAF WAS HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    'high-contrast': {
        brand: 'kp-themes',
        brandTag: 'AAA//21:1',
        navThemes: 'Theme',
        navThemes1: 'Anatomy',
        navThemes2: 'Tokens',
        navThemes3: 'Invariants',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'AAA · WCAG 2.2 · 21:1',
        laurel1b: '21:1',
        laurel1: 'ink on paper',
        laurel2b: '96 tokens',
        laurel2: 'parity gate',
        laurel3b: '0 gradients',
        laurel3: 'nothing to fade',
        microlabelHero: 'accessibility floor · reference build',
        headline: 'Built to be read, not admired.',
        lede1: 'Twenty-one to one, ',
        ledeMark1: 'every time',
        lede2: '. One accent colour with a job, ',
        ledeMark2: 'never a decoration',
        lede3: '. This is kp-themes for the reader who needs contrast, not comfort.',
        btnPrimary: 'Read the anatomy',
        btnSecondary: 'See the tokens',
        btnGhost: 'No fill',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'page',
        spec3: 'alert',
        spec4: 'signal',
        spec5: 'flag',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'form.request',
        h2Form: 'Request access',
        handleLabel: 'Name',
        handlePlaceholder: 'Jordan Reyes',
        handleHelp: 'As it should appear on the record.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within one business day.',
        districtLabel: 'Reason for access',
        district1: 'Low vision',
        district2: 'Bright-daylight use',
        district3: 'End-of-shift fatigue',
        district4: 'Other',
        whyLabel: 'Notes',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: "Wipe everything you've typed?",
        microlabelDossier: 'dossier.high-contrast',
        h2Dossier: 'The record, unredacted',
        cardTitle: 'Who this theme is for',
        stampLabel: 'On record',
        stampLabelOpen: 'On record',
        dossierMeta: 'FILE 06 · STATUS: PREVIEW · CLEARANCE: AAA',
        dossier1: 'This is the theme for someone who finds the other twenty-four too soft: ',
        dossierMark1: 'low vision',
        dossier2: ', ',
        dossierMark2: 'a screen in daylight',
        dossier3: ', or ',
        dossierMark3: 'tired eyes at the end of a shift',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Related themes',
        footerCol2a: 'Formal',
        footerCol2b: 'Light',
        footerCol2c: 'Blueprint',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    mono: {
        brand: 'mono',
        brandTag: 'MN//20',
        navThemes: 'Themes',
        navThemes1: 'Mono',
        navThemes2: 'Formal',
        navThemes3: 'Grotesk',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Tables',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'REV 5.0 · FILE 20 · GREYSCALE ONLY',
        laurel1b: 'Ink over paper',
        laurel1: 'the whole idea',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'register 20 · preview build',
        headline: 'The ink is the only brand here.',
        lede1: 'Every colour that means something elsewhere is a grey here — status, state, emphasis, all read by ',
        ledeMark1: 'lightness',
        lede2: ', not hue. Charts get a pattern as well as a shade, so five greys between 9% and 55% are told apart by ',
        ledeMark2: 'texture before anyone squints',
        lede3: '.',
        btnPrimary: 'Open the dossier',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground: paper #FAFAFA',
        spec2: 'paper: card #FFFFFF',
        spec3: 'ink: foreground #171717',
        spec4: 'action: primary #242424',
        spec5: 'boundary: border-strong #808080',
        spec6: 'display: Geist Mono 600',
        spec7: 'body: Inter Tight 400',
        spec8: 'mono: Geist Mono 400 — the theme\u0027s one voice',
        microlabelForm: 'access.review_form',
        h2Form: 'Request a review',
        handleLabel: 'Reference',
        handlePlaceholder: 'A. Reader',
        handleHelp: 'How the file will read.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'Department',
        district1: 'Records',
        district2: 'Archive',
        district3: 'Redaction',
        district4: 'Standards',
        whyLabel: 'Why you',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit review',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe this form?',
        microlabelDossier: 'dossier.mono-20',
        h2Dossier: 'The file, on record',
        cardTitle: 'Mono',
        stampLabel: 'Classified',
        stampLabelOpen: 'Classified',
        dossierMeta: 'FILE 20 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A greyscale register for kp-themes, built from ',
        dossierMark1: 'rauno.me and Vercel\u0027s Geist',
        dossier2: ' tokens. The ink sits at ',
        dossierMark2: '9% lightness, the action a step above it at 14%',
        dossier3: ' so a visited link has room to move. ',
        dossierMark3: 'No hue, anywhere — not even in the destructive button',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, ink receding left to right, not all at once.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Mono',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-ALPHA · RENDERED FROM TOKENS · GREYSCALE ONLY',
        arrivalLine: '',
        arrivalReady: '',
    },
    solstice: {
        brand: 'Low Sun',
        brandTag: '',
        navThemes: 'Field guide',
        navThemes1: 'Palette & type',
        navThemes2: 'Try the form',
        navThemes3: 'Field notes',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Fields',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Get warm',
        sideNote: 'VOL. III · LOW SUN · 28°',
        laurel1b: 'No neon',
        laurel1: 'firelight only',
        laurel2b: 'Still legible',
        laurel2: 'every boundary holds',
        laurel3b: 'Unhurried',
        laurel3: '240ms, the slowest',
        microlabelHero: 'Firelight, not screenlight',
        headline: 'Warm dark, calibrated.',
        lede1: 'Solstice trades neon for firelight: an interface tuned like ',
        ledeMark1: "a print before it's fixed",
        lede2: ', where amber leads and rust follows, and ',
        ledeMark2: 'every boundary still holds its line',
        lede3: '.',
        btnPrimary: 'Open the field guide',
        btnSecondary: 'See the palette',
        btnGhost: 'Read the anatomy',
        platform1: 'macOS',
        platform2: 'Windows',
        platform3: 'the open web',
        platform4: 'Linux',
        spec1: 'ground',
        spec2: 'page',
        spec3: 'alert',
        spec4: 'rust',
        spec5: 'ember',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'request.notebook',
        h2Form: 'Try it warm',
        handleLabel: 'Name',
        handlePlaceholder: 'Your name',
        handleHelp: 'As it appears on the file.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We reply before the light changes.',
        districtLabel: 'Desk',
        district1: 'Editorial',
        district2: 'Field',
        district3: 'Archive',
        district4: 'Studio',
        whyLabel: 'Notes',
        whyPlaceholder: 'Two lines. Keep them warm.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.solstice-18',
        h2Dossier: 'Field notes, on record',
        cardTitle: 'Low Sun — Round Six',
        stampLabel: 'On file',
        stampLabelOpen: 'On file',
        dossierMeta: 'FILE 18 · STATUS: LIFT · REGISTER: SOLSTICE',
        dossier1: 'Solstice keeps its palette close: primary and accent are ',
        dossierMark1: 'the only pair in the set that share a hue family',
        dossier2: ', the radius is ',
        dossierMark2: 'the softest of the twenty-five',
        dossier3: ', and reduced motion still holds — ',
        dossierMark3: '240ms is the slowest resting duration of all eleven lifted themes',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the marks. They lift right to left, one after another, the way a page catches the last of the light.',
        dossierTrigger: 'Reveal the notes',
        footerTitle: 'Low Sun',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Solstice',
        footerCol2b: 'Sepia',
        footerCol2c: 'Dark',
        footerCol3: 'Elsewhere',
        footerCol3a: 'Documentation',
        footerCol3b: 'Changelog',
        footerCol3c: 'Source',
        footerFine: '/// theme: solstice · concept demo · round six lift · no images were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    sepia: {
        brand: 'kp-themes',
        brandTag: 'the sepia specimen',
        navThemes: 'themes',
        navThemes1: 'formal',
        navThemes2: 'sepia',
        navThemes3: 'solstice',
        navComponents: 'components',
        navComponents1: 'buttons',
        navComponents2: 'forms',
        navComponents3: 'dossiers',
        navEffects: 'essays',
        navDocs: 'colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'reserve a copy',
        sideNote: 'every hue between 24° and 45°',
        laurel1b: 'long-form',
        laurel1: 'not dashboards',
        laurel2b: '94 tokens',
        laurel2: 'at parity',
        laurel3b: '220ms',
        laurel3: 'the slowest fade in the set',
        microlabelHero: 'from the margin',
        headline: 'A page that has aged well.',
        lede1: 'Warm parchment, brown ink, and not one cool hue in the body. This is the only theme built for ',
        ledeMark1: 'long reading',
        lede2: " rather than for dashboards — restful in a way the others aren't, and ",
        ledeMark2: 'never in a hurry to prove it',
        lede3: '.',
        btnPrimary: 'reserve a copy',
        btnSecondary: 'read the specimen',
        btnGhost: 'preview a page',
        platform1: 'chromium',
        platform2: 'firefox',
        platform3: 'framework-free',
        platform4: 'react',
        spec1: 'paper #F6F1E9',
        spec2: 'ink #3B2816',
        spec3: 'sienna #7E4925',
        spec4: 'rule #A0856A',
        spec5: 'mark #EFDBC8',
        spec6: 'danger #9B3227',
        spec7: 'Instrument Serif, italic',
        spec8: 'Instrument Sans',
        microlabelForm: 'request.reading_copy',
        h2Form: 'Reserve a reading copy',
        handleLabel: 'name',
        handlePlaceholder: 'V. Night',
        handleHelp: 'Whatever name suits the copy.',
        mailLabel: 'email',
        mailPlaceholder: 'you@longreading.press',
        mailHelp: 'We answer eventually, and gladly.',
        districtLabel: 'edition',
        district1: 'reading copy — unbound',
        district2: 'library binding',
        district3: 'facsimile, numbered',
        district4: 'digital only',
        whyLabel: 'why this one',
        whyPlaceholder: "A line or two. There's no rush.",
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'send request',
        btnWipe: 'wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'specimen.sepia-09',
        h2Dossier: 'The specimen, on file',
        cardTitle: 'sepia',
        stampLabel: 'specimen — sepia',
        stampLabelOpen: 'specimen — sepia',
        dossierMeta: 'FILE 09 · STATUS: reference demo · ROUND SIX',
        dossier1: 'Cyberpunk shouts in ',
        dossierMark1: 'signal yellow on a void',
        dossier2: '; sepia ',
        dossierMark2: 'sits still and reads',
        dossier3: '. The palette holds to ',
        dossierMark3: 'one warm family, twenty-four to forty-five degrees',
        dossier4: ', and nothing here is trying to be seen from across the room.',
        dossierPara2:
            'Open the file to clear the redactions. Each bar lifts left to right, the way ink lifts off a page under a blade — not the way a curtain opens.',
        dossierTrigger: 'open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'registers',
        footerCol2a: 'cyberpunk',
        footerCol2b: 'synthwave',
        footerCol2c: 'retro',
        footerCol3: 'channels',
        footerCol3a: 'framework-free',
        footerCol3b: 'react',
        footerCol3c: 'home assistant',
        footerFine: 'Set in Instrument Serif and Instrument Sans · 94 tokens at parity · a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
    formal: {
        brand: 'Fair Copy',
        brandTag: 'A kp-themes specimen',
        navThemes: 'Editions',
        navThemes1: 'The specimen sheet',
        navThemes2: 'Register two: sepia',
        navThemes3: 'Compare all 25',
        navComponents: 'Provenance',
        navComponents1: 'The lift plan',
        navComponents2: 'Research, 2026-09',
        navComponents3: 'Design invariants',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'NL',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'Fair Copy — specimen set, round six',
        laurel1b: 'Vol. VI',
        laurel1: 'round six',
        laurel2b: 'No. 016',
        laurel2: 'specimen sixteen',
        laurel3b: 'MMXXVI',
        laurel3: 'this year',
        microlabelHero: 'The formal register',
        headline: 'A promise set once, and unchanged.',
        lede1: 'Every theme in this package keeps its word: what shipped stays ',
        ledeMark1: 'exactly as it shipped',
        lede2: ', and a new idea becomes ',
        ledeMark2: 'a new version',
        lede3: ', never a silent edit.',
        btnPrimary: 'Request the specimen',
        btnSecondary: 'View the ledger',
        btnGhost: 'Read the promise',
        platform1: 'JobTracker',
        platform2: 'Almanac',
        platform3: 'kyu',
        platform4: 'kp-soft',
        spec1: 'Ground',
        spec2: 'Page',
        spec3: 'Brick',
        spec4: 'Bronze',
        spec5: 'Rust',
        spec6: 'Fraunces',
        spec7: 'Instrument Sans',
        spec8: 'System mono',
        microlabelForm: 'Intake — new correspondence',
        h2Form: 'Correspondence',
        handleLabel: 'Full name',
        handlePlaceholder: 'As it should appear in the ledger',
        handleHelp: 'The name on the specimen record.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'Where the specimen sheet is sent.',
        districtLabel: 'Department',
        district1: 'Editorial',
        district2: 'Production',
        district3: 'Rights',
        district4: 'Archive',
        whyLabel: 'Note',
        whyPlaceholder: 'Anything the desk should know.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit for review',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.fair-copy-016',
        h2Dossier: 'On file',
        cardTitle: 'Fair Copy',
        stampLabel: 'Draft — not for release',
        stampLabelOpen: 'Draft — not for release',
        dossierMeta: 'Dossier — draft 3',
        dossier1: 'Correspondence on file: ',
        dossierMark1: 'Applicant confirmed for the November review',
        dossier2: '. ',
        dossierMark2: 'Reference on file, dated 2026-08-11',
        dossier3: '. ',
        dossierMark3: 'Decision: proceed to the second register',
        dossier4: '.',
        dossierPara2:
            'Open the file to clear the redactions. They lift left to right, the way a redaction pen is dragged off a page — not all at once.',
        dossierTrigger: 'Reveal redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Consumers',
        footerCol2a: 'JobTracker',
        footerCol2b: 'Almanac',
        footerCol2c: 'kyu',
        footerCol3: 'Provenance',
        footerCol3a: 'Round six research',
        footerCol3b: 'Design invariants',
        footerCol3c: 'MIGRATION 5.0.0',
        footerFine: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
    academia: {
        brand: 'kp-themes',
        brandTag: 'VOL. X',
        navThemes: 'Collections',
        navThemes1: 'Marginalia',
        navThemes2: 'The reading room',
        navThemes3: 'The archive',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Sources',
        navDocs: 'Colophon',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Enter the reading room',
        sideNote: 'VOL. X · SECT. 10 · EST. MMXXVI',
        laurel1b: '“The library, at night”',
        laurel1: 'the brief',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flicker',
        microlabelHero: 'theme 10 of 25 · preview edition',
        headline: 'The library, after hours.',
        lede1: 'Ink and mahogany for the room, candle gold for what you can ',
        ledeMark1: 'act on',
        lede2: ', oxblood and forest for what ',
        ledeMark2: 'means something',
        lede3: '. Cormorant for the headings, Lora for the reading — dark academia, without the parchment.',
        btnPrimary: 'Enter the reading room',
        btnSecondary: 'View the syllabus',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'hero',
        spec2: 'ground',
        spec3: 'alarm',
        spec4: 'means',
        spec5: 'marginal',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'reading.room / request',
        h2Form: 'Request a seat',
        handleLabel: 'Name',
        handlePlaceholder: 'M. Verlaine',
        handleHelp: 'As it will appear on the card.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@the-archive.edu',
        mailHelp: 'We answer within one term.',
        districtLabel: 'Discipline',
        district1: 'History',
        district2: 'Literature',
        district3: 'Philosophy',
        district4: 'Classics',
        whyLabel: 'Statement of interest',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.academia-10',
        h2Dossier: 'The room, on record',
        cardTitle: 'Special Collections',
        stampLabel: 'Restricted',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 10 · STATUS: PREVIEW · CLEARANCE: READING ROOM',
        dossier1: 'The tenth theme lifted for round six. Its ground is ',
        dossierMark1: 'ink with a trace of red',
        dossier2: ', its acting colour is ',
        dossierMark2: 'candle gold, held at 58% lightness',
        dossier3: ', and its two plate colours — ',
        dossierMark3: 'oxblood for meaning, forest for the ordinary',
        dossier4: ' — never carry a word of their own.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another.',
        dossierTrigger: 'Open the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Collections',
        footerCol2a: 'Marginalia',
        footerCol2b: 'The reading room',
        footerCol2c: 'The archive',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// CONCEPT DEMO · 94 TOKENS · RENDERED WITHOUT A SINGLE IMAGE',
        arrivalLine: '',
        arrivalReady: '',
    },
    dark: {
        brand: 'kp-themes',
        brandTag: 'DK·15',
        navThemes: 'Themes',
        navThemes1: 'Dark',
        navThemes2: 'Phantom',
        navThemes3: 'Synthwave',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dialogs',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'QUIET HOURS · TEXTURE AT 0.35 · 112 IRREGULAR POINTS',
        laurel1b: '14.85, not 21',
        laurel1: '8% ground, 93% ink — never pure black on pure white',
        laurel2b: 'One hue family',
        laurel2: 'ground, border and muted text all carry the same blue cast',
        laurel3b: 'DI5 safe',
        laurel3: 'every reveal is one change, or bound to your own scroll',
        microlabelHero: 'theme 15 · dark · preview build',
        headline: 'Comfortable in the dark, on purpose.',
        lede1: 'Deep slate, not ',
        ledeMark1: 'true black',
        lede2: ' — the gap holds halation and pupil fatigue down without losing contrast. A light, unsaturated violet lifts off the ground instead of vibrating against it, and ',
        ledeMark2: 'a blue cast',
        lede3: ' runs through every border, shadow and line so grey never reads as an afterthought.',
        btnPrimary: 'Read tonight',
        btnSecondary: 'See the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'void',
        spec3: 'danger',
        spec4: 'accent',
        spec5: 'edge',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.reading_light',
        h2Form: "Set tonight's session",
        handleLabel: 'Reader name',
        handlePlaceholder: 'night owl',
        handleHelp: 'However you want the log to remember you.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'Only used if something needs your attention before morning.',
        districtLabel: 'Reading window',
        district1: 'Just past midnight',
        district2: 'The small hours',
        district3: "Until it's light out",
        district4: 'No fixed hour',
        whyLabel: "What you're reading",
        whyPlaceholder: "Two lines. That's plenty.",
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Save settings',
        btnWipe: 'Wipe the form',
        wipeConfirm: 'This clears every field above. It cannot be undone.',
        microlabelDossier: 'log.kp-themes-15',
        h2Dossier: 'The theme, on the record',
        cardTitle: 'Dark',
        stampLabel: 'Observation 15',
        // invented: the demo's stamp never swaps its label; "Read" is
        // written in its own voice for the dossier's open state.
        stampLabelOpen: 'Read',
        dossierMeta: 'FILE 15 · STATUS: PREVIEW · READ AT: NIGHT',
        dossier1: 'The ordinary dark theme, done properly. The ground sits at 8% lightness with a blue cast, ',
        dossierMark1: 'never true black',
        dossier2: '. The one ornament is a starfield of 112 irregular points, ten with a JWST-style shimmer, ',
        dossierMark2: 'seen, softly',
        dossier3: '. Everything else is quiet on purpose, because the whole job of this theme is ',
        dossierMark3: 'two hours of reading',
        dossier4: '.',
        // invented: the demo's dossier carries one paragraph; this second
        // one is written in its voice, the way every other theme's own
        // second paragraph explains what the trigger does.
        dossierPara2:
            'Open the log to clear the redactions. They lift right to left, one after another, the way a line settles once you have read enough of it to trust it.',
        dossierTrigger: 'Open the log',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Dark',
        footerCol2b: 'Phantom',
        footerCol2c: 'Synthwave',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Build 5.0.0-preview · 94 tokens, one dark ground · no hearts were harmed',
        arrivalLine: '',
        arrivalReady: '',
    },
    nostromo: {
        brand: 'kp-themes',
        brandTag: 'REG//19',
        navThemes: 'Manifest',
        navThemes1: 'Signal',
        navThemes2: 'Synthwave',
        navThemes3: 'Nostromo',
        navComponents: 'Systems',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Signals',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'REG 19 · DECK B · SN 044-7',
        laurel1b: 'The case, not the screen',
        laurel1: 'the thesis',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing, no flicker',
        microlabelHero: 'register 19 · preview build',
        headline: 'Built like the case, not the screen.',
        lede1: 'Warm-grey plastic, thirty years of yellowing, and one orange LED that never blinks. ',
        ledeMark1: 'Ink acts',
        lede2: '. ',
        ledeMark2: 'Orange indicates',
        lede3: '. A cassette-futurism register for kp-themes, working panel first.',
        btnPrimary: 'Open the panel',
        btnSecondary: 'Read the spec',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'plate',
        spec3: 'ink',
        spec4: 'signal',
        spec5: 'LED',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'cargo.manifest_form',
        h2Form: 'Request a berth',
        handleLabel: 'Callsign',
        handlePlaceholder: 'ripley.8',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@freight.co',
        mailHelp: 'We answer within one cycle.',
        districtLabel: 'Deck',
        district1: 'Bridge',
        district2: 'Mid-deck',
        district3: 'Hold',
        district4: 'Engineering',
        whyLabel: 'Cargo notes',
        whyPlaceholder: 'Two lines. Make them count.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Log it',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.kp-themes-19',
        h2Dossier: 'The panel, on file',
        cardTitle: 'The Case',
        stampLabel: 'Sealed',
        stampLabelOpen: 'Cleared',
        dossierMeta: 'FILE 19 · STATUS: PREVIEW · CLEARANCE: KENNY',
        dossier1: 'A nineteenth theme for kp-themes, built as cassette futurism: ',
        dossierMark1: 'warm beige plastic',
        dossier2: ', ',
        dossierMark2: 'one orange LED that never blinks',
        dossier3: ', and ',
        dossierMark3: 'label tape for every plate',
        dossier4: '. Every panel is a token, and every token ships in all twenty-five themes.',
        dossierPara2: 'Open the panel to clear the redactions. They lift together, the way label tape peels — one motion, not a flicker.',
        dossierTrigger: 'Open the panel',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, three registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Signal',
        footerCol2b: 'Synthwave',
        footerCol2c: 'Nostromo',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    blueprint: {
        brand: 'kp-themes',
        brandTag: '/ blueprint',
        navThemes: 'Sheets',
        navThemes1: 'Elevations',
        navThemes2: 'Sections',
        navThemes3: 'Details',
        navComponents: 'Legend',
        navComponents1: 'Line weights',
        navComponents2: 'Annotations',
        navComponents3: 'Symbols',
        navEffects: 'Symbols',
        navDocs: 'Request',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request a set',
        sideNote: 'SHEET 07 · SCALE 1:1 · REV C · 0x1F',
        laurel1b: "Vercel's crosshair",
        laurel1: 'grid intersections, not decoration',
        laurel2b: '96 tokens',
        laurel2: 'one register, nothing hidden',
        laurel3b: 'DI5 clear',
        laurel3: 'nothing here loops or flickers',
        microlabelHero: 'SHEET 07 · BLUEPRINT · REV C',
        headline: 'Draw it before you build it.',
        lede1: "Cyan ink on Prussian blue, ruled like a drawing that hasn't been built yet. Nothing is rendered ",
        ledeMark1: "until it's dimensioned",
        lede2: ', and nothing ships ',
        ledeMark2: 'without a boundary you can see',
        lede3: '.',
        btnPrimary: 'Open the drawing set',
        btnSecondary: 'Read the annotations',
        btnGhost: 'View the sheet index',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'ground',
        spec3: 'alert',
        spec4: 'annotation',
        spec5: 'detail',
        spec6: 'display',
        spec7: 'text',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Request a print',
        handleLabel: 'Drawing number',
        handlePlaceholder: 'DWG-2031-A',
        handleHelp: 'The reference this print is filed under.',
        mailLabel: 'Contact',
        mailPlaceholder: 'drafting@studio.blue',
        mailHelp: 'We answer within one revision cycle.',
        districtLabel: 'Sheet size',
        district1: 'A4',
        district2: 'A3',
        district3: 'A1',
        district4: 'Custom',
        whyLabel: 'Notes',
        whyPlaceholder: 'Annotations go here, one line per revision.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Submit for review',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form?',
        microlabelDossier: 'dossier.blueprint-07',
        h2Dossier: 'The sheet, on file',
        cardTitle: 'Blueprint',
        stampLabel: 'Approved for construction',
        stampLabelOpen: 'As built',
        dossierMeta: 'FILE 07 · STATUS: DRAFT · CLEARANCE: KENNY',
        dossier1: 'The seventh theme lifted for 5.0.0. Where cyberpunk is ',
        dossierMark1: 'a dark blue theme that glows',
        dossier2: ', this one is ',
        dossierMark2: 'a dark blue theme that measures',
        dossier3: ', drawn from ',
        dossierMark3: 'ninety-six tokens, nothing hidden',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. They lift one after another, on request — not all at once.',
        dossierTrigger: 'Lift the redactions',
        footerTitle: 'kp-themes',
        footerBlurb: 'Twenty-five themes, six registers, one promise: a released theme never changes.',
        footerCol2: 'Legend',
        footerCol2a: 'Line weights',
        footerCol2b: 'Annotations',
        footerCol2c: '96 tokens',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// SHEET 07 · DRAWN FROM TOKENS · NO PHOTOGRAPHS WERE TAKEN',
        arrivalLine: '',
        arrivalReady: '',
    },
    grotesk: {
        brand: 'Grotesk',
        brandTag: '',
        navThemes: 'Type',
        navThemes1: 'Weights',
        navThemes2: 'Grid',
        navThemes3: 'Specimen',
        navComponents: 'System',
        navComponents1: 'Tokens',
        navComponents2: 'Components',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Request access',
        sideNote: 'BASEL · MOD. 12 · REV. 03',
        laurel1b: '“Identity by letter, not colour”',
        laurel1: 'the brief',
        laurel2b: '94 tokens',
        laurel2: 'parity gate',
        laurel3b: 'DI5 safe',
        laurel3: 'no flashing',
        microlabelHero: 'grotesk · concept demo',
        headline: 'Twelve columns, one red, no noise.',
        lede1: 'Grotesk is the International Typographic Style built for interfaces: flush-left type, oversized headings and one ',
        ledeMark1: 'signal red',
        lede2: ' that never competes with black. Colour is not the identity here — ',
        ledeMark2: 'the grid is',
        lede3: '.',
        btnPrimary: 'View the grid',
        btnSecondary: 'Read the manual',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'paper',
        spec2: 'ground',
        spec3: 'alarm',
        spec4: 'ink',
        spec5: 'info',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'system.request_form',
        h2Form: 'Request an environment',
        handleLabel: 'Handle',
        handlePlaceholder: 'j.muller-brockmann',
        handleHelp: 'Lowercase, dots allowed, no spaces.',
        mailLabel: 'Contact',
        mailPlaceholder: 'you@basel.ch',
        mailHelp: 'We answer within one working day.',
        districtLabel: 'Studio',
        district1: 'Basel',
        district2: 'Zurich',
        district3: 'Ulm',
        district4: 'Amsterdam',
        whyLabel: 'Brief',
        whyPlaceholder: 'Two lines. Set them flush left.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send request',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.grotesk-12',
        h2Dossier: 'The grid, on record',
        cardTitle: 'Grotesk',
        stampLabel: 'Restricted · Rev. 03',
        stampLabelOpen: 'Cleared · Rev. 03',
        dossierMeta: 'FILE 12 · STATUS: CONCEPT · CLEARANCE: KENNY',
        dossier1: 'The type style is ',
        dossierMark1: 'Helvetica-class, set at 800 for headings',
        dossier2: ', the grid is ',
        dossierMark2: 'twelve columns, ink at four percent',
        dossier3: ', and the identity is carried by ',
        dossierMark3: 'letterform and grid, never by a second hue',
        dossier4: '.',
        dossierPara2: 'Open the file to clear the redactions. Each one cuts away in three steps — not a fade, a decision.',
        dossierTrigger: 'Open the file',
        footerTitle: 'Grotesk',
        footerBlurb: 'The house theme system. Twenty-five themes, six registers, one promise: a released theme never changes.',
        footerCol2: 'Grid',
        footerCol2a: 'Columns',
        footerCol2b: 'Type scale',
        footerCol2c: 'Tokens',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: '/// BUILD 5.0.0-PREVIEW · RENDERED FROM TOKENS · NO IMAGES WERE HARMED',
        arrivalLine: '',
        arrivalReady: '',
    },
    light: {
        brand: 'kp-themes',
        brandTag: '',
        navThemes: 'Themes',
        navThemes1: 'Light',
        navThemes2: 'Pastel',
        navThemes3: 'Formal',
        navComponents: 'Components',
        navComponents1: 'Buttons',
        navComponents2: 'Forms',
        navComponents3: 'Dossiers',
        navEffects: 'Effects',
        navDocs: 'Docs',
        navLang: 'EN',
        navLang1: 'Nederlands',
        navLang2: 'English',
        navCta: 'Try it',
        sideNote: 'THEME 22 · WHITE GROUND · NO ORNAMENT',
        laurel1b: '17.2:1',
        laurel1: 'body on ground',
        laurel2b: '94 tokens',
        laurel2: 'declared, no exceptions',
        laurel3b: '0px',
        laurel3: 'corner notch — this theme cuts no corners',
        microlabelHero: 'theme 22 of 25 · restraint, chosen on purpose',
        headline: 'White isn’t neutral. It’s a decision.',
        lede1: 'Pure white ground, near-black ink, and one indigo that ',
        ledeMark1: 'never apologizes',
        lede2: '. No texture, no display face — just the words, ',
        ledeMark2: 'in focus',
        lede3: '.',
        btnPrimary: 'See the spec sheet',
        btnSecondary: 'Read the anatomy',
        btnGhost: 'Ghost',
        platform1: 'Chromium',
        platform2: 'Firefox',
        platform3: 'Framework-free',
        platform4: 'React',
        spec1: 'ground',
        spec2: 'ink',
        spec3: 'signal',
        spec4: 'label',
        spec5: 'fx',
        spec6: 'display',
        spec7: 'body',
        spec8: 'mono',
        microlabelForm: 'access.request_form',
        h2Form: 'Say what you need',
        handleLabel: 'Name',
        handlePlaceholder: 'Your name',
        handleHelp: 'Two words is plenty.',
        mailLabel: 'Email',
        mailPlaceholder: 'you@example.com',
        mailHelp: 'We answer within a day.',
        districtLabel: 'Where do you work',
        district1: 'Design',
        district2: 'Engineering',
        district3: 'Product',
        district4: 'Other',
        whyLabel: 'Anything else',
        whyPlaceholder: 'Two lines is plenty.',
        termsLabel: 'I understand this theme ships no theme picker of its own.',
        btnSubmit: 'Send',
        btnWipe: 'Wipe form',
        wipeConfirm: 'Wipe the form',
        microlabelDossier: 'dossier.light-22',
        h2Dossier: 'The record, reviewed',
        cardTitle: 'Light',
        stampLabel: 'Reviewed',
        stampLabelOpen: 'Open',
        dossierMeta: 'FILE 22 · STATUS: SHIPPED · CLEARANCE: OPEN',
        dossier1: 'This theme carries ',
        dossierMark1: 'no texture',
        dossier2: ', ',
        dossierMark2: 'no display face',
        dossier3: ' and ',
        dossierMark3: 'no second accent',
        dossier4: '. Everything you see is the content, on a ground that stays exactly white.',
        dossierPara2:
            'Open the file to clear the redactions. They lift one after another, the way a document does when the clearance comes through — not all at once.',
        dossierTrigger: 'Reveal the file',
        footerTitle: 'kp-themes',
        footerBlurb: 'The house theme system. Twenty-five themes, seven registers, one promise: a released theme never changes.',
        footerCol2: 'Registers',
        footerCol2a: 'Light',
        footerCol2b: 'Signal',
        footerCol2c: 'Retro',
        footerCol3: 'Channels',
        footerCol3a: 'Framework-free',
        footerCol3b: 'React',
        footerCol3c: 'Home Assistant',
        footerFine: 'Twenty-five themes, seven registers, one promise: a released theme never changes.',
        arrivalLine: '',
        arrivalReady: '',
    },
};

/** The theme the picker page and every page without its own copy shows. */
export const DEFAULT_COPY_THEME = 'cyberpunk';

/** The themes that carry their own words, in the order they were lifted. */
export const COPY_THEMES = Object.keys(CONCEPT_COPY);

/**
 * The copy a page is rendered with.
 *
 * @param {string} [theme]
 * @returns {ConceptCopy}
 */
export function conceptCopy(theme) {
    return CONCEPT_COPY[theme ?? DEFAULT_COPY_THEME] ?? CONCEPT_COPY[DEFAULT_COPY_THEME];
}
