# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Dark. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal EDF0F3
set -g fish_color_command 1C1F26
set -g fish_color_keyword E9EEF1
set -g fish_color_quote F5B547
set -g fish_color_redirection BDF33F
set -g fish_color_end BDF33F
set -g fish_color_error F86E59
set -g fish_color_param EDF0F3
set -g fish_color_option 7B8693
set -g fish_color_comment 7B8693
set -g fish_color_operator E9EEF1
set -g fish_color_escape 1C1F26
set -g fish_color_autosuggestion 7B8693
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=282C33
set -g fish_color_search_match --background=282C33
set -g fish_pager_color_prefix E9EEF1 --bold
set -g fish_pager_color_completion EDF0F3
set -g fish_pager_color_description 7B8693
set -g fish_pager_color_progress 1C1F26
