# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Nostromo. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 2B2522
set -g fish_color_command C84E1E
set -g fish_color_keyword 312A26
set -g fish_color_quote EDE8DE
set -g fish_color_redirection 326744
set -g fish_color_end 326744
set -g fish_color_error 81210E
set -g fish_color_param 2B2522
set -g fish_color_option 544D45
set -g fish_color_comment 544D45
set -g fish_color_operator 312A26
set -g fish_color_escape C84E1E
set -g fish_color_autosuggestion 544D45
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=B1A591
set -g fish_color_search_match --background=B1A591
set -g fish_pager_color_prefix 312A26 --bold
set -g fish_pager_color_completion 2B2522
set -g fish_pager_color_description 544D45
set -g fish_pager_color_progress C84E1E
