# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Cyberpunk. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal D7D5CC
set -g fish_color_command 00EEFF
set -g fish_color_keyword FDEC08
set -g fish_color_quote FFBB33
set -g fish_color_redirection A166FF
set -g fish_color_end A166FF
set -g fish_color_error EE3A4F
set -g fish_color_param D7D5CC
set -g fish_color_option 959283
set -g fish_color_comment 959283
set -g fish_color_operator FDEC08
set -g fish_color_escape 00EEFF
set -g fish_color_autosuggestion 959283
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=312F37
set -g fish_color_search_match --background=312F37
set -g fish_pager_color_prefix FDEC08 --bold
set -g fish_pager_color_completion D7D5CC
set -g fish_pager_color_description 959283
set -g fish_pager_color_progress 00EEFF
