@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs). Double-click: the whole desktop in KP Blueprint.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\windows\apply.ps1" -Theme blueprint -Pause
