@echo off
rem GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs). Double-click: all KP themes in VS Code; the active theme is left alone.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\windows\install-vscode.ps1" -Pause
