# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Light. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 171B26
set -g fish_color_command DAF5FB
set -g fish_color_keyword 352EB8
set -g fish_color_quote 8F5A00
set -g fish_color_redirection DC7A18
set -g fish_color_end DC7A18
set -g fish_color_error B81E1E
set -g fish_color_param 171B26
set -g fish_color_option 555B6D
set -g fish_color_comment 555B6D
set -g fish_color_operator 352EB8
set -g fish_color_escape DAF5FB
set -g fish_color_autosuggestion 555B6D
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=D9DBDD
set -g fish_color_search_match --background=D9DBDD
set -g fish_pager_color_prefix 352EB8 --bold
set -g fish_pager_color_completion 171B26
set -g fish_pager_color_description 555B6D
set -g fish_pager_color_progress DAF5FB
