# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Solstice. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal EDE7DE
set -g fish_color_command D45535
set -g fish_color_keyword EF8E39
set -g fish_color_quote FBF0DA
set -g fish_color_redirection 7CB654
set -g fish_color_end 7CB654
set -g fish_color_error DB5757
set -g fish_color_param EDE7DE
set -g fish_color_option C0B3A5
set -g fish_color_comment C0B3A5
set -g fish_color_operator EF8E39
set -g fish_color_escape D45535
set -g fish_color_autosuggestion C0B3A5
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=4F4540
set -g fish_color_search_match --background=4F4540
set -g fish_pager_color_prefix EF8E39 --bold
set -g fish_pager_color_completion EDE7DE
set -g fish_pager_color_description C0B3A5
set -g fish_pager_color_progress D45535
