# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Pastel. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 392640
set -g fish_color_command D4EDE0
set -g fish_color_keyword A6306B
set -g fish_color_quote 865818
set -g fish_color_redirection B87D00
set -g fish_color_end B87D00
set -g fish_color_error B92733
set -g fish_color_param 392640
set -g fish_color_option 67556D
set -g fish_color_comment 67556D
set -g fish_color_operator A6306B
set -g fish_color_escape D4EDE0
set -g fish_color_autosuggestion 67556D
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=CDD9E0
set -g fish_color_search_match --background=CDD9E0
set -g fish_pager_color_prefix A6306B --bold
set -g fish_pager_color_completion 392640
set -g fish_pager_color_description 67556D
set -g fish_pager_color_progress D4EDE0
