# GENERATED by kp-themes 7.1.0 (gates/generate-desktop.mjs) — KP Sepia. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal 3B2816
set -g fish_color_command EFDBC8
set -g fish_color_keyword 7E4925
set -g fish_color_quote 7B460A
set -g fish_color_redirection 8A425A
set -g fish_color_end 8A425A
set -g fish_color_error 9B3227
set -g fish_color_param 3B2816
set -g fish_color_option 705A48
set -g fish_color_comment 705A48
set -g fish_color_operator 7E4925
set -g fish_color_escape EFDBC8
set -g fish_color_autosuggestion 705A48
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=D5CEC3
set -g fish_color_search_match --background=D5CEC3
set -g fish_pager_color_prefix 7E4925 --bold
set -g fish_pager_color_completion 3B2816
set -g fish_pager_color_description 705A48
set -g fish_pager_color_progress EFDBC8
