# GENERATED by kp-themes 7.1.0 (gates/generate-windows.mjs) — KP Blueprint. Do not edit.
# fish syntax colours; lives in ~/.config/fish/conf.d/, read at every start.
set -g fish_color_normal DFF2F6
set -g fish_color_command F0A742
set -g fish_color_keyword 51D2EC
set -g fish_color_quote FBEFDA
set -g fish_color_redirection C285E0
set -g fish_color_end C285E0
set -g fish_color_error E25F5A
set -g fish_color_param DFF2F6
set -g fish_color_option A2C2CD
set -g fish_color_comment A2C2CD
set -g fish_color_operator 51D2EC
set -g fish_color_escape F0A742
set -g fish_color_autosuggestion A2C2CD
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=304869
set -g fish_color_search_match --background=304869
set -g fish_pager_color_prefix 51D2EC --bold
set -g fish_pager_color_completion DFF2F6
set -g fish_pager_color_description A2C2CD
set -g fish_pager_color_progress F0A742
